-- name: insert-into-hlstats-Actions

INSERT INTO hlstats_Actions (game, code, reward_player, reward_team, team, description, for_PlayerActions, for_PlayerPlayerActions, for_TeamActions, for_WorldActions) VALUES
('tf', 'flagevent_defended', 1, 0, '', 'Defended the flag', '1', '0', '0', '0'),
('tf', 'flagevent_captured', 5, 1, '', 'Captured the flag', '1', '0', '0', '0'),
('tf', 'flagevent_dropped', -2, 0, '', 'Dropped the flag (while alive)', '1', '0', '0', '0'),
('tf', 'flagevent_dropped_death', 0, 0, '', 'Dropped the flag (on death)', '1', '0', '0', '0'),
('tf', 'flagevent_picked_up', 2, 0, '', 'Picked up the flag', '1', '0', '0', '0'),
('tf', 'killedobject_obj_teleporter', 2, 0, '', 'Destroyed a teleporter', '1', '0', '0', '0'),
('tf', 'killedobject_obj_dispenser', 3, 0, '', 'Destroyed a dispenser', '1', '0', '0', '0'),
('tf', 'killedobject_obj_sentrygun', 4, 0, '', 'Destroyed a sentry gun', '1', '0', '0', '0'),
('tf', 'killedobject_obj_sentrygun_mini', 4, 0, '', 'Destroyed a mini sentry gun', '1', '0', '0', '0'),
('tf', 'builtobject_obj_teleporter', 2, 0, '', 'Built a teleporter', '1', '0', '0', '0'),
('tf', 'builtobject_obj_dispenser', 3, 0, '', 'Built a dispenser', '1', '0', '0', '0'),
('tf', 'builtobject_obj_sentrygun', 3, 0, '', 'Built a sentry gun', '1', '0', '0', '0'),
('tf', 'builtobject_obj_sentrygun_mini', 3, 0, '', 'Built a mini sentry gun', '1', '0', '0', '0'),
('tf', 'captureblocked', 1, 0, '', 'Capture Blocked', '1', '0', '0', '0'),
('tf', 'pointcaptured', 5, 5, '', 'Point Captured', '1', '0', '1', '0'),
('tf', 'kill assist', 2, 0, '', 'Kill Assist', '1', '0', '0', '0'),
('tf', 'builtobject_obj_attachment_sapper', 2, 0, '', 'Attached a Sapper', '1', '0', '0', '0'),
('tf', 'killedobject_obj_attachment_sapper', 1, 0, '', 'Removed a Sapper', '1', '0', '0', '0'),
('tf', 'chargedeployed', 1, 0, '', 'Ubercharge', '1', '0', '0', '0'),
('tf', 'domination', 5, 0, '', 'Domination', '0', '1', '0', '0'),
('tf', 'revenge', 3, 0, '', 'Revenge', '0', '1', '0', '0'),
('tf', 'Round_Win', 0, 10, '', 'Round Win', '0', '0', '1', '0'),
('tf', 'Mini_Round_Win', 0, 5, '', 'Mini-Round Win', '0', '0', '1', '0'),
('tf', 'owner_killedobject_obj_sentrygun', -3, 0, '', 'Disassembled a sentry gun', '1', '0', '0', '0'),
('tf', 'owner_killedobject_obj_sentrygun_mini', -3, 0, '', 'Disassembled a mini sentry gun', '1', '0', '0', '0'),
('tf', 'owner_killedobject_obj_dispenser', -3, 0, '', 'Disassembled a dispenser', '1', '0', '0', '0'),
('tf', 'owner_killedobject_obj_teleporter', -2, 0, '', 'Disassembled a teleporter', '1', '0', '0', '0'),
('tf', 'owner_killedobject_obj_attachment_sapper', -2, 0, '', 'Console-killed sapper', '1', '0', '0', '0'),
('tf', 'backstab', 2, 0, '', 'Backstab Kill', '1', '0', '0', '0'),
('tf', 'headshot', 2, 0, '', 'Headshot Kill', '1', '0', '0', '0'),
('tf', 'kill_assist_medic', 3, 0, '', 'Kill Assist - Medic', '1', '0', '0', '0'),
('tf', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('tf', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('tf', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('tf', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('tf', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('tf', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('tf', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('tf', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('tf', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('tf', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('tf', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('tf', 'sandvich', 0, 0, '', 'Ate a Sandvich', '1', '0', '0', '0'),
('tf', 'crit_kill', 0, 0, '', 'Critical Kill', '1', '0', '0', '0'),
('tf', 'force_suicide', 0, 0, '', 'Force Suicide', '1', '0', '0', '0'),
('tf', 'hit_by_train', 0, 0, '', 'LOL TRAIN''D', '1', '0', '0', '0'),
('tf', 'first_blood', 1, 0, '', 'First Blood', '1', '0', '0', '0'),
('tf', 'steal_sandvich', 2, 0, '', 'Steal Sandvich', '0', '1', '0', '0'),
('tf', 'stun', 0, 0, '', 'Stun', '0', '1', '0', '0'),
('tf', 'drowned', 0, 0, '', 'Drowned', '1', '0', '0', '0'),
('tf', 'pyro_extinguish', 1, 0, '', 'Extinguished Teammate (Pyro)', '1', '0', '0', '0'),
('tf', 'sniper_extinguish', 1, 0, '', 'Extinguished Teammate (Sniper)', '1', '0', '0', '0'),
('tf', 'medic_extinguish', 1, 0, '', 'Extinguished Teammate (Medic)', '1', '0', '0', '0'),
('tf', 'engineer_extinguish', 1, 0, '', 'Extinguished Teammate (Engineer)', '1', '0', '0', '0'),
('tf', 'teleport', 1, 0, '', 'Teleporter used', '1', '0', '0', '0'),
('tf', 'teleport_self', 0, 0, '', 'Teleporter used (self)', '1', '0', '0', '0'),
('tf', 'killed_charged_medic', 1, 0, '', 'Killed charged medic', '1', '0', '0', '0'),
('tf', 'death_sawblade', 0, 0, '', 'LOL SAW''D', '1', '0', '0', '0'),
('tf', 'jarate', 1, 0, '', 'Jarated player', '0', '1', '0', '0'),
('tf', 'shield_blocked', 0, 0, '', 'Blocked with Shield', '0', '1', '0', '0'),
('tf', 'mvp1', 5, 0, '', 'MVP #1', '1', '0', '0', '0'),
('tf', 'mvp2', 3, 0, '', 'MVP #2', '1', '0', '0', '0'),
('tf', 'mvp3', 2, 0, '', 'MVP #3', '1', '0', '0', '0'),
('tf', 'defended_medic', 1, 0, '', 'Defended a Medic', '1', '0', '0', '0'),
('tf', 'buff_deployed', 1, 0, '', 'Deployed Buff Flag', '1', '0', '0', '0'),
('tf', 'escort_score', 1, 0, '', 'Cart Escort', '1', '0', '0', '0'),
('tf', 'airshot_rocket', 0, 0, '', 'Airshot Rocket', '1', '0', '0', '0'),
('tf', 'airshot_headshot', 0, 0, '', 'Airshot Headshot', '1', '0', '0', '0'),
('tf', 'air2airshot_pipebomb', 0, 0, '', 'Airshot Pipebomb (Airborne)', '1', '0', '0', '0'),
('tf', 'air2airshot_rocket', 0, 0, '', 'Airshot Rocket (Airborne)', '1', '0', '0', '0'),
('tf', 'air2airshot_sticky', 0, 0, '', 'Airshot Sticky (Airborne)', '1', '0', '0', '0'),
('tf', 'airblast_player', 0, 0, '', 'Airblast Player', '0', '1', '0', '0'),
('tf', 'airshot_arrow', 0, 0, '', 'Airshot Arrow', '1', '0', '0', '0'),
('tf', 'airshot_flare', 0, 0, '', 'Airshot Flare', '1', '0', '0', '0'),
('tf', 'airshot_pipebomb', 0, 0, '', 'Airshot Pipebomb', '1', '0', '0', '0'),
('tf', 'airshot_sticky', 0, 0, '', 'Airshot Sticky', '1', '0', '0', '0'),
('tf', 'airshot_stun', 0, 0, '', 'Airshot Stun', '1', '0', '0', '0'),
('tf', 'deflected_arrow', 0, 0, '', 'Deflected Arrow', '0', '1', '0', '0'),
('tf', 'deflected_baseball', 0, 0, '', 'Deflected Baseball', '0', '1', '0', '0'),
('tf', 'deflected_flare', 0, 0, '', 'Deflected Flare', '0', '1', '0', '0'),
('tf', 'deflected_jarate', 0, 0, '', 'Deflected Jarate', '0', '1', '0', '0'),
('tf', 'deflected_pipebomb', 0, 0, '', 'Deflected Pipebomb', '0', '1', '0', '0'),
('tf', 'deflected_rocket', 0, 0, '', 'Deflected Rocket', '0', '1', '0', '0'),
('tf', 'deflected_rocket_dh', 0, 0, '', 'Deflected Directhit Rocket', '0', '1', '0', '0'),
('tf', 'rocket_failjump', 0, 0, '', 'Rocket Jump Failure', '1', '0', '0', '0'),
('tf', 'rocket_jump', 0, 0, '', 'Rocket Jump', '1', '0', '0', '0'),
('tf', 'rocket_jump_kill', 0, 0, '', 'Rocket Jump Kill', '1', '0', '0', '0'),
('tf', 'rocket_jumper_kill', 0, 0, '', 'Rocket Jumper Kill', '1', '0', '0', '0'),
('tf', 'sandvich_healself', 0, 0, '', 'Ate Sandvich for Health', '1', '0', '0', '0'),
('tf', 'sticky_failjump', 0, 0, '', 'Sticky Jump Failure', '1', '0', '0', '0'),
('tf', 'sticky_jump', 0, 0, '', 'Sticky Jump', '1', '0', '0', '0'),
('tf', 'sticky_jump_kill', 0, 0, '', 'Sticky Jump Kill', '1', '0', '0', '0'),
('tf', 'sticky_jumper_kill', 0, 0, '', 'Sticky Jumper Kill', '1', '0', '0', '0'),
('tf', 'teleport_again', 0, 0, '', 'Teleported Again (Past 10 Seconds)', '1', '0', '0', '0'),
('tf', 'teleport_self_again', 0, 0, '', 'Teleported Self Again (Past 10 Seconds)', '1', '0', '0', '0'),
('tf', 'teleport_used', 0, 0, '', 'Teleporter Used (Not Own)', '1', '0', '0', '0'),
('tf', 'teleport_used_again', 0, 0, '', 'Teleporter Used Again (Past 10 Seconds) (Not Own)', '1', '0', '0', '0'),
('tf', 'dalokohs', 0, 0, '', 'Ate a Dalokohs Bar', '1', '0', '0', '0'),
('tf', 'dalokohs_healself', 0, 0, '', 'Ate Dalokohs Bar for Health', '1', '0', '0', '0'),
('tf', 'steak', 0, 0, '', 'Ate a Buffalo Steak Sandvich', '1', '0', '0', '0'),
('tf', 'madmilk', 0, 0, '', 'Mad Milking a player', '0', '1', '0', '0'),
('tf', 'scout_extinguish', 1, 0, '', 'Extinguished Teammate (Scout)', '1', '0', '0', '0'),
('tf', 'player_penetration', 4, 0, '', 'Player Penetration', '1', '0', '0', '0'),
('css','Begin_Bomb_Defuse_Without_Kit',0,0,'CT','Start Defusing the Bomb Without a Defuse Kit','1','0','0','0'),
('css','Begin_Bomb_Defuse_With_Kit',0,0,'CT','Start Defusing the Bomb With a Defuse Kit','1','0','0','0'),
('css','Planted_The_Bomb',10,2,'TERRORIST','Plant the Bomb','1','0','0','0'),
('css','Defused_The_Bomb',10,0,'CT','Defuse the Bomb','1','0','0','0'),
('css','Touched_A_Hostage',0,0,'CT','Touch a Hostage','1','0','0','0'),
('css','Rescued_A_Hostage',5,1,'CT','Rescue a Hostage','1','0','0','0'),
('css','Killed_A_Hostage',-15,1,'CT','Kill a Hostage','1','0','0','0'),
('css','Spawned_With_The_Bomb',2,0,'TERRORIST','Spawn with the Bomb','1','0','0','0'),
('css','Got_The_Bomb',2,0,'TERRORIST','Pick up the Bomb','1','0','0','0'),
('css','Dropped_The_Bomb',-2,0,'TERRORIST','Drop the Bomb','1','0','0','0'),
('css','CTs_Win',0,2,'CT','All Terrorists eliminated','0','0','1','0'),
('css','Terrorists_Win',0,2,'TERRORIST','All Counter-Terrorists eliminated','0','0','1','0'),
('css','All_Hostages_Rescued',0,10,'CT','Counter-Terrorists rescued all the hostages','0','0','1','0'),
('css','Target_Bombed',0,5,'TERRORIST','Terrorists bombed the target','0','0','1','0'),
('css','Bomb_Defused',0,5,'CT','Counter-Terrorists defused the bomb','0','0','1','0'),
('css','Escaped_As_VIP',0,10,'CT','VIP escaped','0','0','1','0'),
('css','Assassinated_The_VIP',0,6,'TERRORIST','Terrorists assassinated the VIP','0','0','1','0'),
('css','Became_VIP',1,0,'CT','Become the VIP','1','0','0','0'),
('css','headshot',1,0,'','Headshot','1','0','0','0'),
('css','round_mvp',0,0,'','Round MVP','1','0','0','0'),
('css', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('css', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('css', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('css', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('css', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('css', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('css', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('css', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('css', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('css', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('css', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('css', 'domination', 5, 0, '', 'Domination', '0', '1', '0', '0'),
('css', 'revenge', 3, 0, '', 'Revenge', '0', '1', '0', '0'),
('hl2ctf','ctf_flag_capture',15,0,'','Captured Enemy Flag','1','0','0','0'),
('hl2ctf','ctf_flag_defend',2,0,'','Defended the Flag','1','0','0','0'),
('hl2ctf','ctf_kill_carrier',5,0,'','Killed Enemy Flag Carrier','1','0','0','0'),
('hl2ctf','ctf_flag_return',5,0,'','Returned Flag','1','0','0','0'),
('hl2ctf','ctf_flag_stolen',1,0,'','Stole Enemy Flag','1','0','0','0'),
('hl2ctf','ctf_protect_carrier',5,0,'','Protected Flag Carrier','1','0','0','0'),
('hl2ctf', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('hl2ctf', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('hl2ctf', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('hl2ctf', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('hl2ctf', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('hl2ctf', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('hl2ctf', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('hl2ctf', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('hl2ctf', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('hl2ctf', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('hl2ctf', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('dods','capblock',6,1,'','Capture Blocked','1','0','1','0'),
('dods','captured_loc',6,1,'','Area Captured','1','0','1','0'),
('dods','kill_planter',2,0,'','Bomb Planter Killed','1','0','0','0'),
('dods','bomb_defuse',6,1,'','Bomb Defused','1','0','1','0'),
('dods','bomb_plant',6,1,'','Bomb Planted','1','0','1','0'),
('dods','round_win',0,5,'','Round Win','0','0','1','0'),
('dods', 'domination', 5, 0, '', 'Domination', '0', '1', '0', '0'),
('dods', 'revenge', 3, 0, '', 'Revenge', '0', '1', '0', '0'),
('dods', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('dods', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('dods', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('dods', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('dods', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('dods', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('dods', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('dods', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('dods', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('dods', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('dods', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('hl2mp', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('hl2mp', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('hl2mp', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('hl2mp', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('hl2mp', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('hl2mp', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('hl2mp', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('hl2mp', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('hl2mp', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('hl2mp', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('hl2mp', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('hl2mp', 'headshot', 0, 0, '', 'Headshot Kill', '1', '0', '0', '0'),
('insmod', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('insmod', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('insmod', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('insmod', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('insmod', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('insmod', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('insmod', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('insmod', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('insmod', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('insmod', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('insmod', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('insmod', 'headshot', 1, 0, '', 'Headshot Kill', '1', '0', '0', '0'),
('insmod', 'Round_Win', 0, 10, '', 'Round Win', '0', '0', '1', '0'),
('insmod', 'captured_a', 0, 5, '', 'Captured Objective A', '0', '0', '1', '0'),
('insmod', 'captured_b', 0, 5, '', 'Captured Objective B', '0', '0', '1', '0'),
('insmod', 'captured_c', 0, 5, '', 'Captured Objective C', '0', '0', '1', '0'),
('insmod', 'captured_d', 0, 5, '', 'Captured Objective D', '0', '0', '1', '0'),
('insmod', 'captured_e', 0, 5, '', 'Captured Objective E', '0', '0', '1', '0'),
('ff', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('ff', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('ff', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('ff', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('ff', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('ff', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('ff', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('ff', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('ff', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('ff', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('ff', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('ff', 'headshot', 1, 0, '', 'Headshot kill', '1', '0', '0', '0'),
('ff', 'sentrygun_upgraded', 1, 0, '', 'Upgraded Sentry Gun', '1', '0', '0', '0'),
('ff', 'build_sentrygun', 1, 0, '', 'Built Sentry Gun', '1', '0', '0', '0'),
('ff', 'build_dispenser', 1, 0, '', 'Built Dispenser', '1', '0', '0', '0'),
('ff', 'dispenser_detonated', -1, 0, '', 'Dispenser Detonated', '1', '0', '0', '0'),
('ff', 'sentry_detonated', -1, 0, '', 'Sentry Gun Detonated', '1', '0', '0', '0'),
('ff', 'sentry_dismantled', -1, 0, '', 'Sentry Gun Dismantled', '1', '0', '0', '0'),
('ff', 'dispenser_dismantled', -1, 0, '', 'Dispenser Dismantled', '1', '0', '0', '0'),
('ff', 'build_mancannon', 1, 0, '', 'Built Jump Pad', '1', '0', '0', '0'),
('ff', 'mancannon_detonated', -1, 0, '', 'Detonated Jump Pad', '1', '0', '0', '0'),
('ff', 'build_detpack', 1, 0, '', 'Placed Detpack', '1', '0', '0', '0'),
('ff', 'flag_touch', 3, 0, '', 'Flag Picked Up', '1', '0', '0', '0'),
('ff', 'flag_capture', 3, 0, '', 'Flag Captured', '1', '0', '0', '0'),
('ff', 'flag_dropped', -3, 0, '', 'Flag Dropped', '1', '0', '0', '0'),
('ff', 'flag_thrown', -3, 0, '', 'Flag Thrown', '1', '0', '0', '0'),
('ff', 'disguise_lost', 1, 0, '', 'Uncovered Enemy', '0', '1', '0', '0'),
('hidden', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('hidden', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('hidden', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('hidden', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('hidden', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('hidden', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('hidden', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('hidden', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('hidden', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('hidden', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('hidden', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('zps', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('zps', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('zps', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('zps', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('zps', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('zps', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('zps', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('zps', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('zps', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('zps', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('zps', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('zps', 'headshot', 1, 0, '', 'Headshot Kill', '1', '0', '0', '0'),
('aoc', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('aoc', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('aoc', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('aoc', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('aoc', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('aoc', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('aoc', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('aoc', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('aoc', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('aoc', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('aoc', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('aoc', 'headshot', 2, 0, '', 'Headshot/Decapitate Kill', '1', '0', '0', '0'),
('aoc', 'Round_Win', 0, 2, '', 'Round Win', '0', '0', '1', '0'),
('cstrike','Begin_Bomb_Defuse_Without_Kit',0,0,'CT','Start Defusing the Bomb Without a Defuse Kit','1','0','0','0'),
('cstrike','Begin_Bomb_Defuse_With_Kit',0,0,'CT','Start Defusing the Bomb With a Defuse Kit','1','0','0','0'),
('cstrike','Assassinated_The_VIP',10,0,'TERRORIST','Assassinate the VIP','1','0','0','0'),
('cstrike','Planted_The_Bomb',15,2,'TERRORIST','Plant the Bomb','1','0','0','0'),
('cstrike','Defused_The_Bomb',15,0,'CT','Defuse the Bomb','1','0','0','0'),
('cstrike','Touched_A_Hostage',2,0,'CT','Touch a Hostage','1','0','0','0'),
('cstrike','Rescued_A_Hostage',5,1,'CT','Rescue a Hostage','1','0','0','0'),
('cstrike','Killed_A_Hostage',-25,1,'CT','Kill a Hostage','1','0','0','0'),
('cstrike','Became_VIP',1,0,'CT','Become the VIP','1','0','0','0'),
('cstrike','Spawned_With_The_Bomb',2,0,'TERRORIST','Spawn with the Bomb','1','0','0','0'),
('cstrike','Got_The_Bomb',2,0,'TERRORIST','Pick up the Bomb','1','0','0','0'),
('cstrike','Dropped_The_Bomb',-2,0,'TERRORIST','Drop the Bomb','1','0','0','0'),
('cstrike','CTs_Win',0,2,'CT','All Terrorists eliminated','0','0','1','0'),
('cstrike','Terrorists_Win',0,2,'TERRORIST','All Counter-Terrorists eliminated','0','0','1','0'),
('cstrike','All_Hostages_Rescued',0,10,'CT','Counter-Terrorists rescued all the hostages','0','0','1','0'),
('cstrike','Target_Bombed',0,10,'TERRORIST','Terrorists bombed the target','0','0','1','0'),
('cstrike','VIP_Assassinated',0,6,'TERRORIST','Terrorists assassinated the VIP','0','0','1','0'),
('cstrike','Bomb_Defused',0,6,'CT','Counter-Terrorists defused the bomb','0','0','1','0'),
('cstrike','VIP_Escaped',0,10,'CT','VIP escaped','0','0','1','0'),
('cstrike', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('cstrike', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('cstrike', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('cstrike', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('cstrike', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('cstrike', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('cstrike', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('cstrike', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('cstrike', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('cstrike', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('cstrike', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('cstrike', 'headshot', 1, 0, '', 'Headshot', '1', '0', '0', '0'),
('tfc','rock2_bcave1',2,3,'','(rock2) Blow Red Cave','1','0','0','0'),
('tfc','rock2_rcave1',2,3,'','(rock2) Blow Blue Cave','1','0','0','0'),
('tfc','rock2_rholedet',2,3,'','(rock2) Blow Blue Yard','1','0','0','0'),
('tfc','rock2_bholedet',2,3,'','(rock2) Blow Red Yard','1','0','0','0'),
('tfc','Team 2 dropoff',7,0,'','Captured Blue Flag','1','0','0','0'),
('tfc','Team 1 dropoff',7,0,'','Captured Red Flag','1','0','0','0'),
('tfc','Capture Point 1',2,5,'','Captured Point 1','1','0','0','0'),
('tfc','Capture Point 2',2,5,'','Captured Point 2','1','0','0','0'),
('tfc','Capture Point 3',2,5,'','Captured Point 3','1','0','0','0'),
('tfc','Medic_Infection',2,0,'','Infected Enemy','0','1','0','0'),
('tfc','Medic_Cured_Infection',2,0,'','Cured Infection','1','0','0','0'),
('tfc','Hallucination_Grenade',1,0,'','Hallucination','0','1','0','0'),
('tfc','Concussion_Grenade',1,0,'','Concussion','0','1','0','0'),
('tfc','Teleporter_Entrance_Dismantle',-2,0,'','Teleporter Entrance Dismantled','1','0','0','0'),
('tfc','Teleporter_Entrance_Destroyed',1,0,'','Teleporter Entrance Destroyed','0','1','0','0'),
('tfc','Teleporter_Entrance_Finished',2,0,'','Teleporter Entrance Build','1','0','0','0'),
('tfc','Teleporter_Exit_Dismantle',-2,0,'','Teleporter Exit Dismantled','1','0','0','0'),
('tfc','Teleporter_Exit_Destroyed',1,0,'','Teleporter Exit Destroyed','0','1','0','0'),
('tfc','Teleporter_Exit_Finished',2,0,'','Teleporter Exit Build','1','0','0','0'),
('tfc','Sentry_Built_Level_1',2,0,'','Built Sentry','1','0','0','0'),
('tfc','Sentry_Upgrade_Level_2',1,0,'','Upgraded Sentry to Lvl 2','1','0','0','0'),
('tfc','Sentry_Upgrade_Level_3',1,0,'','Upgraded Sentry to Lvl 3','1','0','0','0'),
('tfc','Sentry_Destroyed',3,0,'','Destroyed Sentry Gun','0','1','0','0'),
('tfc','Sentry_Dismantle',3,0,'','Dismantled Sentry Gun','0','1','0','0'),
('tfc','Dispenser_Dismantle',-2,0,'','Dismantled Dispenser','0','1','0','0'),
('tfc','Discovered_Spy',2,0,'','Discovered a Spy','1','0','0','0'),
('tfc','Dispenser_Destroyed',5,0,'','Dispenser Destroyed','1','0','0','0'),
('tfc','Built_Dispenser',2,0,'','Built Dispenser','1','0','0','0'),
('tfc','headshot',1,0,'','Headshot Kill','1','0','0','0'),
('tfc', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('tfc', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('tfc', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('tfc', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('tfc', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('tfc', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('tfc', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('tfc', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('tfc', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('tfc', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('tfc', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('dod','dod_control_point',6,1,'','Control Points Captured','1','0','1','0'),
('dod','dod_capture_area',6,1,'','Areas Captured','1','0','1','0'),
('dod','dod_object_goal',4,0,'','Objectives Achieved','1','0','0','0'),
('dod', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('dod', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('dod', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('dod', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('dod', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('dod', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('dod', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('dod', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('dod', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('dod', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('dod', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('ns','structure_built',1,0,'','Structures Built','1','0','0','0'),
('ns','structure_destroyed',2,0,'','Structures Destroyed','1','0','0','0'),
('ns','research_start',1,0,'','Researches Performed','1','0','0','0'),
('ns','recycle',-3,0,'','Structures Recycled','1','0','0','0'),
('ns','structure_built_alienresourcetower',1,0,'','Built Alien Resource Tower','1','0','0','0'),
('ns','structure_destroyed_alienresourcetower',2,0,'','Destroyed Alien Resource Tower','1','0','0','0'),
('ns','structure_built_phasegate',1,0,'','Built Phasegate','1','0','0','0'),
('ns','structure_destroyed_phasegate',2,0,'','Destroyed Phasegate','1','0','0','0'),
('ns','structure_built_resourcetower',1,0,'','Built Resource Tower','1','0','0','0'),
('ns','structure_destroyed_resourcetower',2,0,'','Destroyed Resource Tower','1','0','0','0'),
('ns','structure_built_siegeturret',1,0,'','Built Siege Turret','1','0','0','0'),
('ns','structure_destroyed_siegeturret',2,0,'','Destroyed Siege Turret','1','0','0','0'),
('ns','structure_built_team_advturretfactory',1,0,'','Built Advanced Turret Factory','1','0','0','0'),
('ns','structure_destroyed_team_advturretfactory',2,0,'','Destroyed Advanced Turret Factory','1','0','0','0'),
('ns','structure_built_team_armory',1,0,'','Built Armory','1','0','0','0'),
('ns','structure_destroyed_team_armory',2,0,'','Destroyed Armory','1','0','0','0'),
('ns','structure_built_team_turretfactory',1,0,'','Built Turret Factory','1','0','0','0'),
('ns','structure_destroyed_team_turretfactory',2,0,'','Destroyed Turret Factory','1','0','0','0'),
('ns','structure_built_turret',1,0,'','Built Turret','1','0','0','0'),
('ns','structure_destroyed_turret',2,0,'','Destroyed Turret','1','0','0','0'),
('ns','structure_built_team_infportal',1,0,'','Built INF Portal','1','0','0','0'),
('ns','structure_destroyed_team_infportal',2,0,'','Destroyed INF Portal','1','0','0','0'),
('ns','structure_built_defensechamber',1,0,'','Built Defense Chamber','1','0','0','0'),
('ns','structure_destroyed_defensechamber',2,0,'','Destroyed Defense Chamber','1','0','0','0'),
('ns','structure_built_offensechamber',1,0,'','Built Offense Chamber','1','0','0','0'),
('ns','structure_destroyed_offensechamber',2,0,'','Destroyed Offense Chamber','1','0','0','0'),
('ns','structure_built_movementchamber',1,0,'','Built Movement Chamber','1','0','0','0'),
('ns','structure_destroyed_movementchamber',2,0,'','Destroyed Movement Chamber','1','0','0','0'),
('ns','structure_built_team_hive',1,0,'','Built Alien Hive','1','0','0','0'),
('ns','structure_destroyed_team_hive',2,0,'','Destroyed Alien Hive','1','0','0','0'),
('ns','structure_built_team_armslab',1,0,'','Built Arms Lab','1','0','0','0'),
('ns','structure_destroyed_team_armslab',2,0,'','Destroyed Arms Lab','1','0','0','0'),
('ns','structure_built_sensorychamber',1,0,'','Built Sensory Chamber','1','0','0','0'),
('ns','structure_destroyed_sensorychamber',2,0,'','Destroyed Sensory Chamber','1','0','0','0'),
('ns','structure_built_team_prototypelab',1,0,'','Built Prototype Lab','1','0','0','0'),
('ns','structure_destroyed_team_prototypelab',2,0,'','Destroyed Prototype Lab','1','0','0','0'),
('ns','structure_built_team_command',1,0,'','Built Command Unit','1','0','0','0'),
('ns','structure_destroyed_team_command',2,0,'','Destroyed Command Unit','1','0','0','0'),
('ns','structure_built_team_observatory',1,0,'','Built Observatory','1','0','0','0'),
('ns','structure_destroyed_team_observatory',1,0,'','Destroyed Observatory','1','0','0','0'),
('ns','structure_built_team_advarmory',1,0,'','Built Advanced Armory','1','0','0','0'),
('ns','structure_destroyed_team_advarmory',1,0,'','Destroyed Advanced Armory','1','0','0','0'),
('ns','structure_built_scan',1,0,'','Built Scanner','1','0','0','0'),
('ns','structure_destroyed_scan',1,0,'','Destroyed Scanner','1','0','0','0'),
('ns','structure_built_weapon_grenadegun',1,0,'','Created a Grenade Gun','1','0','0','0'),
('ns','structure_built_weapon_heavymachinegun',1,0,'','Created a Heavy Machine Gun','1','0','0','0'),
('ns','structure_built_weapon_shotgun',1,0,'','Created a Shotgun','1','0','0','0'),
('ns','structure_built_weapon_welder',1,0,'','Created a Welder','1','0','0','0'),
('ns','structure_built_weapon_mine',1,0,'','Created a Mine','1','0','0','0'),
('ns','structure_built_item_heavyarmour',1,0,'','Created Heavy Armour','1','0','0','0'),
('ns','structure_built_item_catalyst',1,0,'','Created a Catalyst','1','0','0','0'),
('ns','structure_built_item_genericammo',1,0,'','Created Generic Ammo','1','0','0','0'),
('ns','structure_built_item_health',1,0,'','Created a Healthpack','1','0','0','0'),
('ns','structure_built_item_jetpack',1,0,'','Created a Jetpack','1','0','0','0'),
('ns','research_cancel',-1,0,'','Stopped Researching ','1','0','0','0'),
('ns', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('ns', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('ns', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('ns', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('ns', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('ns', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('ns', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('ns', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('ns', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('ns', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('ns', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('l4d', 'headshot', 0, 0, '', 'Headshot Kill', '1', '0', '0', '0'),
('l4d', 'rescued_survivor', 2, 0, '', 'Rescued Teammate', '1', '0', '0', '0'),
('l4d', 'healed_teammate', 5, 0, '', 'Healed Teammate', '1', '0', '0', '0'),
('l4d', 'revived_teammate', 3, 0, '', 'Revived Teammate', '1', '0', '0', '0'),
('l4d', 'startled_witch', -5, 0, '', 'Startled the Witch', '1', '0', '0', '0'),
('l4d', 'pounce', 6, 0, '', '(Hunter) Pounced on Survivor', '0', '1', '0', '0'),
('l4d', 'tongue_grab', 6, 0, '', '(Smoker) Tongue Grabbed Survivor', '0', '1', '0', '0'),
('l4d', 'vomit', 6, 0, '', '(Boomer) Vomited on Survivor', '0', '1', '0', '0'),
('l4d', 'killed_gas', 1, 0, '', 'Killed a Smoker', '1', '0', '0', '0'),
('l4d', 'killed_exploding', 1, 0, '', 'Killed a Boomer', '1', '0', '0', '0'),
('l4d', 'killed_hunter', 1, 0, '', 'Killed a Hunter', '1', '0', '0', '0'),
('l4d', 'killed_tank', 3, 0, '', 'Killed a Tank', '1', '0', '0', '0'),
('l4d', 'killed_witch', 3, 0, '', 'Killed a Witch', '1', '0', '0', '0'),
('l4d', 'killed_survivor', 25, 0, '', 'Incapacitated/Killed Survivor', '0', '1', '0', '0'),
('l4d', 'friendly_fire', -10, 0, '', 'Friendly Fire', '1', '0', '0', '0'),
('l4d', 'cr0wned', 0, 0, '', 'Cr0wned (killed witch with single headshot)', '1', '0', '0', '0'),
('l4d', 'hunter_punter', 0, 0, '', 'Hunter Punter (melee a Hunter mid-jump)', '1', '0', '0', '0'),
('l4d', 'tounge_twister', 0, 0, '', 'Tounge Twister (kill a Smoker while he is dragging you)', '1', '0', '0', '0'),
('l4d', 'protect_teammate', 0, 0, '', 'Protected Teammate', '1', '0', '0', '0'),
('l4d', 'no_death_on_tank', 0, 0, '', 'No survivors died/incapped from tank', '1', '0', '0', '0'),
('l4d', 'killed_all_survivors', 0, 0, '', 'Killed all survivors', '1', '0', '0', '0'),
('l4d2', 'headshot', 0, 0, '', 'Headshot Kill', '1', '0', '0', '0'),
('l4d2', 'killed_smoker', 1, 0, '', 'Killed a Smoker', '1', '0', '0', '0'),
('l4d2', 'killed_boomer', 1, 0, '', 'Killed a Boomer', '1', '0', '0', '0'),
('l4d2', 'killed_hunter', 1, 0, '', 'Killed a Hunter', '1', '0', '0', '0'),
('l4d2', 'killed_tank', 3, 0, '', 'Killed a Tank', '1', '0', '0', '0'),
('l4d2', 'killed_witch', 3, 0, '', 'Killed a Witch', '1', '0', '0', '0'),
('l4d2', 'killed_spitter', 3, 0, '', 'Killed a Spitter', '1', '0', '0', '0'),
('l4d2', 'killed_jockey', 3, 0, '', 'Killed a Jockey', '1', '0', '0', '0'),
('l4d2', 'killed_charger', 3, 0, '', 'Killed a Charger', '1', '0', '0', '0'),
('l4d2', 'killed_survivor', 25, 0, '', 'Incapacitated/Killed Survivor', '0', '1', '0', '0'),
('l4d2', 'tongue_grab', 6, 0, '', '(Smoker) Tongue Grabbed Survivor', '0', '1', '0', '0'),
('l4d2', 'scavenge_win', 0, 5, '', 'Scavenge Team Win', '0', '0', '1', '0'),
('l4d2', 'versus_win', 0, 5, '', 'Versus Team Win', '0', '0', '1', '0'),
('l4d2', 'defibrillated_teammate', 5, 0, '', 'Defibrillated Teammate', '1', '0', '0', '0'),
('l4d2', 'used_adrenaline', 0, 0, '', 'Used Adrenaline', '1', '0', '0', '0'),
('l4d2', 'jockey_ride', 5, 0, '', 'Going for a ride', '1', '0', '0', '0'),
('l4d2', 'charger_pummel', 5, 0, '', 'Charger Pummeling', '1', '0', '0', '0'),
('l4d2', 'bilebomb_tank', 5, 0, '', 'Tank Bilebombed', '1', '0', '0', '0'),
('l4d2', 'spitter_acidbath', 5, 0, '', 'Spitter Acid', '1', '0', '0', '0'),
('l4d2', 'rescued_survivor', 2, 0, '', 'Rescued Teammate', '1', '0', '0', '0'),
('l4d2', 'healed_teammate', 5, 0, '', 'Healed Teammate', '1', '0', '0', '0'),
('l4d2', 'revived_teammate', 3, 0, '', 'Revived Teammate', '1', '0', '0', '0'),
('l4d2', 'startled_witch', -5, 0, '', 'Startled the Witch', '1', '0', '0', '0'),
('l4d2', 'pounce', 6, 0, '', '(Hunter) Pounced on Survivor', '0', '1', '0', '0'),
('l4d2', 'vomit', 6, 0, '', '(Boomer) Vomited on Survivor', '0', '1', '0', '0'),
('l4d2', 'friendly_fire', -3, 0, '', 'Friendly Fire', '1', '0', '0', '0'),
('l4d2', 'cr0wned', 0, 0, '', 'Cr0wned (killed witch with single headshot)', '1', '0', '0', '0'),
('l4d2', 'hunter_punter', 0, 0, '', 'Hunter Punter (melee a Hunter mid-jump)', '1', '0', '0', '0'),
('l4d2', 'tounge_twister', 0, 0, '', 'Tounge Twister (kill a Smoker while he is dragging you)', '1', '0', '0', '0'),
('l4d2', 'protect_teammate', 0, 0, '', 'Protected Teammate', '1', '0', '0', '0'),
('l4d2', 'no_death_on_tank', 0, 0, '', 'No survivors died/incapped from tank', '1', '0', '0', '0'),
('l4d2', 'killed_all_survivors', 0, 0, '', 'Killed all survivors', '1', '0', '0', '0'),
('fof', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('fof', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('fof', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('fof', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('fof', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('fof', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('fof', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('fof', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('fof', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('fof', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('fof', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('fof', 'loot_drop', -2, 0, '', 'Dropped the loot', '1', '0', '0', '0'),
('fof', 'loot_capture', 8, 0, '', 'Captured the loot', '1', '0', '0', '0'),
('fof', 'carrier_protect', 5, 0, '', 'Protected the carrier', '1', '0', '0', '0'),
('fof', 'headshot', 1, 0, '', 'Headshot Kill', '1', '0', '0', '0'),
('ges', 'headshot', 1, 0, '', 'Headshot Kill', '1', '0', '0', '0'),
('ges', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('ges', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('ges', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('ges', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('ges', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('ges', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('ges', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('ges', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('ges', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('ges', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('ges', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('ges', 'Round_Win', 5, 0, '', 'Round Win', '1', '0', '0', '0'),
('ges', 'Round_Win_Team', 0, 3, '', 'Team Round Win', '0', '0', '1', '0'),
('ges', 'GE_AWARD_DEADLY', 10, 0, '', 'Most Deadly', '1', '0', '0', '0'),
('ges', 'GE_AWARD_HONORABLE', 5, 0, '', 'Most Honorable', '1', '0', '0', '0'),
('ges', 'GE_AWARD_PROFESSIONAL', 10, 0, '', 'Most Professional', '1', '0', '0', '0'),
('ges', 'GE_AWARD_MARKSMANSHIP', 1, 0, '', 'Marksmanship Award', '1', '0', '0', '0'),
('ges', 'GE_AWARD_AC10', 2, 0, '', 'AC-10 Award', '1', '0', '0', '0'),
('ges', 'GE_AWARD_FRANTIC', 2, 0, '', 'Most Frantic', '1', '0', '0', '0'),
('ges', 'GE_AWARD_WTA', 1, 0, '', 'Where''s the Ammo?', '1', '0', '0', '0'),
('ges', 'GE_AWARD_LEMMING', -1, 0, '', 'Lemming (suicide)', '1', '0', '0', '0'),
('ges', 'GE_AWARD_LONGIN', 1, 0, '', 'Longest Innings', '1', '0', '0', '0'),
('ges', 'GE_AWARD_SHORTIN', -1, 0, '', 'Shortest Innings', '1', '0', '0', '0'),
('ges', 'GE_AWARD_DISHONORABLE', -10, 0, '', 'Most Dishonorable', '1', '0', '0', '0'),
('ges', 'GE_AWARD_NOTAC10', 4, 0, '', 'Where''s the Armor?', '1', '0', '0', '0'),
('ges', 'GE_AWARD_MOSTLYHARMLESS', -1, 0, '', 'Mostly Harmless', '1', '0', '0', '0'),
('bg2', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('bg2', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('bg2', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('bg2', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('bg2', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('bg2', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('bg2', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('bg2', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('bg2', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('bg2', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('bg2', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('sgtls', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('sgtls', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('sgtls', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('sgtls', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('sgtls', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('sgtls', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('sgtls', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('sgtls', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('sgtls', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('sgtls', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('sgtls', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('sgtls', 'Goa''uld_Win', 5, 0, '', 'Goa''uld Won Round', '0', '0', '1', '0'),
('sgtls', 'Tau''ri_Win', 5, 0, '', 'Tau''ri Won Round', '0', '0', '1', '0'),
('dystopia', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('dystopia', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('dystopia', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('dystopia', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('dystopia', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('dystopia', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('dystopia', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('dystopia', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('dystopia', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('dystopia', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('dystopia', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('dystopia', 'Capture Guard Post', 2, 0, '', 'Capture Guard Post', '1', '0', '0', '0'),
('dystopia', 'Capture Interior Spawn', 2, 0, '', 'Capture Interior Spawn', '1', '0', '0', '0'),
('dystopia', 'Capture Internal Spawn', 2, 0, '', 'Capture Internal Spawn', '1', '0', '0', '0'),
('dystopia', 'Capture The Docks', 2, 0, '', 'Capture The Docks', '1', '0', '0', '0'),
('dystopia', 'Capture the Inner Base', 2, 0, '', 'Capture the Inner Base', '1', '0', '0', '0'),
('dystopia', 'Capture the Spawn', 2, 0, '', 'Capture the Spawn', '1', '0', '0', '0'),
('dystopia', 'Cut Entrance Spawn Power', 2, 0, '', 'Cut Entrance Spawn Power', '1', '0', '0', '0'),
('dystopia', 'Defend Interior Spawn', 2, 0, '', 'Defend Interior Spawn', '1', '0', '0', '0'),
('dystopia', 'Defend Middle Spawn', 2, 0, '', 'Defend Middle Spawn', '1', '0', '0', '0'),
('dystopia', 'Defend Security JIP', 2, 0, '', 'Defend Security JIP', '1', '0', '0', '0'),
('dystopia', 'Destroy Broadcast Server', 2, 0, '', 'Destroy Broadcast Server', '1', '0', '0', '0'),
('dystopia', 'Destroy Cooling Access Door', 2, 0, '', 'Destroy Cooling Access Door', '1', '0', '0', '0'),
('dystopia', 'Destroy Cooling Tank', 2, 0, '', 'Destroy Cooling Tank', '1', '0', '0', '0'),
('dystopia', 'Destroy The Bulkhead', 2, 0, '', 'Destroy The Bulkhead', '1', '0', '0', '0'),
('dystopia', 'Destroy The Core', 2, 0, '', 'Destroy The Core', '1', '0', '0', '0'),
('dystopia', 'Destroy the Firewall', 2, 0, '', 'Destroy the Firewall', '1', '0', '0', '0'),
('dystopia', 'Destroy the Reactor', 2, 0, '', 'Destroy the Reactor', '1', '0', '0', '0'),
('dystopia', 'Destroy Transformer', 2, 0, '', 'Destroy Transformer', '1', '0', '0', '0'),
('dystopia', 'Enable Auxilary Power Feed', 2, 0, '', 'Enable Auxilary Power Feed', '1', '0', '0', '0'),
('dystopia', 'Enable The 4-Point Override', 2, 0, '', 'Enable The 4-Point Override', '1', '0', '0', '0'),
('dystopia', 'Escort Hostage', 2, 0, '', 'Escort Hostage', '1', '0', '0', '0'),
('dystopia', 'Hack Middle Spawn', 2, 0, '', 'Hack Middle Spawn', '1', '0', '0', '0'),
('dystopia', 'Hack Spawn Controls', 2, 0, '', 'Hack Spawn Controls', '1', '0', '0', '0'),
('dystopia', 'Hack the Perimeter', 2, 0, '', 'Hack the Perimeter', '1', '0', '0', '0'),
('dystopia', 'Inject The Virus', 2, 0, '', 'Inject The Virus', '1', '0', '0', '0'),
('dystopia', 'Launch Missile', 2, 0, '', 'Launch Missile', '1', '0', '0', '0'),
('dystopia', 'Locate profile', 2, 0, '', 'Locate profile', '1', '0', '0', '0'),
('dystopia', 'Maintain Power Routing', 2, 0, '', 'Maintain Power Routing', '1', '0', '0', '0'),
('dystopia', 'Open And Destroy Data Stores / Establish An Uplink', 2, 0, '', 'Open And Destroy Data Stores / Establish An Uplink', '1', '0', '0', '0'),
('dystopia', 'Redirect Laser', 2, 0, '', 'Redirect Laser', '1', '0', '0', '0'),
('dystopia', 'Reroute Power To Control Room', 2, 0, '', 'Reroute Power To Control Room', '1', '0', '0', '0'),
('dystopia', 'Shut Down Security', 2, 0, '', 'Shut Down Security', '1', '0', '0', '0'),
('dystopia', 'Shutdown The Production Line', 2, 0, '', 'hutdown The Production Line', '1', '0', '0', '0'),
('dystopia', 'Smash Data Storage', 2, 0, '', 'Smash Data Storage', '1', '0', '0', '0'),
('dystopia', 'Turn Power Offline', 2, 0, '', 'Turn Power Offline', '1', '0', '0', '0'),
('nts', 'headshot', 5, 0, '', 'Headshot Kill', '1', '0', '0', '0'),
('nts', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('nts', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('nts', 'kill_streak_12', 15, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('nts', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('nts', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('nts', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('nts', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('nts', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('nts', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('nts', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('nts', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('nts', 'Round_Win', 0, 20, '', 'Team Round Win', '0', '0', '1', '0'),
('pvkii', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('pvkii', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('pvkii', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('pvkii', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('pvkii', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('pvkii', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('pvkii', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('pvkii', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('pvkii', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('pvkii', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('pvkii', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('pvkii', 'kill assist', 2, 0, '', 'Kill Assist', '1', '0', '0', '0'),
('pvkii', 'mvp1', 5, 0, '', 'Most Valuable Player #1', '1', '0', '0', '0'),
('pvkii', 'mvp2', 0, 0, '', 'Most Valuable Player #2', '1', '0', '0', '0'),
('pvkii', 'mvp3', 0, 0, '', 'Most Valuable Player #3', '1', '0', '0', '0'),
('pvkii', 'chest_capture', 3, 0, '', 'Chest Capture', '1', '0', '0', '0'),
('pvkii', 'chest_defend', 2, 0, '', 'Chest Defend', '1', '0', '0', '0'),
('pvkii', 'obj_complete', 3, 0, '', 'Complted Objective', '1', '0', '0', '0'),
('pvkii', 'grail_defend', 2, 0, '', 'Defended Grail', '1', '0', '0', '0'),
('pvkii', 'killed_parrot', 1, 0, '', 'Killed Parrot', '1', '0', '0', '0'),
('pvkii', 'domination', 5, 0, '', 'Domination', '0', '1', '0', '0'),
('pvkii', 'revenge', 3, 0, '', 'Revenge', '0', '1', '0', '0'),
('csp', 'headshot', 1, 0, '', 'Headshot', '1', '0', '0', '0'),
('csp', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('csp', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('csp', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('csp', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('csp', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('csp', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('csp', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('csp', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('csp', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('csp', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('csp', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('valve', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('valve', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('valve', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('valve', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('valve', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('valve', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('valve', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('valve', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('valve', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('valve', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('valve', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('valve', 'headshot', 1, 0, '', 'Headshot Kill', '1', '0', '0', '0'),
('nd', 'headshot', 1, 0, '', 'Headshot', '1', '0', '0', '0'),
('nd', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('nd', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('nd', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('nd', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('nd', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('nd', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('nd', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('nd', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('nd', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('nd', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('nd', 'kill_streak_12', 11, 0, '', 'God Like (12 kills)', '1', '0', '0', '0'),
('nd', 'round_win', 0, 20, 'Consortium', 'Consortium Win Round', '0', '0', '1', '0'),
('nd', 'round_win', 0, 20, 'Empire', 'Empire Win Round', '0', '0', '1', '0'),
('nd', 'round_lose', 0, -20, 'Consortium', 'Consortium Lose Round', '0', '0', '1', '0'),
('nd', 'round_lose', 0, -20, 'Empire', 'Empire Lose Round', '0', '0', '1', '0'),
('nd', 'structure_kill', 0, 20, 'Consortium', 'Empire Structure Destroyed', '1', '0', '1', '0'),
('nd', 'structure_kill', 0, 20, 'Empire', 'Consortium Structure Destroyed', '1', '0', '1', '0'),
('nd', 'killed_commander', 5, 0, '', 'Killed the enemy commander', '1', '0', '0', '0'),
('nd', 'promoted_to_commander', 10, 0, '', 'Promoted to commander', '1', '0', '0', '0'),
('nd', 'damaged_opposite_bunker', 0, 1, '', '500dmg at enemy bunker', '0', '0', '1', '0'),
('nd', 'resource_captured', 0, 1, '', 'Captured resource', '0', '0', '1', '0'),
('nd', 'armoury_destroyed', 10, 0, '', 'Destroyed Armory', '1', '0', '0', '0'),
('nd', 'artillery_destroyed', 10, 0, '', 'Destroyed Artillery', '1', '0', '0', '0'),
('nd', 'assembler_destroyed', 10, 0, '', 'Destroyed Assembler', '1', '0', '0', '0'),
('nd', 'flamethrowerturret_destroyed', 10, 0, '', 'Destroyed Empire Flamethrower Turret', '1', '0', '0', '0'),
('nd', 'wirelessrepeater_destroyed', 10, 0, '', 'Destroyed Consortium Wireless Repeater', '1', '0', '0', '0'),
('nd', 'powerstation_destroyed', 10, 0, '', 'Destroyed Power Station', '1', '0', '0', '0'),
('nd', 'radar_destroyed', 10, 0, '', 'Destroyed Radar Station', '1', '0', '0', '0'),
('nd', 'powerrelay_destroyed', 10, 0, '', 'Destroyed Empire Relay Tower', '1', '0', '0', '0'),
('nd', 'rocketturret_destroyed', 10, 0, '', 'Destroyed Rocket Turret', '1', '0', '0', '0'),
('nd', 'sonicturret_destroyed', 10, 0, '', 'Destroyed Consortium Sonic Turret', '1', '0', '0', '0'),
('nd', 'supply_destroyed', 10, 0, '', 'Destroyed Supply Station', '1', '0', '0', '0'),
('nd', 'transportgate_destroyed', 10, 0, '', 'Destroyed Transport Gate', '1', '0', '0', '0'),
('nd', 'machineguneturret_destroyed', 10, 0, '', 'Destroyed Machinegun Turret', '1', '0', '0', '0'),
('csgo', 'Begin_Bomb_Defuse_Without_Kit', 0, 0, 'CT', 'Start Defusing the Bomb Without a Defuse Kit', '1', '0', '0', '0'),
('csgo', 'Begin_Bomb_Defuse_With_Kit', 0, 0, 'CT', 'Start Defusing the Bomb With a Defuse Kit', '1', '0', '0', '0'),
('csgo', 'Planted_The_Bomb', 10, 2, 'TERRORIST', 'Plant the Bomb', '1', '0', '0', '0'),
('csgo', 'Defused_The_Bomb', 10, 0, 'CT', 'Defuse the Bomb', '1', '0', '0', '0'),
('csgo', 'Touched_A_Hostage', 0, 0, 'CT', 'Touch a Hostage', '1', '0', '0', '0'),
('csgo', 'Rescued_A_Hostage', 5, 1, 'CT', 'Rescue a Hostage', '1', '0', '0', '0'),
('csgo', 'Killed_A_Hostage', -15, 1, 'CT', 'Kill a Hostage', '1', '0', '0', '0'),
('csgo', 'Spawned_With_The_Bomb', 2, 0, 'TERRORIST', 'Spawn with the Bomb', '1', '0', '0', '0'),
('csgo', 'Got_The_Bomb', 2, 0, 'TERRORIST', 'Pick up the Bomb', '1', '0', '0', '0'),
('csgo', 'Dropped_The_Bomb', -2, 0, 'TERRORIST', 'Drop the Bomb', '1', '0', '0', '0'),
('csgo', 'SFUI_Notice_CTs_Win', 0, 2, 'CT', 'All Terrorists eliminated', '0', '0', '1', '0'),
('csgo', 'SFUI_Notice_Terrorists_Win', 0, 2, 'TERRORIST', 'All Counter-Terrorists eliminated', '0', '0', '1', '0'),
('csgo', 'SFUI_Notice_All_Hostages_Rescued', 0, 10, 'CT', 'Counter-Terrorists rescued all the hostages', '0', '0', '1', '0'),
('csgo', 'SFUI_Notice_Target_Bombed', 0, 5, 'TERRORIST', 'Terrorists bombed the target', '0', '0', '1', '0'),
('csgo', 'SFUI_Notice_Bomb_Defused', 0, 5, 'CT', 'Counter-Terrorists defused the bomb', '0', '0', '1', '0'),
('csgo', 'Escaped_As_VIP', 0, 10, 'CT', 'VIP escaped', '0', '0', '1', '0'),
('csgo', 'Assassinated_The_VIP', 0, 6, 'TERRORIST', 'Terrorists assassinated the VIP', '0', '0', '1', '0'),
('csgo', 'Became_VIP', 1, 0, 'CT', 'Become the VIP', '1', '0', '0', '0'),
('csgo', 'headshot', 1, 0, '', 'Headshot', '1', '0', '0', '0'),
('csgo', 'round_mvp', 0, 0, '', 'Round MVP', '1', '0', '0', '0'),
('csgo', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('csgo', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('csgo', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('csgo', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('csgo', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('csgo', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('csgo', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('csgo', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('csgo', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('csgo', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('csgo', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
('csgo', 'domination', 5, 0, '', 'Domination', '0', '1', '0', '0'),
('csgo', 'revenge', 3, 0, '', 'Revenge', '0', '1', '0', '0'),
('dinodday', 'headshot', 3, 0, '', 'Boom! Headshot!', '1', '0', '0', '0'),
('dinodday', 'kill_goat', -10, 0, '', 'Defenseless Goat murdered', '1', '0', '0', '0'),
('dinodday', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
('dinodday', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
('dinodday', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
('dinodday', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
('dinodday', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
('dinodday', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
('dinodday', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
('dinodday', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
('dinodday', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
('dinodday', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
('dinodday', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0');