-- name: insert-into-hlstats-Awards

INSERT INTO hlstats_Awards (awardType, game, code, name, verb)
VALUES ('P', 'tf', 'domination', 'Dominator', 'dominations'),
       ('V', 'tf', 'domination', 'Most dominated', 'times dominated'),
       ('P', 'tf', 'revenge', 'King of vengence', 'revenges'),
       ('W', 'tf', 'tf_projectile_pipe_remote', 'Remote Demolition Man', 'pipe bomb kills'),
       ('W', 'tf', 'tf_projectile_pipe', 'Demolition Man', 'pipe bomb kills'),
       ('W', 'tf', 'sniperrifle', 'Top Sniper', 'snipings'),
       ('W', 'tf', 'smg', 'Submachine gun', 'smg kills'),
       ('W', 'tf', 'shotgun_soldier', 'Shotgun Soldier', 'shotgun kills'),
       ('W', 'tf', 'shotgun_pyro', 'Shotgun Pyro', 'shotgun kills'),
       ('W', 'tf', 'shotgun_primary', 'Shotgun', 'shotgun kills'),
       ('W', 'tf', 'scattergun', 'Fast and Furious', 'scattergun kills'),
       ('W', 'tf', 'revolver', 'Wayne', 'revolver kills'),
       ('W', 'tf', 'pistol', 'Pistol', 'pistol kills'),
       ('W', 'tf', 'allsentrykills', 'Engineer', 'sentry kills'),
       ('W', 'tf', 'minigun', 'Terminator', 'minigun kills'),
       ('W', 'tf', 'knife', 'Stabber', 'knifings'),
       ('W', 'tf', 'flamethrower', 'Pyro', 'flame burnings'),
       ('W', 'tf', 'bat', 'Baseball freak', 'bat kills'),
       ('O', 'tf', 'pointcaptured', 'Capturer', 'checkpoint captures'),
       ('O', 'tf', 'kill assist', 'Assistance', 'kill assists'),
       ('O', 'tf', 'captureblocked', 'Blocker', 'checkpoint blockings'),
       ('O', 'tf', 'chargedeployed', 'Ubermedic', 'deployed charges'),
       ('W', 'tf', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'tf', 'tf_projectile_rocket', 'Soldier', 'rocket kills'),
       ('W', 'tf', 'wrench', 'Engineer on Rage', 'wrench kills'),
       ('W', 'tf', 'shovel', 'Grave Digger', 'shovel kills'),
       ('W', 'tf', 'fireaxe', 'Axe-O-Mania', 'axe kills'),
       ('W', 'tf', 'bottle', 'Drunken Demoman', 'bottle kills'),
       ('W', 'tf', 'bonesaw', 'The Saw', 'sawed bones'),
       ('W', 'tf', 'fists', 'Fisting king', 'fistings'),
       ('W', 'tf', 'club', 'Now that''s a knife', 'machete kills'),
       ('W', 'tf', 'pistol_scout', 'Scout Pistol', 'pistol kills'),
       ('W', 'tf', 'shotgun_hwg', 'Shotgun Heavy', 'shotgun kills'),
       ('W', 'tf', 'syringegun_medic', 'The Injector', 'syringe kills'),
       ('W', 'tf', 'axtinguisher', 'Axtinguisher', 'kills with the axtinguisher'),
       ('W', 'tf', 'backburner', 'Backburner', 'burned backs'),
       ('W', 'tf', 'blutsauger', 'Blutsauger', 'times sucked blood'),
       ('W', 'tf', 'flaregun', 'Flare Gun', 'flare gun kills'),
       ('W', 'tf', 'gloves', 'Heavy surgery', 'KGB kills'),
       ('W', 'tf', 'natascha', 'Nataschas Friend', 'Natascha kills'),
       ('W', 'tf', 'ubersaw', 'Ubersaw', 'kills with ubersaw'),
       ('W', 'tf', 'deflect_flare', 'Deflected Flare', 'kills with deflected flare'),
       ('W', 'tf', 'telefrag', 'Lucky Duck', 'kills by telefrag'),
       ('W', 'tf', 'deflect_promode', 'Deflected Grenade', 'kills with deflected grenade'),
       ('W', 'tf', 'deflect_rocket', 'On the Rebound', 'kills with deflected rocket'),
       ('W', 'tf', 'deflect_sticky', 'Deflected Sticky', 'kills with deflected sticky'),
       ('W', 'tf', 'deflect_arrow', 'Deflected Arrow', 'kills with deflected arrow'),
       ('W', 'tf', 'taunt_heavy', 'POW! Ha Ha', 'kills with heavy taunt'),
       ('W', 'tf', 'taunt_pyro', 'Hadouken', 'kills with Hadouken'),
       ('W', 'tf', 'mostkills', 'Most Kills', 'kills'),
       ('W', 'tf', 'bonuspoints', 'Most Bonus Points', 'bonus points'),
       ('O', 'tf', 'sandvich', 'Hungry Hungry Heavy', 'sandviches eaten'),
       ('O', 'tf', 'backstab', 'Backstabber', 'backstabs'),
       ('O', 'tf', 'flagevent_defended', 'Defender of the Flag', 'flag defenses'),
       ('O', 'tf', 'flagevent_captured', 'The Mad Capper', 'flag captures'),
       ('O', 'tf', 'killedobject_obj_dispenser', 'NO METAL FOR YOU!', 'dispensers destroyed'),
       ('O', 'tf', 'killedobject_obj_sentrygun', 'Say no to sentries', 'sentry guns destroyed'),
       ('O', 'tf', 'killedobject_obj_sentrygun_mini', 'Say no to mini sentries', 'mini sentry guns destroyed'),
       ('O', 'tf', 'builtobject_obj_sentrygun', 'Bob the Builder', 'sentry guns built'),
       ('O', 'tf', 'builtobject_obj_sentrygun_mini', 'Mini Bob the Builder', 'mini sentry guns built'),
       ('O', 'tf', 'builtobject_obj_attachment_sapper', 'Super Sapper', 'sappers placed'),
       ('O', 'tf', 'kill_assist_medic', 'Medic Assistance', 'medic assists'),
       ('P', 'tf', 'stun', 'Absolutely Stunning', 'stuns'),
       ('O', 'tf', 'pyro_extinguish', 'Give It a Little Blow', 'extinguishes with Flamethrower'),
       ('O', 'tf', 'sniper_extinguish', 'Douser', 'extinguishes with Jarate'),
       ('O', 'tf', 'medic_extinguish', 'Medic Extinguish', 'extinguishes with Heal Gun'),
       ('O', 'tf', 'engineer_extinguish', 'Engineer Extinguish', 'extinguishes with Dispenser'),
       ('W', 'tf', 'force_a_nature', 'Who wants some of this?', 'kills with the Force-A-Nature'),
       ('W', 'tf', 'ambassador', 'Diplomatic Immunity', 'kills with the Ambassador'),
       ('W', 'tf', 'tf_projectile_arrow', 'Quivering Fool', 'kills with the Huntsman'),
       ('W', 'tf', 'taunt_spy', 'Dangerous Crab', 'spy taunt kills'),
       ('W', 'tf', 'taunt_sniper', 'Robin Hood', 'sniper taunt kills'),
       ('P', 'tf', 'shield_blocked', 'Razor Breakin', 'razorbacks broken'),
       ('V', 'tf', 'shield_blocked', 'Broken Back', 'razorbacks broken (sniper)'),
       ('P', 'tf', 'jarate', 'Urine'' For A Surprise', 'jarates'),
       ('V', 'tf', 'jarate', 'Yellow Bellied Spies', 'victims jarated'),
       ('W', 'tf', 'tf_pumpkin_bomb', 'Pumpkin Bomber', 'kills with a pumpkin bomb'),
       ('O', 'tf', 'mvp1', 'Most Valuable Player', 'wins as Most Valuable Player'),
       ('W', 'tf', 'taunt_scout', 'Not even winded', 'scout taunt kills'),
       ('W', 'tf', 'sandman', 'Batter Up!', 'kills with the Sandman'),
       ('W', 'tf', 'rocketlauncher_directhit', 'Skill Rockets', 'kills with the Direct Hit'),
       ('W', 'tf', 'unique_pickaxe', 'Prospectors Piercings', 'kills with the Equalizer'),
       ('W', 'tf', 'sword', 'Swords a Slicing', 'kills with the Eyelander'),
       ('W', 'tf', 'sticky_resistance', 'Skill Stickies', 'kills with the Scottish Resistance'),
       ('W', 'tf', 'taunt_demoman', 'Sword Swallowers', 'Demoman taunt kills'),
       ('W', 'tf', 'taunt_soldier', 'Good-bye Cruel Worlds', 'Soldier taunt kills'),
       ('O', 'tf', 'buff_deployed', 'Rootin Tootin Shootin', 'Buffs deployed'),
       ('O', 'tf', 'defended_medic', 'Get behind me doctor!', 'Medics defended'),
       ('W', 'tf', 'demoshield', 'Got something for ya!', 'kills with the Chargin'' Targe'),
       ('O', 'tf', 'builtobject_obj_dispenser', 'Dispenser Here!', 'Dispensers built'),
       ('P', 'tf', 'steal_sandvich', 'Mmm, Ham', 'stolen Sandviches'),
       ('O', 'tf', 'teleport', 'One to beam up!', 'players Teleported'),
       ('W', 'tf', 'tf_projectile_arrow_fire', 'Fire Flight', 'kills with the Flaming Huntsman'),
       ('O', 'tf', 'killed_charged_medic', 'Juice Loosener', 'Charged Medics killed'),
       ('W', 'tf', 'ball', 'Fly Ball', 'kills with the Baseball'),
       ('W', 'tf', 'taunt_medic', 'Oktoberfest!', 'medic taunt kills'),
       ('W', 'tf', 'paintrain', 'Come on ride THE PAIN TRAIN', 'kills with The Pain Train'),
       ('W', 'tf', 'sledgehammer', 'Homewreckin', 'kills with The Homewrecker'),
       ('W', 'tf', 'tribalkukri', 'The Tribalman''s Shiv', 'kills with The Tribalman''s Shiv'),
       ('W', 'tf', 'battleaxe', 'Scotsman''s Skullcutter', 'kills with The Scotsman''s Skullcutter'),
       ('W', 'tf', 'frontier_justice', 'Justified Kills', 'kills with the Frontier Justice'),
       ('W', 'tf', 'obj_minisentry', 'It''s Little and Cute and Ben''s Sister Likes It', 'Mini Sentry Gun kills'),
       ('W', 'tf', 'robot_arm', 'Slings Slung', 'kills with the Gunslinger'),
       ('W', 'tf', 'robot_arm_combo_kill', 'One, Two, Punch!', 'Gunslinger Combo Kills'),
       ('W', 'tf', 'robot_arm_blender_kill', 'Mixed ya right up!', 'Engineer taunt kills (Gunslinger)'),
       ('W', 'tf', 'bleed_kill', 'We''ve got a bleeder', 'bleed kills'),
       ('W', 'tf', 'southern_hospitality', 'Southern This!', 'kills with the Southern Hospitality'),
       ('W', 'tf', 'taunt_guitar_kill', 'Despite all my rage there''s a Guitar on your head',
        'Engineer taunt kills (Guitar)'),
       ('W', 'tf', 'wrangler_kill', 'Rustlers Wrangled', 'kills with the Wrangler'),
       ('W', 'tf', 'battleneedle', 'Take your Vita-Saws', 'kills with The Vita-Saw'),
       ('W', 'tf', 'powerjack', 'Powerjacking', 'kills with The Powerjack'),
       ('W', 'tf', 'degreaser', 'Degreased', 'kills with The Degreaser'),
       ('W', 'tf', 'short_stop', 'Stopping Short', 'kills with The Shortstop'),
       ('W', 'tf', 'holy_mackerel', 'Something''s Fishy', 'kills with The Holy Mackerel'),
       ('W', 'tf', 'letranger', 'Ranged', 'kills with the L''Etranger'),
       ('W', 'tf', 'eternal_reward', 'It goes on and on...', 'kills with Your Eternal Reward'),
       ('W', 'tf', 'fryingpan', 'Fried Egg', 'kills with the Frying Pan'),
       ('W', 'tf', 'bushwacka', 'George Bushwacka', 'kills with The Bushwacka'),
       ('W', 'tf', 'gloves_running_urgently', 'It''s Urgent', 'kills with the Gloves of Running Urgently'),
       ('W', 'tf', 'blackbox', 'What''s in the box?', 'kills with The Black Box'),
       ('W', 'tf', 'sydney_sleeper', 'Down Under', 'kills with The Sydney Sleeper'),
       ('O', 'tf', 'dalokohs', 'Dalokohs is delicious!', 'Dalokohs eaten'),
       ('O', 'tf', 'hit_by_train', 'Flattened', 'deaths from train'),
       ('O', 'tf', 'headshot', 'Headache', 'headshots'),
       ('W', 'tf', 'suicide', 'Doctor Assited Suicide', 'suicides'),
       ('O', 'tf', 'steak', 'Don''t Run, Its Just Steak', 'Buffalo Steak Sandviches eaten'),
       ('W', 'tf', 'claidheamohmor', 'Claidheamohmor', 'Claidheamohmor kills'),
       ('W', 'tf', 'back_scratcher', 'Rakes Wrecked', 'Back Scratcher kills'),
       ('W', 'tf', 'boston_basher', 'Boston Basher', 'Boston Basher kills'),
       ('W', 'tf', 'steel_fists', 'My Fists They Are Made Of Steel!', 'kills with the Fists of Steel'),
       ('W', 'tf', 'amputator', 'Amputator', 'Amputator kills'),
       ('W', 'tf', 'crusaders_crossbow', 'Bolts Blown', 'Crusader''s Crossbow kills'),
       ('W', 'tf', 'ullapool_caber', 'Caber''s Clubbed', 'Caber bash kills'),
       ('W', 'tf', 'ullapool_caber_explosion', 'Boom Sticka', 'Caber BOOM kills'),
       ('W', 'tf', 'loch_n_load', 'Loch-n-Load''d', 'Loch-n-Load kills'),
       ('W', 'tf', 'brass_beast', 'Brass Beast', 'Brass Beast kills'),
       ('W', 'tf', 'warrior_spirit', 'Clawed Candyasses', 'Warrior''s Spirit kills'),
       ('W', 'tf', 'candy_cane', 'Canes Cracked', 'Candy Cane kills'),
       ('W', 'tf', 'wrench_jag', 'Jag''d Off', 'Jag kills'),
       ('W', 'tf', 'iron_curtain', 'In Soviet Russia Iron Curtain Owns You', 'Iron Curtain kills'),
       ('W', 'tf', 'headtaker', 'Horseless Headless Horseman''s Headtaker',
        'Horseless Headless Horseman''s Headtaker kills'),
       ('P', 'tf', 'madmilk', 'Creamed', 'Mad Milk hits'),
       ('W', 'tf', 'atomizer', 'Atoms Split', 'Atomizer kills'),
       ('W', 'tf', 'bazaar_bargain', 'Bargins Earned', 'Bazaar Bargain kills'),
       ('W', 'tf', 'demokatana', 'Samurai Swipes', 'Half-Zatoichi kills'),
       ('W', 'tf', 'detonator', 'Detonations Served', 'Detonator kills'),
       ('W', 'tf', 'disciplinary_action', 'Disciplined to Death', 'Disciplinary Action kills'),
       ('W', 'tf', 'enforcer', 'Deaths Enforced', 'Enforcer kills'),
       ('W', 'tf', 'eviction_notice', 'Souls Evicted', 'Eviction Notice kills'),
       ('W', 'tf', 'family_business', 'Cement Shoes Dispensed', 'Family Business kills'),
       ('W', 'tf', 'kunai', 'Spikes Implanted', 'Conniver\'s Kunai kills'),
       ('W', 'tf', 'lava_axe', 'Fragments Fragged', 'Sharpened Volcano Fragment kills'),
       ('W', 'tf', 'lava_bat', 'Afterlives Brightened', 'Sun-on-a-Stick kills'),
       ('W', 'tf', 'liberty_launcher', 'Lives Liberated', 'Liberty Launcher kills'),
       ('W', 'tf', 'mantreads', 'Goombas Stomped', 'Mantreads kills'),
       ('W', 'tf', 'market_gardener', 'Garden Graves Dug', 'Market Gardener kills'),
       ('W', 'tf', 'persian_persuader', 'Persons Persuaded', 'Persian Persuader kills'),
       ('W', 'tf', 'proto_syringe', 'Patients Overdosed', 'Overdose kills'),
       ('W', 'tf', 'reserve_shooter', 'Reservations Made', 'Reserve Shooter kills'),
       ('W', 'tf', 'scout_sword', 'Rune Slices Served', 'Three-Rune Blade kills'),
       ('W', 'tf', 'shahanshah', 'Shahaha UR Dead', 'Shahanshah kills'),
       ('W', 'tf', 'soda_popper', 'Souls Popped', 'Soda Popper kills'),
       ('W', 'tf', 'solemn_vow', 'Busts Busted', 'Solemn Vow kills'),
       ('W', 'tf', 'the_maul', 'Men Mauled', 'Maul kills'),
       ('W', 'tf', 'the_winger', 'Warriors Winged', 'Winger kills'),
       ('W', 'tf', 'tomislav', 'Tomis Tapped', 'Tomislav kills'),
       ('W', 'tf', 'warfan', 'Fans Made', 'Fan O\'War kills'),
       ('W', 'tf', 'big_earner', 'Suckers Stuck', 'Big Earner kills'),
       ('W', 'tf', 'saxxy', 'Hale No', 'Saxxy kills'),
       ('W', 'tf', 'splendid_screen', 'Full Speed Ahead', 'Splendid Screen kills'),
       ('W', 'tf', 'taunt_soldier_lumbricus', 'Hallelujah!', 'Kamikaze (Lumbricus Lid) kills'),
       ('W', 'tf', 'nessieclub', 'Hole in One', 'Nessie\'s Nine Iron kills'),
       ('W', 'tf', 'mailbox', 'Mail\'s Here', 'Postal Pummeler kills'),
       ('O', 'tf', 'scout_extinguish', 'Milk - does a body good', 'extinguishes with Mad Milk'),
       ('W', 'tf', 'cow_mangler', 'Cows Mangled', 'Cow Mangler 5000 kills'),
       ('W', 'tf', 'righteous_bison', 'Bisons Blasted', 'Righteous Bison kills'),
       ('W', 'tf', 'tf_projectile_energy_ball', 'Save A Cow, Eat mor Chikin', 'Deflected Cow Mangler Shot kills'),
       ('W', 'tf', 'machina', 'Problems Solved', 'Machina kills'),
       ('W', 'tf', 'diamondback', 'Souls Rattled', 'Diamondback kills'),
       ('W', 'tf', 'widowmaker', 'Widows Made', 'Widowmaker kills'),
       ('W', 'tf', 'short_circuit', 'Circuits Shorted', 'Short Circuit kills'),
       ('W', 'tf', 'quake_rl', 'Boots Quaked', 'Original kills'),
       ('W', 'tf', 'scotland_shard', 'Hands Shook', 'Scottish Handshake kills'),
       ('W', 'tf', 'nonnonviolent_protest', 'Signed Petitioners', 'Conscientious Objector kills'),
       ('W', 'tf', 'deflect_flare_detonator', 'Reflected Detonation', 'Defected Flare (Detonator) kills'),
       ('W', 'tf', 'deflect_huntsman_flyingburn', 'Reflected Burn', 'Defected Huntsman Burning Arrow kills'),
       ('W', 'tf', 'unarmed_combat', 'Armed Robbery', 'Unarmed Combat kills'),
       ('O', 'tf', 'player_penetration', 'In and Out', 'players penetrated'),
       ('O', 'tf', 'builtobject_obj_teleporter', 'Proceed to android hell', 'teleporters built'),
       ('O', 'tf', 'death_sawblade', 'Blades of Glory', 'deaths to a sawblade'),
       ('O', 'tf', 'killedobject_obj_attachment_sapper', 'Sap This!', 'sappers removed'),
       ('O', 'tf', 'killedobject_obj_teleporter', 'Take a walk!', 'teleporters killed'),
       ('W', 'tf', 'eureka_effect', 'Eureka!', 'Eureka Effect kills'),
       ('W', 'tf', 'holiday_punch', 'The Gift of Punch', 'Holiday Punch kills'),
       ('W', 'tf', 'manmelter', 'Melted Men', 'Manmelter kills'),
       ('W', 'tf', 'phlogistinator', 'Phlogged', 'Phlogistinator kills'),
       ('W', 'tf', 'pomson', 'Convenient Radiation', 'Pomson 6000 kills'),
       ('W', 'tf', 'spy_cicle', 'Cold as ice', 'Spy-cicle kills'),
       ('W', 'tf', 'thirddegree', 'Ooooh burn!', 'Third Degree kills'),
       ('W', 'tf', 'wrap_assassin', 'Wrapping Machine', 'Wrap Assassin kills'),
       ('W', 'tf', 'pep_pistol', 'Lookin Good', 'Pretty Boy\'s Pocket Pistol kills'),
       ('W', 'tf', 'pep_brawlerblaster', 'Baby Face', 'Baby Face\'s Blaster kills'),
       ('W', 'tf', 'dumpster_device', 'Don\'t Beg', 'Beggar\'s Bazooka kills'),
       ('W', 'tf', 'pro_smg', 'Cleaning Time', 'The Cleaner\'s Carbine kills'),
       ('W', 'tf', 'pro_rifle', 'Making Heat', 'The Hitman\'s Heatmaker kills'),
       ('W', 'tf', 'rainblower', 'The Rainman', 'The Rainblower kills'),
       ('W', 'tf', 'lollichop', 'Free Candy', 'The Lollichop kills'),
       ('W', 'tf', 'scorchshot', 'Scorcher', 'The Scorch Shot kills'),
       ('W', 'tf', 'unique_pickaxe_escape', 'The Great Escape', 'The Escape Plan kills'),
       ('O', 'hl2mp', 'headshot', 'Headshot King', 'headshot kills'),
       ('W', 'hl2mp', 'crowbar', '01. (Crowbar) Rebel for Life', 'guys slaughtered and some more fleshwounds'),
       ('W', 'hl2mp', 'physics', '04. (Physics) Bummsmaster', 'kills with the Zeropoint Energyfield Manipulator'),
       ('W', 'hl2mp', 'physbox', '05. (Physbox) Baffmaster', 'hits with this and that'),
       ('W', 'hl2mp', 'stunstick', '02. (Stunstick) Stockmaster', 'guys beatn up'),
       ('W', 'hl2mp', 'pistol', '03. (Pistol) Freakin Pistol Freak', 'times freaked out'),
       ('W', 'hl2mp', 'shotgun', '09. (Pumpgun) Duckmaster', 'kills with the Duckmaster2k'),
       ('W', 'hl2mp', '357', '08. (.357) Peacemaker', 'Killshots'),
       ('W', 'hl2mp', 'smg1', '14. (SMG) SMG Killer', 'kills with the SMGay'),
       ('W', 'hl2mp', 'ar2', '11. (AR2) Rattertante', 'kills with the assault rifle'),
       ('W', 'hl2mp', 'crossbow_bolt', '10. (Crossbow) Robin Hood', 'guys killed instantly'),
       ('W', 'hl2mp', 'slam', '12. (Slam) Trapmaster', 'guys trapped and killed'),
       ('W', 'hl2mp', 'grenade_frag', '06. (Grenade) Nadethrower 2k', 'guys nuked'),
       ('W', 'hl2mp', 'rpg_missile', '16. (RPG) Clumsy Smurf found the RPG!', 'times pissed in the pants'),
       ('W', 'hl2mp', 'combine_ball', '07. (Combine Balls) Ball Player', 'guys set on fire'),
       ('W', 'hl2mp', 'smg1_grenade', '13. (SMG Nade) SMG Nader', 'guys exploded by him'),
       ('W', 'hl2mp', 'latency', '15. (Latency) Lowpinger', 'ms average'),
       ('W', 'hl2mp', 'mostkills', '17. Most Kills', 'kills'),
       ('W', 'hl2mp', 'suicide', '18. Most Suicides', 'suicides'),
       ('W', 'css', 'awp', 'AWP', 'kills with awp'),
       ('W', 'css', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'css', 'galil', 'Galil', 'kills with galil'),
       ('W', 'css', 'famas', 'Fusil Automatique', 'kills with famas'),
       ('W', 'css', 'ak47', 'AK47', 'kills with ak47'),
       ('W', 'css', 'glock', 'Glock', 'kills with glock'),
       ('W', 'css', 'm4a1', 'Colt M4A1 Carbine', 'kills with m4a1'),
       ('W', 'css', 'usp', 'USP Master', 'kills with usp'),
       ('W', 'css', 'm3', 'M3 Shotgun', 'kills with m3 shotgun'),
       ('W', 'css', 'deagle', 'Desert Eagle', 'kills with deagle'),
       ('W', 'css', 'p90', 'P 90', 'kills with p90'),
       ('W', 'css', 'knife', 'Knife Maniac', 'knifings'),
       ('W', 'css', 'elite', 'Dual Berretta Elites', 'kills with elite'),
       ('O', 'css', 'Rescued_A_Hostage', 'Top Hostage Rescuer', 'hostages rescued'),
       ('O', 'css', 'Planted_The_Bomb', 'Top Demolitionist', 'bomb plantings'),
       ('O', 'css', 'Defused_The_Bomb', 'Top Defuser', 'bomb defusions'),
       ('W', 'css', 'aug', 'Steyr Aug', 'kills with aug'),
       ('W', 'css', 'fiveseven', 'Five Seven', 'kills with fiveseven'),
       ('W', 'css', 'g3sg1', 'G3 SG1', 'kills with g3sg1'),
       ('W', 'css', 'm249', 'Para', 'kills with m249'),
       ('W', 'css', 'mac10', 'Mac 10', 'kills with mac10'),
       ('W', 'css', 'mp5navy', 'MP5 Navy', 'kills with mp5'),
       ('W', 'css', 'p228', 'P 228', 'kills with p228'),
       ('W', 'css', 'sg550', 'SG 550', 'kills with sg550'),
       ('W', 'css', 'sg552', 'SG 552', 'kills with sg552'),
       ('W', 'css', 'tmp', 'TMP', 'kills with tmp'),
       ('W', 'css', 'ump45', 'UMP 45', 'kills with ump45'),
       ('W', 'css', 'xm1014', 'XM automatic Shotgun', 'kills with xm1014'),
       ('O', 'css', 'headshot', 'Headshot King', 'shots in the head'),
       ('O', 'css', 'round_mvp', 'Most Valuable Player', 'times earning Round MVP'),
       ('W', 'css', 'scout', 'Scout Elite', 'kills with scout'),
       ('W', 'css', 'hegrenade', 'Top grenadier', 'kills with grenade'),
       ('O', 'css', 'Killed_A_Hostage', 'Top Hostage Killer', 'hostages killed'),
       ('W', 'css', 'mostkills', 'Most Kills', 'kills'),
       ('W', 'css', 'suicide', 'Suicides', 'suicides'),
       ('W', 'css', 'teamkills', 'Team Killer', 'team kills'),
       ('W', 'hl2ctf', 'crowbar', 'Crowbar', 'bludgeonings with ole red'),
       ('W', 'hl2ctf', 'physcannon', 'Anger Issues', 'kills with physics'),
       ('W', 'hl2ctf', 'stunstick', 'Stun Stick', 'kills with stunstick'),
       ('W', 'hl2ctf', 'pistol', 'Pistol', 'kills with pistol'),
       ('W', 'hl2ctf', 'shotgun', 'A freakin 12 gague!', 'kills with shotgun'),
       ('W', 'hl2ctf', '357', 'Clint', 'kills with .357'),
       ('W', 'hl2ctf', 'smg1', 'SMG', 'kills with the smg'),
       ('W', 'hl2ctf', 'ar2', 'Assault', 'kills with the assault rifle'),
       ('W', 'hl2ctf', 'crossbow_bolt', 'Sniper', 'snipings with crossbow'),
       ('W', 'hl2ctf', 'slam', 'SLAMMED!', 'kills with the slam'),
       ('W', 'hl2ctf', 'grenade_frag', 'Grenade Fiend', 'kills with nades'),
       ('W', 'hl2ctf', 'rpg_missile', 'Role Player', 'kills with RPG'),
       ('W', 'hl2ctf', 'latency', 'Best Latency', 'ms average connection'),
       ('O', 'dods', 'bomb_defuse', 'Top Defuser', 'bomb defusions'),
       ('O', 'dods', 'bomb_plant', 'Top Demolitionist', 'bomb plantings'),
       ('O', 'dods', 'capblock', 'Capture Blocked', 'flags blocked'),
       ('O', 'dods', 'captured_loc', 'Area Captured', 'flags captured'),
       ('O', 'dods', 'kill_planter', 'Bomb Planter Killer', 'kills'),
       ('W', 'dods', '30cal', '.30 Caliber Machine Gun', 'kills with .30 Caliber Machine Gun'),
       ('W', 'dods', 'amerknife', 'Backstabbing Beotch', 'kills with the American Knife'),
       ('W', 'dods', 'mp40', 'MP40 Hor', 'kills with the MP40 Machine Pistol'),
       ('W', 'dods', 'spade', 'Shovel God', 'kills with the spade'),
       ('W', 'dods', 'mp44', 'MP44 Hor', 'kills with the MP44 Assault Rifle'),
       ('W', 'dods', 'c96', 'Pistol c96', 'kills with Pistol c96'),
       ('W', 'dods', 'colt', 'Colt Freak', 'kills with the Colt .45 model 1911'),
       ('W', 'dods', 'garand', 'GarandMeister', 'kills with the M1 Garand Rifle'),
       ('W', 'dods', 'k98', 'Mauser Kar 98k', 'kills with Mauser Kar 98k'),
       ('W', 'dods', 'k98_scoped', 'Mauser Karbiner k98 Sniper Rifle', 'kills with Mauser Karbiner k98 Sniper Rifle'),
       ('W', 'dods', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'dods', 'm1carbine', 'M1 Carbine', 'kills with M1 Carbine'),
       ('W', 'dods', 'p38', 'Pistol 38', 'kills with Pistol 38'),
       ('W', 'dods', 'riflegren_ger', 'German Rifle Grenade', 'kills with German Rifle Grenade'),
       ('W', 'dods', 'riflegren_us', 'M1 Garand Rifle', 'kills with M1 Garand Rifle'),
       ('W', 'dods', 'thompson', 'Thompson Hor', 'kills with the Thompson Submachine Gun'),
       ('W', 'dods', 'spring', 'Spring Sniper', 'snipings with the Springfield 03 Rifle'),
       ('W', 'dods', 'bar', 'Bar Browning Hor', 'kills with the BAR Browning Automatic Rifle'),
       ('W', 'dods', 'frag_us', 'McVeigh Alert', 'bombings with the U.S. Grenade'),
       ('W', 'dods', 'frag_ger', 'Grenade Freak', 'bombings with the German Grenade'),
       ('W', 'dods', 'bazooka', 'Bazooka Joe', 'kills with the Bazooka'),
       ('W', 'dods', 'pschreck', 'Panzerschreck Hans', 'kills with the Panzerschreck'),
       ('W', 'dods', 'punch', 'Puncher', 'knock-outs'),
       ('W', 'dods', 'mg42', 'German Machine Hor', 'kills with the MG42'),
       ('W', 'dods', 'smoke_us', 'U.S. Smoke Grenade', 'kills with the U.S. Smoke Grenade'),
       ('W', 'dods', 'smoke_ger', 'German Smoke Grenade', 'kills with the German Smoke Grenade'),
       ('W', 'insmod', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'insmod', 'weapon_makarov', 'Soviet Makarov Combat Pistol', 'kills with Soviet Makarov Combat Pistol'),
       ('W', 'insmod', 'weapon_m9', '9mm Beretta Pistol', 'kills with 9mm Beretta Pistol'),
       ('W', 'insmod', 'weapon_sks', 'Simonov SKS carbine', 'kills with Simonov SKS carbine'),
       ('W', 'insmod', 'world', 'RPG or Grenade', 'kills with RPG or Grenade'),
       ('W', 'insmod', 'weapon_m1014', 'M1014 Service Combat Shotgun', 'kills with M1014 Service Combat Shotgun'),
       ('W', 'insmod', 'weapon_toz', 'TOZ Rifle', 'kills with TOZ Rifle'),
       ('W', 'insmod', 'weapon_svd', 'Dragunov Sniper Rifle', 'kills with Dragunov Sniper Rifle'),
       ('W', 'insmod', 'weapon_rpk', 'RPK Ruchnoy Pulemyot Kalashnikova',
        'kills with RPK Ruchnoy Pulemyot Kalashnikova'),
       ('W', 'insmod', 'weapon_m249', 'M249 SAW (Squad Automatic Weapon)',
        'kills with M249 SAW (Squad Automatic Weapon)'),
       ('W', 'insmod', 'weapon_m16m203', 'M16 carbine M203 Grenade Launcher',
        'kills with M16 carbine M203 Grenade Launcher'),
       ('W', 'insmod', 'weapon_l42a1', 'Enfield L42A1 Military Sniper Rifle',
        'kills with Enfield L42A1 Military Sniper Rifle'),
       ('W', 'insmod', 'weapon_m4med', 'M4 Medium Range Rifle', 'kills with M4 Medium Range Rifle'),
       ('W', 'insmod', 'weapon_m4', 'M4 Carbine Rifle', 'kills with M4 Carbine Rifle'),
       ('W', 'insmod', 'weapon_m16a4', 'M16A4 Infantry Rifle', 'kills with M16A4 Infantry Rifle'),
       ('W', 'insmod', 'weapon_m14', 'Colt M14 Carbine', 'kills with Colt M14 Carbine'),
       ('W', 'insmod', 'weapon_fnfal', 'FN FAL Automatic Rifle', 'kills with FN FAL Automatic Rifle'),
       ('W', 'insmod', 'weapon_aks74u', 'AKS-74U Awtomat Kalaschnikowa Ukorochennyj', 'kills with AKS-74U'),
       ('W', 'insmod', 'weapon_ak47', 'AK-47 Awtomat Kalaschnikowa', 'kills with AK-47 Awtomat Kalaschnikowa'),
       ('W', 'ff', 'weapon_tranq', 'Drug Dealer', 'kills with tranq gun'),
       ('W', 'ff', 'weapon_supershotgun', 'Super Shots', 'kills with super shotgun'),
       ('W', 'ff', 'weapon_supernailgun', 'Super Nails', 'kills with super nailgun'),
       ('W', 'ff', 'weapon_spanner', 'Whack-A-Mole', 'kills with spanner'),
       ('W', 'ff', 'weapon_sniperrifle', 'Snipes-A-Holic', 'kills with sniper rifle'),
       ('W', 'ff', 'weapon_rpg', 'ROCKET MAN', 'kills with rpg'),
       ('W', 'ff', 'weapon_shotgun', 'N00b shotwhore', 'kills with normal shotgun'),
       ('W', 'ff', 'weapon_railgun', 'Pew pew laz0r beams', 'kills with railgun'),
       ('W', 'ff', 'weapon_pipelauncher', 'Bouncy pipe whore', 'kills with blues'),
       ('W', 'ff', 'weapon_medkit', 'Aids Monger', 'kills with aids'),
       ('W', 'ff', 'weapon_knife', 'My name is Skanky Butterpuss(e)', 'kills with knife'),
       ('W', 'ff', 'weapon_grenadelauncher', 'Click BOOM', 'kills with grellows'),
       ('W', 'ff', 'weapon_flamethrower', 'I like fire!', 'kills with flamethrower'),
       ('W', 'ff', 'weapon_autorifle', 'Gay Sniper', 'kills with AR'),
       ('W', 'ff', 'weapon_dispenser', 'Remote Control GOD', 'kills with dispenser'),
       ('W', 'ff', 'weapon_assaultcannon', 'Best Fatty Ever!', 'kills with ass cannon'),
       ('W', 'ff', 'SentryGun', 'Robocop', 'kills with SG'),
       ('W', 'ff', 'grenade_normal', 'Flying chicken!', 'kills with frag grenade'),
       ('W', 'ff', 'grenade_mirv', 'Look I can kill SGs!', 'kills with mirv grenade'),
       ('W', 'ff', 'grenade_emp', 'Wheres all my ammo!', 'kills with emp grenade'),
       ('W', 'ff', 'BOOM_HEADSHOT', 'Sharp Eye', 'headshots'),
       ('W', 'ff', 'DETPACK', 'Earthquake Machine', 'kills with detpack'),
       ('W', 'ff', 'backstab', 'Backstabber', 'backstab kills'),
       ('W', 'ff', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'hidden', 'fn2000', 'FN2000 Assault Rifle', 'kills with FN2000 Assault Rifle'),
       ('W', 'hidden', 'p90', 'FN P90 Sub Machine Gun', 'kills with FN P90 Sub Machine Gun'),
       ('W', 'hidden', 'shotgun', 'Remington 870 MCS Shotgun', 'kills with Remington 870 MCS Shotgun'),
       ('W', 'hidden', 'fn303', 'FN303 Less Lethal Launcher', 'kills with FN303 Less Lethal Launcher'),
       ('W', 'hidden', 'pistol', 'FN FiveSeven Pistol', 'kills with FN FiveSeven Pistol'),
       ('W', 'hidden', 'pistol2', 'FNP-9 Pistol', 'kills with FNP-9 Pistol'),
       ('W', 'hidden', 'knife', 'Kabar D2 Knife', 'kills with Kabar D2 Knife'),
       ('W', 'hidden', 'grenade_projectile', 'Pipe Bomb', 'kills with Pipe Bomb'),
       ('W', 'hidden', 'physics', 'Physics', 'kills with Physics'),
       ('W', 'hidden', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'zps', 'arms', 'Armed and Dangerous', 'kills with Zombie Arms'),
       ('W', 'zps', 'carrierarms', 'Carry on...', 'kills with Carrier Arms'),
       ('W', 'zps', 'ak47', 'AK-47', 'kills with AK-47'),
       ('W', 'zps', 'mp5', 'MP5', 'kills with MP5'),
       ('W', 'zps', 'revolver', 'Revolver', 'kills with Revolver'),
       ('W', 'zps', 'glock', 'Glock 17', 'kills with Glock 17'),
       ('W', 'zps', 'glock18c', 'Glock 18c', 'kills with Glock 18c'),
       ('W', 'zps', 'ppk', 'PPK', 'kills with PPK'),
       ('W', 'zps', 'usp', 'H & K USP', 'kills with H & K USP'),
       ('W', 'zps', '870', 'Rem. 870', 'kills with Rem. 870'),
       ('W', 'zps', 'supershorty', 'Super Shorty', 'kills with Super Shorty'),
       ('W', 'zps', 'grenade_frag', 'Grenade', 'kills with Grenades'),
       ('W', 'zps', 'sledgehammer', 'Sledgehammer', 'kills with Sledgehammer'),
       ('W', 'zps', 'crowbar', 'Hello, I''m Gordon Freeman', 'kills with Crowbar'),
       ('W', 'zps', 'chair', 'Sorry, I thought this was pro wrestling', 'kills with Chair'),
       ('W', 'zps', 'keyboard', 'Keyboard', 'kills with Keyboard'),
       ('W', 'zps', 'plank', 'Plank', 'kills with Plank'),
       ('W', 'zps', 'shovel', 'Grave Digger', 'kills with Shovel'),
       ('W', 'zps', 'golf', 'Fore!', 'kills with Golf Club'),
       ('W', 'zps', 'machete', 'Cuttin'' em Down', 'kills with Machete'),
       ('W', 'zps', 'fryingpan', 'Frying Pan', 'kills with Frying Pan'),
       ('W', 'zps', 'spanner', 'Wrench', 'kills with Wrench'),
       ('W', 'zps', 'axe', 'Axe', 'kills with Axe'),
       ('W', 'zps', 'tireiron', 'Tire Iron', 'kills with Tire Iron'),
       ('W', 'zps', 'hammer', 'Hammer', 'kills with Hammer'),
       ('W', 'zps', 'broom', 'Broom', 'kills with Broom'),
       ('W', 'zps', 'pot', 'Pot', 'kills with Pot'),
       ('W', 'zps', 'racket', 'Tennis Racket', 'kills with Tennis Racket'),
       ('W', 'zps', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'zps', 'bat_aluminum', 'Out of the park!', 'kills with Bat (Aluminum)'),
       ('W', 'zps', 'bat_wood', 'Corked', 'kills with Bat (Wood)'),
       ('W', 'zps', 'm4', 'M4', 'kills with M4'),
       ('W', 'zps', 'pipe', 'Piping hot', 'kills with Pipe'),
       ('W', 'zps', 'slam', 'IEDs', 'kills with IED'),
       ('O', 'zps', 'headshot', 'Headshot King', 'headshot kills'),
       ('W', 'aoc', 'Flamberge', 'Flamberge', 'kills with Flamberge'),
       ('W', 'aoc', 'Longsword', 'Longsword', 'kills with Longsword'),
       ('W', 'aoc', 'Glaive', 'Glaive', 'kills with Glaive'),
       ('W', 'aoc', 'Dual Daggers', 'Dual Daggers', 'kills with Dual Daggers'),
       ('W', 'aoc', 'Flamberge & Kite Shield', 'Flamberge & Kite Shield', 'kills with Flamberge & Kite Shield'),
       ('W', 'aoc', 'Shortsword', 'Shortsword', 'kills with Shortsword'),
       ('W', 'aoc', 'Warhammer', 'Warhammer', 'kills with Warhammer'),
       ('W', 'aoc', 'Mace', 'Mace', 'kills with Mace'),
       ('W', 'aoc', 'Mace & Buckler', 'Mace & Buckler', 'kills with Mace & Buckler'),
       ('W', 'aoc', 'Broadsword & Evil Shield', 'Mason Broadsword & Shield', 'kills with Mason Broadsword & Shield'),
       ('W', 'aoc', 'Crossbow', 'Crossbow', 'kills with Crossbow'),
       ('W', 'aoc', 'Longbow', 'Longbow', 'kills with Longbow'),
       ('W', 'aoc', 'Longsword & Kite Shield', 'Longsword & Kite Shield', 'kills with Longsword & Kite Shield'),
       ('W', 'aoc', 'Broadsword & Good Shield', 'Knights Broadsword & Shield',
        'kills with Knights Broadsword & Shield'),
       ('W', 'aoc', 'Hatchet', 'Hatchet', 'kills with Hatchet'),
       ('W', 'aoc', 'Double Axe', 'Battle Axe', 'kills with Battle Axe'),
       ('W', 'aoc', 'Flail & Evil Shield', 'Mason Flail & Shield', 'kills with Mason Flail & Shield'),
       ('W', 'aoc', 'Flail & Good Shield', 'Knights Flail & Shield', 'kills with Knights Flail & Shield'),
       ('W', 'aoc', 'Javelin', 'Javelin', 'kills with Javelin'),
       ('W', 'aoc', 'Spiked Mace', 'Spiked Mace', 'kills with Spiked Mace'),
       ('W', 'aoc', 'Spear & Buckler', 'Spear & Buckler', 'kills with Spear & Buckler'),
       ('W', 'aoc', 'Spiked Mace & Buckler', 'Spiked Mace & Buckler', 'kills with Spiked Mace & Buckler'),
       ('W', 'aoc', 'Dagger', 'Dagger', 'kills with Dagger'),
       ('W', 'aoc', 'Broadsword', 'Broadsword', 'kills with Broadsword'),
       ('W', 'aoc', 'Throwing Knife', 'Throwing Knife', 'kills with Throwing Knives'),
       ('W', 'aoc', 'Halberd', 'Halberd', 'kills with Halberd'),
       ('W', 'aoc', 'chivalry', 'Fire', 'kills with Fire'),
       ('W', 'aoc', 'Oil Pot', 'Oil Pot', 'kills with Oil Pot'),
       ('O', 'aoc', 'headshot', 'Headshot/Decapitation', 'Headshots and Decapitations'),
       ('W', 'aoc', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'aoc', 'Fists', 'Fists', 'kills with fists'),
       ('W', 'aoc', 'Throwing Axe', 'Throwing Axe', 'kills with throwing axes'),
       ('O', 'cstrike', 'headshot', 'Headshot King', 'headshots'),
       ('O', 'cstrike', 'Defused_The_Bomb', 'Top Defuser', 'bomb defusions'),
       ('O', 'cstrike', 'Planted_The_Bomb', 'Top Demolitionist', 'bomb plantings'),
       ('O', 'cstrike', 'Rescued_A_Hostage', 'Top Hostage Rescuer', 'hostages rescued'),
       ('O', 'cstrike', 'Assassinated_The_VIP', 'Top Assassin', 'assassinations'),
       ('W', 'cstrike', 'elite', 'Dual Berretta Elites', 'kills with elite'),
       ('W', 'cstrike', 'knife', 'Knife Maniac', 'knifings'),
       ('W', 'cstrike', 'awp', 'AWP', 'snipings with awp'),
       ('W', 'cstrike', 'p90', 'P90', 'kills with p90'),
       ('W', 'cstrike', 'deagle', 'Desert Eagle', 'kills with deagle'),
       ('W', 'cstrike', 'm3', 'Shotgun', 'kills with m3 shotgun'),
       ('W', 'cstrike', 'usp', 'USP Master', 'kills with usp'),
       ('W', 'cstrike', 'm4a1', 'Colt M4A1 Carbine', 'kills with m4a1'),
       ('W', 'cstrike', 'glock18', 'Glock', 'kills with glock18'),
       ('W', 'cstrike', 'ak47', 'AK47', 'kills with ak47'),
       ('W', 'cstrike', 'famas', 'Fusil Automatique', 'kills with famas'),
       ('W', 'cstrike', 'galil', 'Galil', 'kills with galil'),
       ('W', 'cstrike', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'cstrike', 'grenade', 'Grenadier', 'kills with grenade'),
       ('W', 'tfc', 'axe', 'Crowbar Maniac', 'murders with crowbar'),
       ('W', 'tfc', 'spanner', 'Evil Engie', 'bludgeonings with spanner'),
       ('W', 'tfc', 'rocket', 'Rocketeer', 'kills with rocket'),
       ('W', 'tfc', 'ac', 'HWGuy Extraordinaire', 'ownings with ac'),
       ('W', 'tfc', 'sniperrifle', 'Red Dot Special', 'snipings'),
       ('W', 'tfc', 'flames', 'Fire Man', 'roastings'),
       ('W', 'tfc', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'dod', 'amerknife', 'Backstabbing Beotch', 'kills with the American Knife'),
       ('W', 'dod', 'luger', 'Luger Freak', 'kills with the Luger 08 Pistol'),
       ('W', 'dod', 'kar', 'KarMeister', 'kills with the Mauser Kar 98k'),
       ('W', 'dod', 'mp40', 'MP40 Hor', 'kills with the MP40 Machine Pistol'),
       ('W', 'dod', 'spade', 'Shovel God', 'kills with the spade'),
       ('W', 'dod', 'mp44', 'MP44 Hor', 'kills with the MP44 Assault Rifle'),
       ('W', 'dod', 'colt', 'Colt Freak', 'kills with the Colt .45 model 1911'),
       ('W', 'dod', 'garand', 'GarandMeister', 'kills with the M1 Garand Rifle'),
       ('W', 'dod', 'thompson', 'Thompson Hor', 'kills with the Thompson Submachine Gun'),
       ('W', 'dod', 'spring', 'Spring Sniper', 'snipings with the Springfield 03 Rifle'),
       ('W', 'dod', 'bar', 'Bar Browning Hor', 'kills with the BAR Browning Automatic Rifle'),
       ('W', 'dod', 'grenade', 'McVeigh Alert', 'bombings with the Grenade'),
       ('W', 'dod', 'garandbutt', 'Headsmasher', 'kills with Garand Butt Stock'),
       ('W', 'dod', 'bazooka', 'Bazooka Joe', 'kills with the Bazooka'),
       ('W', 'dod', 'pschreck', 'Panzerschreck Hans', 'kills with the Panzerschreck'),
       ('W', 'dod', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'ns', 'slash', 'Vicious Kitty', 'killings by le Swipe'),
       ('W', 'ns', 'shotgun', 'Buckshot Masta', 'killings with the shotty'),
       ('W', 'ns', 'pistol', 'Harold Handgun Alert', 'asskickings by pistola'),
       ('W', 'ns', 'knife', 'Iron Chef Alert', 'vicious stabbings'),
       ('W', 'ns', 'grenade', 'absolute n00b', 'pathetic killings by n00b grenades'),
       ('W', 'ns', 'bitegun', 'Teething Tommy', 'killings with le jaw'),
       ('W', 'ns', 'bite2gun', 'Mouth Full', 'killings with le big jaw'),
       ('W', 'ns', 'leap', 'Tigger Alert', 'crushings by leap'),
       ('W', 'ns', 'divinewind', 'Silent but Violent', 'slayings by recal relief'),
       ('W', 'ns', 'sporegunprojectile', 'Left Feet Larry', 'killings with Lerk'),
       ('W', 'ns', 'devour', 'Hungry Hungry Hippo', 'killings by Ingestion'),
       ('W', 'ns', 'spitgunspit', 'Masta Fatty', 'Marines too dumb to kill a gorge'),
       ('W', 'ns', 'latency', 'Best Latency', 'ms average connection'),
       ('O', 'l4d', 'headshot', 'Brain Salad', 'headshot kills'),
       ('O', 'l4d', 'healed_teammate', 'Field Medic', 'healed Survivors'),
       ('O', 'l4d', 'killed_exploding', 'Stomach Upset', 'killed Boomers'),
       ('O', 'l4d', 'killed_gas', 'No Smoking Section', 'killed Smokers'),
       ('O', 'l4d', 'killed_hunter', 'Hunter Punter', 'killed Hunters'),
       ('P', 'l4d', 'killed_survivor', 'Dead Wreckening', 'downed Survivors'),
       ('O', 'l4d', 'killed_tank', 'Tankbuster', 'killed Tanks'),
       ('O', 'l4d', 'killed_witch', 'Inquisitor', 'killed Witches'),
       ('P', 'l4d', 'pounce', 'Free to Fly', 'pounced Survivors'),
       ('O', 'l4d', 'rescued_survivor', 'Ground Cover', 'rescued Survivors'),
       ('O', 'l4d', 'revived_teammate', 'Helping Hand', 'revived Survivors'),
       ('P', 'l4d', 'tongue_grab', 'Drag &amp; Drop', 'constricted Survivors'),
       ('P', 'l4d', 'vomit', 'Barf Bagged', 'vomited on Survivors'),
       ('W', 'l4d', 'autoshotgun', 'Automation', 'kills with Auto Shotgun'),
       ('W', 'l4d', 'boomer_claw', 'Boom!', 'kills with Boomer''s Claws'),
       ('W', 'l4d', 'dual_pistols', 'Akimbo Assassin', 'kills with Dual Pistols'),
       ('W', 'l4d', 'hunter_claw', 'Open Season', 'kills with Hunter''s Claws'),
       ('W', 'l4d', 'hunting_rifle', 'Hawk Eye', 'kills with Hunting Rifle'),
       ('W', 'l4d', 'inferno', 'Pyromaniac', 'cremated Infected'),
       ('W', 'l4d', 'pipe_bomb', 'Pyrotechnician', 'blown up Infected'),
       ('W', 'l4d', 'pistol', 'Ammo Saver', 'kills with Pistol'),
       ('W', 'l4d', 'prop_minigun', 'No-One Left Behind', 'kills with Mounted Machine Gun'),
       ('W', 'l4d', 'pumpshotgun', 'Pump It!', 'kills with Pump Shotgun'),
       ('W', 'l4d', 'rifle', 'Commando', 'kills with M16 Assault Rifle'),
       ('W', 'l4d', 'smg', 'Safety First', 'kills with Uzi'),
       ('W', 'l4d', 'smoker_claw', 'Chain Smoker', 'kills with Smoker''s Claws'),
       ('W', 'l4d', 'tank_claw', 'Burger Tank', 'kills with Tank''s Claws'),
       ('W', 'l4d', 'tank_rock', 'Rock Star', 'kills with Tank''s Rock'),
       ('O', 'l4d', 'hunter_punter', 'Hunter Punter', 'hunter punts'),
       ('O', 'l4d', 'protect_teammate', 'Protector', 'teammate protections'),
       ('W', 'l4d', 'latency', 'Lowest Ping', 'ms average connection'),
       ('O', 'l4d2', 'headshot', 'Brain Salad', 'headshot kills'),
       ('O', 'l4d2', 'killed_boomer', 'Stomach Upset', 'killed Boomers'),
       ('O', 'l4d2', 'killed_smoker', 'No Smoking Section', 'killed Smokers'),
       ('O', 'l4d2', 'killed_hunter', 'Hunter Punter', 'killed Hunters'),
       ('O', 'l4d2', 'killed_spitter', 'Spittle Splatter', 'Spitters Splated'),
       ('O', 'l4d2', 'killed_charger', 'Bumrush Thwarter', 'killed Chargers'),
       ('O', 'l4d2', 'killed_jockey', 'Hunter Punter', 'killed Jockeys'),
       ('P', 'l4d2', 'killed_survivor', 'Dead Wreckening', 'downed Survivors'),
       ('O', 'l4d2', 'killed_tank', 'Tankbuster', 'killed Tanks'),
       ('O', 'l4d2', 'killed_witch', 'Inquisitor', 'killed Witches'),
       ('P', 'l4d2', 'tongue_grab', 'Drag &amp; Drop', 'constricted Survivors'),
       ('O', 'l4d2', 'healed_teammate', 'Field Medic', 'healed Survivors'),
       ('P', 'l4d2', 'pounce', 'Free to Fly', 'pounced Survivors'),
       ('O', 'l4d2', 'rescued_survivor', 'Ground Cover', 'rescued Survivors'),
       ('O', 'l4d2', 'revived_teammate', 'Helping Hand', 'revived Survivors'),
       ('P', 'l4d2', 'vomit', 'Barf Bagged', 'vomited on Survivors'),
       ('W', 'l4d2', 'autoshotgun', 'Automation', 'kills with Auto Shotgun'),
       ('W', 'l4d2', 'boomer_claw', 'Boom!', 'kills with Boomer''s Claws'),
       ('W', 'l4d2', 'dual_pistols', 'Akimbo Assassin', 'kills with Dual Pistols'),
       ('W', 'l4d2', 'hunter_claw', 'Open Season', 'kills with Hunter''s Claws'),
       ('W', 'l4d2', 'hunting_rifle', 'Hawk Eye', 'kills with Hunting Rifle'),
       ('W', 'l4d2', 'inferno', 'Pyromaniac', 'cremated Infected'),
       ('W', 'l4d2', 'pipe_bomb', 'Pyrotechnician', 'blown up Infected'),
       ('W', 'l4d2', 'pistol', 'Ammo Saver', 'kills with Pistol'),
       ('W', 'l4d2', 'prop_minigun', 'No One Left Behind', 'kills with Mounted Machine Gun'),
       ('W', 'l4d2', 'pumpshotgun', 'Pump It!', 'kills with Pump Shotgun'),
       ('W', 'l4d2', 'rifle', 'Commando', 'kills with M16 Assault Rifle'),
       ('W', 'l4d2', 'smg', 'Safety First', 'kills with Uzi'),
       ('W', 'l4d2', 'smoker_claw', 'Chain Smoker', 'kills with Smoker''s Claws'),
       ('W', 'l4d2', 'tank_claw', 'Burger Tank', 'kills with Tank''s Claws'),
       ('W', 'l4d2', 'tank_rock', 'Rock Star', 'kills with Tank''s Rock'),
       ('O', 'l4d2', 'hunter_punter', 'Hunter Punter', 'hunter punts'),
       ('O', 'l4d2', 'protect_teammate', 'Protector', 'hunter punts'),
       ('W', 'l4d2', 'latency', 'Lowest Ping', 'ms average connection'),
       ('O', 'l4d2', 'defibrillated_teammate', 'Dr. Shocker', 'teammates defibrillated'),
       ('O', 'l4d2', 'used_adrenaline', 'Adrenaline Junkie', 'adrenaline shots used'),
       ('O', 'l4d2', 'jockey_ride', 'Going for a ride!', 'jockey rides'),
       ('O', 'l4d2', 'charger_pummel', 'Hulk Smash!', 'pummelings as a charger'),
       ('O', 'l4d2', 'bilebomb_tank', 'Green can''t be healthy..', 'tank bilebombs'),
       ('O', 'l4d2', 'spitter_acidbath', 'Spit shine', 'spitter acid attacks'),
       ('W', 'l4d2', 'jockey_claw', 'Little Man Claws', 'kills with Jockey''s Claws'),
       ('W', 'l4d2', 'spitter_claw', 'Those nails could kill', 'kills with Spitter''s Claws'),
       ('W', 'l4d2', 'charger_claw', 'TAAN... What is this?!', 'kills with Charger''s Claws'),
       ('W', 'l4d2', 'first_aid_kit', 'Hi Dr. Nick!', 'kills with a First Aid Kit'),
       ('W', 'l4d2', 'grenade_launcher_projectile', 'Black Scottish Psyclops', 'kills with the Grenade Launcher'),
       ('W', 'l4d2', 'chainsaw', 'Slice and Dice', 'kills with the Chainsaw'),
       ('W', 'l4d2', 'fire_cracker_blast', 'Snap Crackle Pop', 'kills with fire crackers'),
       ('W', 'l4d2', 'pistol_magnum', 'Magnum', 'kills with the Magnum'),
       ('W', 'l4d2', 'rifle_ak47', 'AK-47', 'kills with the AK-47'),
       ('W', 'l4d2', 'rifle_desert', 'Combat Rifle', 'kills with the Combat Rifle'),
       ('W', 'l4d2', 'shotgun_chrome', 'Chrome Shotgun', 'kills with the Chrome Shotgun'),
       ('W', 'l4d2', 'shotgun_spas', 'Combat Shotgun', 'kills with the Combat Shotgun'),
       ('W', 'l4d2', 'smg_silenced', 'Uzi (Silenced)', 'kills with the Uzi (silenced)'),
       ('W', 'l4d2', 'sniper_military', 'Sniper Rifle', 'kills with the Sniper Rifle'),
       ('W', 'l4d2', 'baseball_bat', 'Batter Up!', 'kills with the Baseball Bat'),
       ('W', 'l4d2', 'cricket_bat', 'Cheerio.', 'kills with the Cricket Bat'),
       ('W', 'l4d2', 'crowbar', 'Crowbar', 'kills with the Crowbar'),
       ('W', 'l4d2', 'electric_guitar', 'Wayne''s world party on!', 'kills with the Electric Guitar'),
       ('W', 'l4d2', 'fireaxe', 'Fight fire with an axe', 'kills with the Fireaxe'),
       ('W', 'l4d2', 'frying_pan', 'BANG Headshot.', 'kills with the Frying Pan'),
       ('W', 'l4d2', 'katana', 'Katana', 'kills with the Katana'),
       ('W', 'l4d2', 'knife', 'Knife', 'kills with the Knife'),
       ('W', 'l4d2', 'machete', 'Machete', 'kills with the Machete'),
       ('W', 'l4d2', 'tonfa', 'Tonfa', 'kills with the Tonfa'),
       ('W', 'l4d2', 'melee', 'Fists of RAGGEE', 'melee kills'),
       ('W', 'l4d2', 'sniper_awp', 'AWP', 'kills with awp'),
       ('W', 'l4d2', 'smg_mp5', 'MP5 Navy', 'kills with mp5'),
       ('W', 'l4d2', 'sniper_scout', 'Scout Elite', 'kills with scout'),
       ('W', 'l4d2', 'rifle_sg552', 'SG 552', 'kills with sg552'),
       ('W', 'l4d2', 'gnome', 'GET OFF MY LAWN', 'gnome smash kills'),
       ('W', 'l4d2', 'golfclub', 'Golf Club', 'kills with the Golf Club'),
       ('W', 'l4d2', 'rifle_m60', 'M60', 'kills with M60'),
       ('W', 'fof', 'deringer', 'Deringer', 'kills with Deringer'),
       ('W', 'fof', 'carbine', 'Carbine', 'kills with Carbine'),
       ('W', 'fof', 'coltnavy', 'Colt Navy', 'kills with Colt Navy'),
       ('W', 'fof', 'bow', 'Bow', 'kills with Bow'),
       ('W', 'fof', 'arrow', 'Arrow', 'kills with Arrow'),
       ('W', 'fof', 'sharps', 'Sharps', 'kills with Sharps'),
       ('W', 'fof', 'coachgun', 'Coach Gun', 'kills with Coach Gun'),
       ('W', 'fof', 'peacemaker', 'Peacemaker', 'kills with Peacemaker'),
       ('W', 'fof', 'knife', 'Knife', 'kills with Knife'),
       ('W', 'fof', 'thrown_axe', 'Thrown Axe', 'kills with Thrown Axe'),
       ('W', 'fof', 'arrow_fiery', 'Fire Arrow', 'kills with Fire Arrow'),
       ('W', 'fof', 'thrown_knife', 'Thrown Knife', 'kills with Thrown Knife'),
       ('W', 'fof', 'dualnavy', 'Dual Colt Navys', 'kills with Dual Colt Navys'),
       ('W', 'fof', 'dynamite', 'Dynamite', 'kills with Dynamite'),
       ('W', 'fof', 'fists', 'Fists', 'kills with Fists'),
       ('W', 'fof', 'axe', 'Axe', 'kills with Axe'),
       ('W', 'fof', 'dualpeacemaker', 'Dual Peacemakers', 'kills with Dual Peacemakers'),
       ('W', 'fof', 'henryrifle', 'Henry Rifle', 'kills with Henry Rifle'),
       ('W', 'fof', 'shotgun', 'Winchester Shotgun', 'kills with the Winchester'),
       ('O', 'fof', 'loot_drop', 'Butter Fingers', 'Loot Drops'),
       ('O', 'fof', 'loot_capture', 'Gimme all yo loot', 'Loot Captures'),
       ('O', 'fof', 'carrier_protect', 'Grand Protector', 'carrier protections'),
       ('O', 'fof', 'headshot', 'BOOM HEADSHOT', 'headshot kills'),
       ('W', 'fof', 'latency', 'Lowest Ping', 'ms average connection'),
       ('W', 'ges', '#GE_ProximityMine', 'Proximity Pulvarizer', 'kills with Proximity Mines'),
       ('W', 'ges', '#GE_AutoShotgun', 'Automatic Shotgun', 'kills with Automatic Shotgun'),
       ('W', 'ges', '#GE_Phantom', 'Phantastic Phantom', 'kills with Phantom'),
       ('W', 'ges', '#GE_Knife', 'Silent Assassin', 'kills with Hunting Knife'),
       ('W', 'ges', '#GE_D5K', 'D5K', 'kills with D5K Deutsche'),
       ('W', 'ges', '#GE_SilverPP7', 'Silver PP7', 'kills with Silver PP7'),
       ('W', 'ges', '#GE_DD44', 'DD44', 'kills with DD44'),
       ('W', 'ges', '#GE_Grenade', 'Grenade', 'kills with Grenades'),
       ('W', 'ges', '#GE_CougarMagnum', 'Cougar Magnum', 'kills with Cougar Magnum'),
       ('W', 'ges', '#GE_D5K_SILENCED', 'Silenced D5K', 'kills with D5K (Silenced)'),
       ('W', 'ges', '#GE_Shotgun', 'Shotgun', 'kills with Shotgun'),
       ('W', 'ges', '#GE_Klobb', 'Klobbering Time', 'kills with Klobb'),
       ('W', 'ges', '#GE_RCP90', 'RCP 4 Death', 'kills with RC-P90'),
       ('W', 'ges', '#GE_RemoteMine', 'Remotely Remove', 'kills with Remote Mines'),
       ('W', 'ges', '#GE_KF7Soviet', 'KF7 Soviet', 'kills with KF7 Soviet'),
       ('W', 'ges', '#GE_ZMG', 'ZMG', 'kills with ZMG'),
       ('W', 'ges', '#GE_SniperRifle', 'A View To A Kill', 'kills with Sniper Rifle'),
       ('W', 'ges', '#GE_GoldPP7', 'Golden PP7', 'kills with Golden PP7'),
       ('W', 'ges', '#GE_AR33', 'ARYOU33?', 'kills with US AR33 Assault'),
       ('W', 'ges', '#GE_GoldenGun', 'Unknown Pain', 'kills with Golden Gun'),
       ('W', 'ges', '#GE_ThrowingKnife', 'Thorwing Knives', 'kills with Throwing Knives'),
       ('W', 'ges', '#GE_PP7', 'PKing Soup', 'kills with PP7'),
       ('W', 'ges', '#GE_PP7_SILENCED', 'Silenced PP7', 'kills with PP7 (Silenced)'),
       ('W', 'ges', '#GE_TimedMine', 'Timed Termination', 'kills with Timed Mines'),
       ('W', 'ges', '#GE_MilitaryLaser', 'Military Laser', 'kills with Military Laser'),
       ('W', 'ges', '#GE_GrenadeLauncher', 'Grenade Launcher', 'kills with Grenade Launcher'),
       ('W', 'ges', '#GE_Rocket', 'Rocket Launcher', 'kills with Rocket Launcher'),
       ('W', 'ges', '#GE_Taser', 'Taser', 'kills with Taser'),
       ('W', 'ges', '#GE_SniperButt', 'Sniper Butt', 'kills with Sniper Butt'),
       ('W', 'ges', '#GE_Slapper', 'Bitch Fighter', 'kills with Slappers'),
       ('W', 'ges', '#GE_RocketLauncher', ', Rocket Launcher', 'kills with Rocket Launcher'),
       ('W', 'ges', 'latency', 'Lowest Ping', 'ms average connection'),
       ('W', 'ges', 'mostkills', 'Bond, James Bond', 'kills'),
       ('W', 'bg2', 'brownbess', 'Brown Bess', 'kills with Brown Bess'),
       ('W', 'bg2', 'brownbess_bayonet', 'Brown Bess - Bayonet', 'kills with Brown Bess Bayonet'),
       ('W', 'bg2', 'charleville', 'Charleville', 'kills with Charleville'),
       ('W', 'bg2', 'charleville_bayonet', 'Charleville - Bayonet', 'kills with Charleville Bayonet'),
       ('W', 'bg2', 'hirschf', 'Hirschfaenger', 'kills with Hirschfaenger'),
       ('W', 'bg2', 'jaeger', 'Jaeger Rifle', 'kills with Jaeger Rifle'),
       ('W', 'bg2', 'knife', 'Knife', 'kills with Knife'),
       ('W', 'bg2', 'pennsylvania', 'Pennsylvania', 'kills with Pennsylvania'),
       ('W', 'bg2', 'pistol_a', 'British Pistol', 'kills with British Pistol'),
       ('W', 'bg2', 'pistol_b', 'American Pistol', 'kills with American Pistol'),
       ('W', 'bg2', 'sabre_a', 'British Sabre', 'kills with British Sabre'),
       ('W', 'bg2', 'sabre_b', 'American Sabre', 'kills with American Sabre'),
       ('W', 'bg2', 'mostkills', 'Most Kills', 'kills'),
       ('W', 'bg2', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'sgtls', 'mostkills', 'Most Kills', 'kills'),
       ('W', 'sgtls', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'sgtls', 'p90', 'FN Herstal P-90 Red Dot / FN-H P-90RD', 'kills'),
       ('W', 'sgtls', 'pistol', 'Beretta M92F-s', 'kills'),
       ('W', 'sgtls', 'knife', 'Combat Knife', 'kills'),
       ('W', 'sgtls', 'staff_blast', 'Staff Weapon', 'kills'),
       ('W', 'sgtls', 'p90D', 'FN Herstal P-90 w/ Disruptor', 'kills'),
       ('W', 'sgtls', 'hdevice', 'Hand Device / Ribbon Device', 'kills'),
       ('W', 'sgtls', 'tac_pulse', 'Tac (turrent)', 'kills'),
       ('W', 'sgtls', 'tac_projectile', 'Tac (bomb)', 'kills'),
       ('W', 'sgtls', 'c4_charge', 'C4', 'kills'),
       ('W', 'sgtls', 'grenade_projectile', 'M67 Frag Grenade', 'kills'),
       ('W', 'sgtls', 'g36', 'H&K G-36', 'kills'),
       ('W', 'sgtls', 'kull_blast', 'Kull Warrior Staff Device', 'kills'),
       ('W', 'sgtls', 'suicide_bomb', 'Goa''uld Suicide Bomb', 'kills'),
       ('W', 'sgtls', 'kullblaster', 'Kull Warrior Staff Device (blast)', 'kills'),
       ('W', 'sgtls', 'staff', 'Staff Weapon Melee', 'kills'),
       ('W', 'sgtls', 'zat_blast', 'Zat', 'kills'),
       ('W', 'sgtls', 'awp', 'AWP Rifle', 'kills'),
       ('W', 'sgtls', 'grenade', 'M67 Frag Grenade', 'kills'),
       ('W', 'sgtls', 'zat', 'Zat (splash)', 'kills'),
       ('W', 'sgtls', 'tac', 'Tac (splash)', 'kills'),
       ('O', 'dystopia', 'Capture Guard Post', 'Capture Guard Post', 'captures'),
       ('O', 'dystopia', 'Capture Interior Spawn', 'Capture Interior Spawn', 'captures'),
       ('O', 'dystopia', 'Capture Internal Spawn', 'Capture Internal Spawn', 'captures'),
       ('O', 'dystopia', 'Capture The Docks', 'Capture The Docks', 'captures'),
       ('O', 'dystopia', 'Capture the Inner Base', 'Capture the Inner Base', 'captures'),
       ('O', 'dystopia', 'Capture the Spawn', 'Capture the Spawn', 'captures'),
       ('O', 'dystopia', 'Cut Entrance Spawn Power', 'Cut Entrance Spawn Power', 'power cuts'),
       ('O', 'dystopia', 'Defend Interior Spawn', 'Defend Interior Spawn', 'defenses'),
       ('O', 'dystopia', 'Defend Middle Spawn', 'Defend Middle Spawn', 'defenses'),
       ('O', 'dystopia', 'Defend Security JIP', 'Defend Security JIP', 'defenses'),
       ('O', 'dystopia', 'Destroy Broadcast Server', 'Destroy Broadcast Server', 'destructions'),
       ('O', 'dystopia', 'Destroy Cooling Access Door', 'Destroy Cooling Access Door', 'destructions'),
       ('O', 'dystopia', 'Destroy Cooling Tank', 'Destroy Cooling Tank', 'destructions'),
       ('O', 'dystopia', 'Destroy The Bulkhead', 'Destroy The Bulkhead', 'destructions'),
       ('O', 'dystopia', 'Destroy The Core', 'Destroy The Core', 'destructions'),
       ('O', 'dystopia', 'Destroy the Firewall', 'Destroy the Firewall', 'destructions'),
       ('O', 'dystopia', 'Destroy the Reactor', 'Destroy the Reactor', 'destructions'),
       ('O', 'dystopia', 'Destroy Transformer', 'Destroy Transformer', 'destructions'),
       ('O', 'dystopia', 'Enable Auxilary Power Feed', 'Enable Auxilary Power Feed', 'power feed enablings'),
       ('O', 'dystopia', 'Enable The 4-Point Override', 'Enable The 4-Point Override', '4-point override enablings'),
       ('O', 'dystopia', 'Escort Hostage', 'Escort Hostage', 'escorts'),
       ('O', 'dystopia', 'Hack Middle Spawn', 'Hack Middle Spawn', 'hacks'),
       ('O', 'dystopia', 'Hack Spawn Controls', 'Hack Spawn Controls', 'hacks'),
       ('O', 'dystopia', 'Hack the Perimeter', 'Hack the Perimeter', 'hacks'),
       ('O', 'dystopia', 'Inject The Virus', 'Inject The Virus', 'injections'),
       ('O', 'dystopia', 'Launch Missile', 'Launch Missile', 'launches'),
       ('O', 'dystopia', 'Locate profile', 'Locate profile', 'locations'),
       ('O', 'dystopia', 'Maintain Power Routing', 'Maintain Power Routing', 'maintenances'),
       ('O', 'dystopia', 'Open And Destroy Data Stores / Establish An Uplink',
        'Open And Destroy Data Stores / Establish An Uplink', 'times'),
       ('O', 'dystopia', 'Redirect Laser', 'Redirect Laser', 'redirections'),
       ('O', 'dystopia', 'Reroute Power To Control Room', 'Reroute Power To Control Room', 'reroutings'),
       ('O', 'dystopia', 'Shut Down Security', 'Shut Down Security', 'shutdowns'),
       ('O', 'dystopia', 'Shutdown The Production Line', 'hutdown The Production Line', 'shutdowns'),
       ('O', 'dystopia', 'Smash Data Storage', 'Smash Data Storage', 'smashings'),
       ('O', 'dystopia', 'Turn Power Offline', 'Turn Power Offline', 'times'),
       ('W', 'dystopia', 'bonuspoints', 'Most Bonus Points', 'bonus points'),
       ('W', 'dystopia', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'dystopia', 'Light Katana', 'Light Katana', 'kills'),
       ('W', 'dystopia', 'Medium Katana', 'Medium Katana', 'kills'),
       ('W', 'dystopia', 'Fatman Fist', 'Fatman Fist', 'kills'),
       ('W', 'dystopia', 'Machine Pistol', 'Machine Pistol', 'kills'),
       ('W', 'dystopia', 'Shotgun', 'Shotgun', 'kills'),
       ('W', 'dystopia', 'Laser Rifle', 'Laser Rifle', 'kills'),
       ('W', 'dystopia', 'BoltGun', 'Bolt Gun', 'kills'),
       ('W', 'dystopia', 'SmartLock Pistols', 'Smartlock Pistols', 'kills'),
       ('W', 'dystopia', 'Assault Rifle', 'Assault Rifle', 'kills'),
       ('W', 'dystopia', 'Grenade Launcher', 'Grenade Launcher', 'kills'),
       ('W', 'dystopia', 'MK-808 Rifle', 'MK-808 Rifle', 'kills'),
       ('W', 'dystopia', 'Tesla Rifle', 'Tesla Rifle', 'kills'),
       ('W', 'dystopia', 'Rocket Launcher', 'Rocket Launcher', 'kills'),
       ('W', 'dystopia', 'Minigun', 'Minigun', 'kills'),
       ('W', 'dystopia', 'Ion Cannon', 'Ion Cannon', 'kills'),
       ('W', 'dystopia', 'Basilisk', 'Basilisk', 'kills'),
       ('W', 'dystopia', 'Frag Grenade', 'Frag Grenade', 'kills'),
       ('W', 'dystopia', 'EMP Grenade', 'EMP Grenade', 'kills'),
       ('W', 'dystopia', 'Spider Grenade', 'Spider Grenade', 'kills'),
       ('W', 'dystopia', 'Cortex Bomb', 'Cortex Bomb', 'kills'),
       ('W', 'dystopia', 'Leg Boosters', 'Leg Boosters', 'kills'),
       ('W', 'dystopia', 'Trap', 'Trap', 'kills'),
       ('W', 'dystopia', 'Turret', 'Turret', 'kills'),
       ('O', 'nts', 'headshot', 'Headshot King', 'headshot kills'),
       ('W', 'nts', 'aa13', 'AA13', 'kills with AA13'),
       ('W', 'nts', 'grenade_projectile', 'Frag Grenade', 'kills with Frag Grenade'),
       ('W', 'nts', 'jitte', 'Jitte', 'kills with Jitte'),
       ('W', 'nts', 'jittescoped', 'Jitte (Scoped)', 'kills with Jitte (Scoped)'),
       ('W', 'nts', 'knife', 'Knife', 'kills with Knife'),
       ('W', 'nts', 'kyla', 'KYLA', 'kills with KYLA'),
       ('W', 'nts', 'm41', 'M41', 'kills with M41'),
       ('W', 'nts', 'm41s', 'M41S', 'kills with M41S'),
       ('W', 'nts', 'milso', 'MilSO', 'kills with MilSO'),
       ('W', 'nts', 'mpn', 'MPN45', 'kills with MPN45'),
       ('W', 'nts', 'mx', 'MX', 'kills with MX'),
       ('W', 'nts', 'mx_silenced', 'MX Silenced', 'kills with MX Silenced'),
       ('W', 'nts', 'pz', 'PZ252', 'kills with PZ252'),
       ('W', 'nts', 'grenade_detapack', 'Detpack', 'kills with Detpack'),
       ('W', 'nts', 'srm', 'SRM', 'kills with SRM'),
       ('W', 'nts', 'srm_s', 'SRM-S', 'kills with SRM-S'),
       ('W', 'nts', 'srs', 'SRS', 'kills with SRS'),
       ('W', 'nts', 'supa7', 'MURATA SUPA 7', 'kills with MURATA SUPA 7'),
       ('W', 'nts', 'tachi', 'TACHI', 'kills with TACHI'),
       ('W', 'nts', 'zr68c', 'ZR68C', 'kills with ZR68C'),
       ('W', 'nts', 'zr68l', 'ZR68L', 'kills with ZR68L'),
       ('W', 'nts', 'zr68s', 'ZR68S', 'kills with ZR68S'),
       ('W', 'nts', 'mostkills', 'Most Kills', 'kills'),
       ('W', 'nts', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'pvkii', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'pvkii', 'mostkills', 'Most Kills', 'kills'),
       ('W', 'pvkii', 'teamkills', 'Most Team Kills', 'team kills'),
       ('W', 'pvkii', 'bonuspoints', 'Most bonus points', 'bonus points'),
       ('W', 'pvkii', 'zerking', 'Zerking', 'kills with Zerking'),
       ('W', 'pvkii', 'slidingdoor', 'Sliding Door', 'kills with Sliding Door'),
       ('W', 'pvkii', 'seaxshield', 'Langseax & Shield', 'kills with Langseax & Shield'),
       ('W', 'pvkii', 'longbow', 'Long Bow', 'kills with Long Bow'),
       ('W', 'pvkii', 'chest', 'Chest', 'kills with Chest'),
       ('W', 'pvkii', 'parrot', 'Parrot', 'kills with Parrot'),
       ('W', 'pvkii', 'rocks', 'Rocks', 'kills with Rocks'),
       ('W', 'pvkii', 'bigaxe', 'Berserker Axe', 'kills with Berserker Axe'),
       ('W', 'pvkii', 'gatecrush', 'Gate Crush', 'kills with Gate Crush'),
       ('W', 'pvkii', 'cutlass', 'Cutlass', 'kills with Cutlass'),
       ('W', 'pvkii', 'twoaxe', 'Huscarl Axe', 'kills with Huscarl Axe'),
       ('W', 'pvkii', 'spear', 'Spear', 'kills with Spear'),
       ('W', 'pvkii', 'freeze', 'Freeze', 'kills with Freeze'),
       ('W', 'pvkii', 'plfall', 'Falling', 'kills with Falling'),
       ('W', 'pvkii', 'steam', 'Steam', 'kills with Steam'),
       ('W', 'pvkii', 'vulture', 'Vultures', 'kills with Vultures'),
       ('W', 'pvkii', 'shuriken', 'shuriken', 'kills with shuriken'),
       ('W', 'pvkii', 'huscshieldbash', 'Huscarl Shield Bash', 'kills with Huscarl Shield Bash'),
       ('W', 'pvkii', 'spike', 'Spike', 'kills with Spike'),
       ('W', 'pvkii', 'blunderbuss', 'Blunderbuss', 'kills with Blunderbuss'),
       ('W', 'pvkii', 'punch_cpt', 'Punch', 'kills with Punch'),
       ('W', 'pvkii', 'crossbow', 'Crossbow', 'kills with Crossbow'),
       ('W', 'pvkii', 'env_explosion', 'Explosion', 'kills with Explosion '),
       ('W', 'pvkii', 'flintlock', 'Flintlock Pistols', 'kills with Flintlock Pistols'),
       ('W', 'pvkii', 'throwaxe', 'Throwing Axes', 'kills with Throwing Axes'),
       ('W', 'pvkii', 'powderkeg', 'Powderkeg', 'kills with Powderkeg'),
       ('W', 'pvkii', 'physics', 'Physics', 'kills with Physics'),
       ('W', 'pvkii', 'boulder', 'Boulder', 'kills with Boulder'),
       ('W', 'pvkii', 'drowned', 'Drowned', 'kills with Drowned'),
       ('W', 'pvkii', 'barrel', 'Barrel', 'kills with Barrel'),
       ('W', 'pvkii', 'axesword', 'Sword & Axe', 'kills with Sword & Axe'),
       ('W', 'pvkii', 'cutlass2', 'Captain''s Cutlass', 'kills with Captain''s Cutlass'),
       ('W', 'pvkii', 'flames', 'Flames', 'kills with Flames'),
       ('W', 'pvkii', 'vikingshield', 'Huscarl Sword & Shield', 'kills with Huscarl Sword & Shield '),
       ('W', 'pvkii', 'thrownkeg', 'Thrown Powderkeg', 'kills with Thrown Powderkeg '),
       ('W', 'pvkii', 'archersword', 'Short Sword', 'kills with Short Sword'),
       ('W', 'pvkii', 'player', 'Player', 'kills with Player'),
       ('W', 'pvkii', 'worldspawn', 'World', 'kills with World'),
       ('W', 'pvkii', 'twosword', '2 Handed Sword', 'kills with 2 Handed Sword'),
       ('W', 'pvkii', 'hook', 'Hook', 'kills with Hook'),
       ('W', 'pvkii', 'hkshieldbash', 'Heavy Knight Bash', 'kills with Heavy Knight Bash'),
       ('W', 'pvkii', 'javelin', 'Javelins', 'kills with Javelins'),
       ('W', 'pvkii', 'swordshield', 'Heavy Knight Sword/Shield', 'kills with Heavy Knight Sword/Shield'),
       ('W', 'pvkii', 'crusher', 'Crusher', 'kills with Crusher'),
       ('O', 'pvkii', 'kill assist', 'Kill Assists', 'kill assists'),
       ('O', 'pvkii', 'mvp1', 'Most Valuable Player', 'times MVP'),
       ('O', 'pvkii', 'chest_capture', 'Chest Captures', 'chest captures'),
       ('O', 'pvkii', 'obj_complete', 'Completed Objectives', 'completed objectives'),
       ('O', 'pvkii', 'chest_defend', 'Chest Defends', 'chests defends'),
       ('O', 'pvkii', 'grail_defend', 'Grail Defends', 'grail defends'),
       ('O', 'pvkii', 'killed_parrot', 'Parrot Killer', 'parrots killed'),
       ('P', 'pvkii', 'domination', 'Dominations', 'dominations'),
       ('P', 'pvkii', 'revenge', 'Revenge', 'revenges'),
       ('W', 'csp', 'awp', 'AWP', 'kills with awp'),
       ('W', 'csp', 'galil', 'Galil', 'kills with galil'),
       ('W', 'csp', 'famas', 'Fusil Automatique', 'kills with famas'),
       ('W', 'csp', 'ak47', 'AK47', 'kills with ak47'),
       ('W', 'csp', 'glock', 'Glock', 'kills with glock'),
       ('W', 'csp', 'm4a1', 'Colt M4A1 Carbine', 'kills with m4a1'),
       ('W', 'csp', 'usp', 'USP Master', 'kills with usp'),
       ('W', 'csp', 'deagle', 'Desert Eagle', 'kills with deagle'),
       ('W', 'csp', 'knife', 'Knife Maniac', 'knifings'),
       ('W', 'csp', 'mp5navy', 'MP5 Navy', 'kills with mp5'),
       ('W', 'csp', 'hegrenade', 'Top grenadier', 'kills with grenade'),
       ('O', 'csp', 'headshot', 'Headshot King', 'shots in the head'),
       ('W', 'csp', 'latency', 'Best Latency', 'ms average connection'),
       ('W', 'csp', 'mostkills', 'Most Kills', 'kills'),
       ('W', 'csp', 'suicide', 'Suicides', 'suicides'),
       ('W', 'csp', 'teamkills', 'Team Killer', 'team kills'),
       ('W', 'valve', '357', '357', 'kills with 357'),
       ('W', 'valve', '9mmAR', 'MP5', 'kills with 9mmAR'),
       ('W', 'valve', '9mmhandgun', 'Glock', 'kills with 9mmhandgun'),
       ('W', 'valve', 'crossbow', 'Crossbow Sniper', 'kills with crossbow'),
       ('W', 'valve', 'crowbar', 'Crowbar Maniac', 'murders with crowbar'),
       ('W', 'valve', 'gluon gun', 'Gauss King', 'kills with gluon gun'),
       ('W', 'valve', 'tau_cannon', 'Egon', 'kills with tau_cannon'),
       ('W', 'valve', 'grenade', 'Grenadier', 'kills with grenade'),
       ('W', 'valve', 'hornet', 'Hornet Master', 'kills with hornet'),
       ('W', 'valve', 'rpg_rocket', 'Rocketeer', 'kills with rocket'),
       ('W', 'valve', 'satchel', 'Lord Satchel', 'kills with satchel'),
       ('W', 'valve', 'shotgun', 'Redneck', 'kills with shotgun'),
       ('W', 'valve', 'snark', 'Snark Master', 'kills with snark'),
       ('W', 'valve', 'tripmine', 'Shady Assassin', 'kills with tripmine'),
       ('O', 'valve', 'headshot', 'Headshot King', 'shots in the head'),
       ('W', 'valve', 'latency', 'Latency', 'ms average connection'),
       ('W', 'valve', 'mostkills', 'Most Kills', 'kills'),
       ('W', 'valve', 'suicide', 'Suicides', 'suicides'),
       ('W', 'csgo', 'ak47', 'AK47', 'kills with ak47'),
       ('W', 'csgo', 'AUG', 'Aug', 'kills with aug'),
       ('W', 'csgo', 'awp', 'AWP', 'kills with awp'),
       ('W', 'csgo', 'deagle', 'Desert Eagle', 'kills with deagle'),
       ('W', 'csgo', 'elite', 'Dual Berretta Elites', 'kills with elite'),
       ('W', 'csgo', 'famas', 'Fusil Automatique', 'kills with famas'),
       ('W', 'csgo', 'fiveseven', 'Five Seven', 'kills with fiveseven'),
       ('W', 'csgo', 'g3sg1', 'G3 SG1', 'kills with g3sg1'),
       ('W', 'csgo', 'galilar', 'Galil', 'kills with galil'),
       ('W', 'csgo', 'glock', 'Glock', 'kills with glock'),
       ('W', 'csgo', 'hegrenade', 'High Explosive Grenade', 'kills with grenade'),
       ('W', 'csgo', 'firebomb', 'Incendiary Grenade', 'kills with inferno'),
       ('W', 'csgo', 'knife', 'Knife Maniac', 'knifings'),
       ('W', 'csgo', 'm249', 'M249', 'kills with m249'),
       ('W', 'csgo', 'm4a1', 'M4A4', 'kills with m4a4'),
       ('W', 'csgo', 'mac10', 'MAC-10', 'kills with mac10'),
       ('W', 'csgo', 'mag7', 'MAG-7', 'kills with mag7'),
       ('O', 'csgo', 'headshot', 'Headshot King', 'shots in the head'),
       ('W', 'csgo', 'latency', 'Best Latency', 'ms average connection'),
       ('O', 'csgo', 'round_mvp', 'Most Valuable Player', 'times earning Round MVP'),
       ('W', 'csgo', 'mostkills', 'Most Kills', 'kills'),
       ('W', 'csgo', 'suicide', 'Suicides', 'suicides'),
       ('W', 'csgo', 'teamkills', 'Team Killer', 'team kills'),
       ('W', 'csgo', 'mp7', 'MP7', 'kills with mp7'),
       ('W', 'csgo', 'mp9', 'MP9', 'kills with mp9'),
       ('W', 'csgo', 'negev', 'Negev', 'kills with negev'),
       ('W', 'csgo', 'nova', 'Nova', 'kills with nova'),
       ('W', 'csgo', 'hkp2000', 'P2000', 'kills with p2000'),
       ('W', 'csgo', 'p250', 'P250', 'kills with p250'),
       ('W', 'csgo', 'p90', 'P90', 'kills with p90'),
       ('W', 'csgo', 'bizon', 'PP-Bizon', 'kills with pp-bizon'),
       ('W', 'csgo', 'sawedoff', 'Sawed-Off', 'kills with sawed-off'),
       ('W', 'csgo', 'scar20', 'SCAR-20', 'kills with scar-20'),
       ('W', 'csgo', 'sg553', 'SG 553', 'kills with sg553'),
       ('W', 'csgo', 'ssg08', 'SSG 08', 'kills with ssg08'),
       ('W', 'csgo', 'tec9', 'Tec-9', 'kills with Tec-9'),
       ('O', 'csgo', 'Defused_The_Bomb', 'Top Defuser', 'bomb defusions'),
       ('O', 'csgo', 'Planted_The_Bomb', 'Top Demolitionist', 'bomb plantings'),
       ('O', 'csgo', 'Killed_A_Hostage', 'Top Hostage Killer', 'hostages killed'),
       ('O', 'csgo', 'Rescued_A_Hostage', 'Top Hostage Rescuer', 'hostages rescued'),
       ('W', 'csgo', 'ump45', 'UMP-45', 'kills with ump45'),
       ('W', 'csgo', 'xm1014', 'XM automatic Shotgun', 'kills with xm1014'),
       ('W', 'csgo', 'taser', 'Zeus x27', 'kills with taser'),
       ('O', 'nd', 'headshot', 'Headshot King', 'shots in the head'),
       ('O', 'nd', 'structure_kill', 'Destroyer', 'destroyed structures'),
       ('O', 'nd', 'killed_commander', 'Commander Killer', 'enemy commander kills'),
       ('O', 'nd', 'promoted_to_commander', 'Master Commander', 'times commander'),
       ('O', 'nd', 'armoury_destroyed', 'Armoury Destroyer', 'destroyed armouries'),
       ('O', 'nd', 'artillery_destroyed', 'Armoury Destroyer', 'destroyed artilleries'),
       ('O', 'nd', 'assembler_destroyed', 'Armoury Destroyer', 'destroyed assemblers'),
       ('O', 'nd', 'flamethrowerturret_destroyed', 'Armoury Destroyer', 'destroyed flameghrower turrets'),
       ('O', 'nd', 'wirelessrepeater_destroyed', 'Armoury Destroyer', 'destroyed wireless repeaters'),
       ('O', 'nd', 'powerstation_destroyed', 'Armoury Destroyer', 'destroyed power stations'),
       ('O', 'nd', 'radar_destroyed', 'Armoury Destroyer', 'destroyed radars'),
       ('O', 'nd', 'powerrelay_destroyed', 'Armoury Destroyer', 'destroyed relay towers'),
       ('O', 'nd', 'rocketturret_destroyed', 'Armoury Destroyer', 'destroyed rocket turrets'),
       ('O', 'nd', 'sonicturret_destroyed', 'Armoury Destroyer', 'destroyed sonic turrets'),
       ('O', 'nd', 'supply_destroyed', 'Armoury Destroyer', 'destroyed supplies'),
       ('O', 'nd', 'transportgate_destroyed', 'Armoury Destroyer', 'destroyed transport gates'),
       ('O', 'nd', 'machineguneturret_destroyed', 'Armoury Destroyer', 'destroyed machinegun turrets'),
       ('W', 'nd', 'armblade', 'BLADES', 'kills with BLADES'),
       ('W', 'nd', 'armknives', 'KNIVES', 'kills with KNIVES'),
       ('W', 'nd', 'artillery', 'Artillerist', 'kills with Artillery'),
       ('W', 'nd', 'avenger', 'C1 AVENGER', 'kills with C1 AVENGER'),
       ('W', 'nd', 'bag90', 'BAG-90', 'kills with BAG-90'),
       ('W', 'nd', 'bonuspoints', 'Improved Player', 'bonus points'),
       ('W', 'nd', 'chaingun', 'GAU-20P', 'kills with GAU-20P'),
       ('W', 'nd', 'commander damage', 'Damage Commander', 'kills with Commander Damage Ability'),
       ('W', 'nd', 'commander poison', 'Poison Commander', 'kills with Commander Poison Ability'),
       ('W', 'nd', 'connectiontime', 'Play Time', 's in game'),
       ('W', 'nd', 'daisy cutter', 'DAISYCUTTER', 'kills with DAISYCUTTER'),
       ('W', 'nd', 'deathstreak', 'Victim', 'death streak'),
       ('W', 'nd', 'env_explosion', 'Blaster', 'kills with Environment Explosion'),
       ('W', 'nd', 'f2000', 'FN-H F2100 TR', 'kills with FN-H F2100 TR'),
       ('W', 'nd', 'flamethrower turret', 'Flamethrower Turret', 'kills with Flamethrower Turret'),
       ('W', 'nd', 'frag grenade', 'M-87 FRAG', 'kills with M-87 FRAG'),
       ('W', 'nd', 'grenade launcher', 'M52 HYDRA', 'kills with M52 HYDRA'),
       ('W', 'nd', 'killstreak', 'Slayer', 'kill streak'),
       ('W', 'nd', 'latency', 'Lowpinger', 'ms average connection'),
       ('W', 'nd', 'm95', 'M-95 L.A.W.S.', 'kills with M-95 L.A.W.S.'),
       ('W', 'nd', 'mg turret', 'Machine-gun Turret', 'kills with Machine-gun Turret'),
       ('W', 'nd', 'mostkills', 'Killer', 'kills'),
       ('W', 'nd', 'mp500', 'MP-500', 'kills with MP-500'),
       ('W', 'nd', 'mp7', 'MP-7', 'kills with MP-7'),
       ('W', 'nd', 'nx300', 'NX-300', 'kills with NX-300'),
       ('W', 'nd', 'p12 grenade', 'P12 POISON', 'kills with P12 POISON'),
       ('W', 'nd', 'p900', 'P-900', 'kills with P-900'),
       ('W', 'nd', 'paladin', 'PALADIN PLR-5', 'kills with PALADIN PLR-5'),
       ('W', 'nd', 'pp22', 'PP-22', 'kills with PP-22'),
       ('W', 'nd', 'psg', 'PSG-L', 'kills with PSG-L'),
       ('W', 'nd', 'R.E.D.', 'R.E.D.', 'kills with R.E.D.'),
       ('W', 'nd', 'repair tool', 'Engineer', 'kills with BLOWTORCH'),
       ('W', 'nd', 'rocket turret', 'Rocket Turret', 'kills with Rocket Turret'),
       ('W', 'nd', 'shotgun', 'SPETZ-9', 'kills with SPETZ-9'),
       ('W', 'nd', 'sonic turret', 'SONIC TURRET', 'kills with Sonic Turret'),
       ('W', 'nd', 'sp5', 'SP-5 K1', 'kills with SP-5 K1'),
       ('W', 'nd', 'suicide', 'Self-murderer', 'suicides'),
       ('W', 'nd', 'teamkills', 'Betrayer', 'team kills'),
       ('W', 'nd', 'u23 grenade', 'U23 POISON', 'kills with U23 POISON'),
       ('W', 'nd', 'x01', 'X-01', 'kills with X-01');