-- name: insert-into-hlstats-ClanTags

INSERT INTO hlstats_ClanTags (pattern, position)
VALUES ('[AXXXXX]', 'EITHER'),
       ('|AXXXXX|', 'EITHER'),
       ('(AXXXXX)', 'EITHER'),
       ('{AXXXXX}', 'EITHER'),
       ('-=AXXX=-', 'START'),
       ('=AXXXXX=', 'START'),
       ('-AXXXXX-', 'START'),
       ('=[AXXXX]=', 'START'),
       ('-=|AXXXXXX|=-', 'EITHER'),
       ('-=[AXXXXXX]=-', 'EITHER'),
       ('-=]AXXXXXX[=-', 'EITHER'),
       ('~{|AXXXXXX|}~', 'EITHER'),
       ('-|-AXXXXXX-|-', 'EITHER'),
       ('-(AXXXXXX)-', 'EITHER'),
       ('::AXXXXXX::', 'EITHER'),
       ('<<AXXXXXX>>', 'EITHER'),
       ('{{AXXXXXX}}', 'EITHER'),
       ('((AXXXXXX))', 'EITHER'),
       ('.|AXXXXXX|.', 'EITHER'),
       ('--AXXXXXX--', 'EITHER'),
       ('\AXXXXXX/', 'EITHER'),
       ('-)AXXXXXX(-', 'EITHER'),
       ('/AXXXXXX', 'EITHER'),
       ('//AXXXXXX', 'EITHER'),
       ('_AXXXXXX_', 'EITHER'),
       ('_=|AXXXXXX|=_', 'EITHER'),
       ('*AXXXXXX*', 'EITHER'),
       ('.:AXXXXXX:', 'START'),
       ('[(AXXXXXX)]', 'EITHER');
