-- name: insert-into-hlstats-Games

INSERT INTO hlstats_Games (code, name, realgame, hidden)
VALUES ('css', 'Counter-Strike: Source', 'css', '1'),
       ('hl2mp', 'Half-Life 2 Multiplayer', 'hl2mp', '1'),
       ('tf', 'Team Fortress 2', 'tf', '0'),
       ('hl2ctf', 'Half-Life 2 Capture the flag', 'hl2mp', '1'),
       ('dods', 'Day of Defeat: Source', 'dods', '1'),
       ('insmod', 'Insurgency: Modern Infantry Combat', 'insmod', '1'),
       ('ff', 'Fortress Forever', 'ff', '1'),
       ('hidden', 'The Hidden: Source', 'hidden', '1'),
       ('zps', 'Zombie Panic! Source', 'zps', '1'),
       ('aoc', 'Age of Chivalry', 'aoc', '1'),
       ('cstrike', 'Counter-Strike', 'cstrike', '1'),
       ('tfc', 'Team Fortress Classic', 'tfc', '1'),
       ('dod', 'Day of Defeat', 'dod', '1'),
       ('ns', 'Natural Selection', 'ns', '1'),
       ('l4d', 'Left 4 Dead', 'l4d', '1'),
       ('l4d2', 'Left 4 Dead 2', 'l4d', '1'),
       ('fof', 'Fistful of Frags', 'fof', '1'),
       ('ges', 'GoldenEye: Source', 'ges', '1'),
       ('bg2', 'Battle Grounds 2', 'bg2', '1'),
       ('sgtls', 'Stargate: The Last Stand', 'sgtls', '1'),
       ('dystopia', 'Dystopia', 'dystopia', '1'),
       ('nts', 'NeoTokyo', 'nts', '1'),
       ('pvkii', 'Pirates, Vikings, & Knights II', 'pvkii', '1'),
       ('csp', 'CSPromod', 'csp', '1'),
       ('valve', 'Half-Life 1 Multiplayer', 'valve', '1'),
       ('nd', 'Nuclear Dawn', 'nd', '1'),
       ('csgo', 'Counter-Strike: Global Offensive', 'csgo', '1'),
       ('dinodday', 'Dino D-Day', 'dinodday', '1');