-- name: insert-into-hlstats-Games_Supported

INSERT INTO hlstats_Games_Supported (code, name)
VALUES ('csp', 'CSPromod'),
       ('css', 'Counter-Strike: Source'),
       ('hl2mp', 'Half-Life 2 Multiplayer'),
       ('tf', 'Team Fortress 2'),
       ('dods', 'Day of Defeat: Source'),
       ('insmod', 'Insurgency'),
       ('ff', 'Fortress Forever'),
       ('hidden', 'Hidden: Source'),
       ('zps', 'Zombie Panic: Source'),
       ('aoc', 'Age of Chivalry'),
       ('cstrike', 'Counter-Strike 1.6'),
       ('tfc', 'Team Fortress Classic'),
       ('dod', 'Day of Defeat'),
       ('ns', 'Natural Selection'),
       ('l4d', 'Left 4 Dead (Orig. & 2)'),
       ('fof', 'Fistful of Frags'),
       ('ges', 'GoldenEye: Source'),
       ('bg2', 'Battle Grounds 2'),
       ('sgtls', 'Stargate: The Last Stand'),
       ('dystopia', 'Dystopia'),
       ('nts', 'NeoTokyo'),
       ('pvkii', 'Pirates, Vikings, & Knights II'),
       ('valve', 'Half-Life 1 Multiplayer'),
       ('nd', 'Nuclear Dawn'),
       ('csgo', 'Counter-Strike: Global Offensive'),
       ('dinodday', 'Dino D-Day');