-- name: insert-into-hlstats-Roles

INSERT INTO hlstats_Roles (game, code, name, hidden)
VALUES ('tf', 'engineer', 'Engineer', '0'),
       ('tf', 'spy', 'Spy', '0'),
       ('tf', 'soldier', 'Soldier', '0'),
       ('tf', 'scout', 'Scout', '0'),
       ('tf', 'demoman', 'Demo Man', '0'),
       ('tf', 'sniper', 'Sniper', '0'),
       ('tf', 'medic', 'Medic', '0'),
       ('tf', 'pyro', 'Pyro', '0'),
       ('tf', 'heavyweapons', 'Heavy', '0'),
       ('dods', 'Random', 'Random', '0'),
       ('dods', '#class_allied_garand', 'American Rifleman', '0'),
       ('dods', '#class_allied_thompson', 'American Master Sergeant', '0'),
       ('dods', '#class_allied_heavy', 'American Support Infantry', '0'),
       ('dods', '#class_allied_sniper', 'American Sniper', '0'),
       ('dods', '#class_allied_mg', 'American Machine Gunner', '0'),
       ('dods', '#class_allied_bazooka', 'American Bazooka ', '0'),
       ('dods', '#class_axis_kar98', 'Axis Grenadier', '0'),
       ('dods', '#class_axis_mp40', 'Axis Unteroffizier', '0'),
       ('dods', '#class_axis_mp44', 'Axis Sturmtruppe', '0'),
       ('dods', '#class_axis_sniper', 'Axis Scharfschütze', '0'),
       ('dods', '#class_axis_mg42', 'Axis MG42-Schütze', '0'),
       ('dods', '#class_axis_pschreck', 'Axis Panzerschreck', '0'),
       ('ff', 'engineer', 'Engineer', '0'),
       ('ff', 'spy', 'Spy', '0'),
       ('ff', 'soldier', 'Soldier', '0'),
       ('ff', 'scout', 'Scout', '0'),
       ('ff', 'demoman', 'Demo Man', '0'),
       ('ff', 'sniper', 'Sniper', '0'),
       ('ff', 'medic', 'Medic', '0'),
       ('ff', 'pyro', 'Pyro', '0'),
       ('ff', 'hwguy', 'HWGuy', '0'),
       ('ff', 'civilian', 'Civilian', '0'),
       ('tfc', 'Scout', 'Scout', '0'),
       ('tfc', 'Sniper', 'Sniper', '0'),
       ('tfc', 'Soldier', 'Soldier', '0'),
       ('tfc', 'Demoman', 'Demoman', '0'),
       ('tfc', 'Medic', 'Medic', '0'),
       ('tfc', 'HWGuy', 'HWGuy', '0'),
       ('tfc', 'Pyro', 'Pyro', '0'),
       ('tfc', 'Spy', 'Spy', '0'),
       ('tfc', 'Engineer', 'Engineer', '0'),
       ('tfc', 'Civilian', 'The Hunted', '0'),
       ('dod', 'Random', 'Random', '0'),
       ('dod', '#class_allied_garand', 'American Rifleman', '0'),
       ('dod', '#class_allied_carbine', 'American Staff Sergeant', '0'),
       ('dod', '#class_allied_thompson', 'American Master Sergeant', '0'),
       ('dod', '#class_allied_grease', 'American Sergeant', '0'),
       ('dod', '#class_allied_sniper', 'American Sniper', '0'),
       ('dod', '#class_allied_heavy', 'American Support Infantry', '0'),
       ('dod', '#class_allied_mg', 'American Machine Gunner', '0'),
       ('dod', '#class_alliedpara_garand', 'American Para Rifleman', '0'),
       ('dod', '#class_alliedpara_carbine', 'American Para Staff Sergeant', '0'),
       ('dod', '#class_alliedpara_thompson', 'American Para Master Sergeant', '0'),
       ('dod', '#class_alliedpara_grease', 'American Para Sergeant', '0'),
       ('dod', '#class_alliedpara_spring', 'American Para Sniper', '0'),
       ('dod', '#class_alliedpara_bar', 'American Para Support Infantry', '0'),
       ('dod', '#class_alliedpara_30cal', 'American Para Machine Gunner', '0'),
       ('dod', '#class_brit_light', 'British Rifleman', '0'),
       ('dod', '#class_brit_medium', 'British Sergeant Major', '0'),
       ('dod', '#class_brit_sniper', 'British Marksman', '0'),
       ('dod', '#class_brit_heavy', 'British Gunner', '0'),
       ('dod', '#class_axis_kar98', 'Axis Grenadier', '0'),
       ('dod', '#class_axis_k43', 'Axis Stosstruppe', '0'),
       ('dod', '#class_axis_mp40', 'Axis Unteroffizier', '0'),
       ('dod', '#class_axis_mp44', 'Axis Sturmtruppe', '0'),
       ('dod', '#class_axis_sniper', 'Axis Scharfschütze', '0'),
       ('dod', '#class_axis_mg34', 'Axis MG34-Schütze', '0'),
       ('dod', '#class_axis_mg42', 'Axis MG42-Schütze', '0'),
       ('dod', '#class_axispara_kar98', 'Axis Para Grenadier', '0'),
       ('dod', '#class_axispara_k43', 'Axis Para Stosstruppe', '0'),
       ('dod', '#class_axispara_mp40', 'Axis Para Unteroffizier', '0'),
       ('dod', '#class_axispara_mp44', 'Axis Para Sturmtruppe', '0'),
       ('dod', '#class_axispara_scopedkar', 'Axis Para Scharfschütze', '0'),
       ('dod', '#class_axispara_fg42bipod', 'Axis Para Fg42-Zweinbein', '0'),
       ('dod', '#class_axispara_fg42scope', 'Axis Para Fg42-Zielfernrohr', '0'),
       ('dod', '#class_axispara_mg34', 'Axis Para MG34-Schütze', '0'),
       ('dod', '#class_axispara_mg42', 'Axis Para MG42-Schütze', '0'),
       ('ns', 'soldier', 'Soldier', '0'),
       ('ns', 'commander', 'Commander', '0'),
       ('ns', 'skulk', 'Skulk', '0'),
       ('ns', 'gorge', 'Gorge', '0'),
       ('ns', 'lerk', 'Lerk', '0'),
       ('ns', 'fade', 'Fade', '0'),
       ('ns', 'onos', 'Onos', '0'),
       ('ns', 'gestate', 'Gestate', '1'),
       ('l4d', 'NamVet', 'Bill', '0'),
       ('l4d', 'TeenGirl', 'Zoey', '0'),
       ('l4d', 'Biker', 'Francis', '0'),
       ('l4d', 'Manager', 'Louis', '0'),
       ('l4d', 'GAS', 'Smoker', '0'),
       ('l4d', 'EXPLODING', 'Boomer', '0'),
       ('l4d', 'HUNTER', 'Hunter', '0'),
       ('l4d', 'TANK', 'Tank', '0'),
       ('l4d', 'infected', 'Infected Horde', '0'),
       ('l4d', 'witch', 'Witch', '0'),
       ('l4d2', 'NamVet', 'Bill', '0'),
       ('l4d2', 'TeenGirl', 'Zoey', '0'),
       ('l4d2', 'Biker', 'Francis', '0'),
       ('l4d2', 'Manager', 'Louis', '0'),
       ('l4d2', 'Producer', 'Rochelle', '0'),
       ('l4d2', 'Mechanic', 'Ellis', '0'),
       ('l4d2', 'Coach', 'Coach', '0'),
       ('l4d2', 'Gambler', 'Nick', '0'),
       ('l4d2', 'SMOKER', 'Smoker', '0'),
       ('l4d2', 'BOOMER', 'Boomer', '0'),
       ('l4d2', 'HUNTER', 'Hunter', '0'),
       ('l4d2', 'TANK', 'Tank', '0'),
       ('l4d2', 'CHARGER', 'Charger', '0'),
       ('l4d2', 'SPITTER', 'Spitter', '0'),
       ('l4d2', 'JOCKEY', 'Jockey', '0'),
       ('l4d2', 'infected', 'Infected Horde', '0'),
       ('l4d2', 'witch', 'Witch', '0'),
       ('ges', 'jaws', 'Jaws', '0'),
       ('ges', 'bond', 'Bond', '0'),
       ('ges', 'boris', 'Boris', '0'),
       ('ges', 'Mayday', 'May Day', '0'),
       ('ges', 'Mishkin', 'Mishkin', '0'),
       ('ges', 'oddjob', 'Oddjob', '0'),
       ('ges', 'ourumov', 'Ourumov', '0'),
       ('ges', 'samedi', 'Samedi', '0'),
       ('ges', 'valentin', 'Valentin', '0'),
       ('dystopia', '1', 'Light', '0'),
       ('dystopia', '2', 'Medium', '0'),
       ('dystopia', '3', 'Heavy', '0'),
       ('aoc', 'Longbowman', 'Longbowman', '0'),
       ('aoc', 'Crossbowman', 'Crossbowman', '0'),
       ('aoc', 'Javelineer', 'Javelineer', '0'),
       ('aoc', 'Man at Arms', 'Man at Arms', '0'),
       ('aoc', 'Sergeant', 'Sergeant', '0'),
       ('aoc', 'Guardsman', 'Guardsman', '0'),
       ('aoc', 'Crusader', 'Crusader', '0'),
       ('aoc', 'Knight', 'Knight', '0'),
       ('aoc', 'Heavy Knight', 'Heavy Knight', '0'),
       ('pvkii', 'Berserker', 'Berserker', '0'),
       ('pvkii', 'Gestir', 'Gestir', '0'),
       ('pvkii', 'Huscarl', 'Huscarl', '0'),
       ('pvkii', 'Captain', 'Captain', '0'),
       ('pvkii', 'Skirmisher', 'Skirmisher', '0'),
       ('pvkii', 'Archer', 'Archer', '0'),
       ('pvkii', 'Heavy Knight', 'Heavy Knight', '0'),
       ('nd', 'ASSAULT', 'Assault', '0'),
       ('nd', 'EXO', 'Exo', '0'),
       ('nd', 'STEALTH', 'Stealth', '0'),
       ('nd', 'SUPPORT', 'Support', '0'),
       ('dinodday', '#class_blue_class2', 'Cpl. Joe Spencer', '0'),
       ('dinodday', '#class_blue_class1', 'Cpt. Jack Hardgrave', '0'),
       ('dinodday', '#class_red_class11', 'Microraptor', '0'),
       ('dinodday', '#class_red_class10', 'Compsognathus', '0'),
       ('dinodday', '#class_red_class7', 'Stygimoloch', '0'),
       ('dinodday', '#class_red_class6', 'Dilophosaurus', '0'),
       ('dinodday', '#class_red_class5', 'Desmatosuchus', '0'),
       ('dinodday', '#class_red_class4', 'Velociraptor', '0'),
       ('dinodday', '#class_red_class3', 'Hpt.Fw. Wolfgang von Graff', '0'),
       ('dinodday', '#class_red_class2', 'OLt. Karl Hissmann', '0'),
       ('dinodday', '#class_red_class1', 'Hptm. Kurt Streicher', '0'),
       ('dinodday', '#class_blue_class3', 'Cpt. Nigel Blithe-Crossley', '0'),
       ('dinodday', '#class_blue_class4', 'Ilona Vike', '0'),
       ('dinodday', '#class_blue_class5', 'Camille Brun', '0'),
       ('dinodday', '#class_blue_class6', 'Jakob Frank', '0'),
       ('dinodday', '#class_blue_class7', 'Trigger', '0');
