-- name: create-table-hlstats-Servers

CREATE TABLE IF NOT EXISTS hlstats_Servers
(
    serverId      int(10) unsigned NOT NULL auto_increment,
    address       varchar(32)      NOT NULL default '',
    port          int(5) unsigned  NOT NULL default '0',
    name          varchar(255)     NOT NULL default '',
    sortorder     tinyint          NOT NULL default '0',
    game          varchar(32)      NOT NULL default 'valve',
    publicaddress varchar(128)     NOT NULL default '',
    statusurl     varchar(255)              default NULL,
    rcon_password varchar(128)     NOT NULL default '',
    kills         int(10)          NOT NULL default '0',
    players       int(11)          NOT NULL default '0',
    rounds        int(10)          NOT NULL default '0',
    suicides      int(10)          NOT NULL default '0',
    headshots     int(10)          NOT NULL default '0',
    bombs_planted int(10)          NOT NULL default '0',
    bombs_defused int(10)          NOT NULL default '0',
    ct_wins       int(10)          NOT NULL default '0',
    ts_wins       int(10)          NOT NULL default '0',
    act_players   int(4)           NOT NULL default '0',
    max_players   int(4)           NOT NULL default '0',
    act_map       varchar(64)      NOT NULL default '',
    map_rounds    int(6)           NOT NULL default '0',
    map_ct_wins   int(10)          NOT NULL default '0',
    map_ts_wins   int(10)          NOT NULL default '0',
    map_started   int(10)          NOT NULL default '0',
    map_changes   int(10)          NOT NULL default '0',
    ct_shots      int(11)          NOT NULL default '0',
    ct_hits       int(11)          NOT NULL default '0',
    ts_shots      int(11)          NOT NULL default '0',
    ts_hits       int(11)          NOT NULL default '0',
    map_ct_shots  int(11)          NOT NULL default '0',
    map_ct_hits   int(11)          NOT NULL default '0',
    map_ts_shots  int(11)          NOT NULL default '0',
    map_ts_hits   int(11)          NOT NULL default '0',
    lat           FLOAT(7, 4)      NULL,
    lng           FLOAT(7, 4)      NULL,
    city          varchar(64)      NOT NULL default '',
    country       varchar(64)      NOT NULL default '',
    last_event    int(10) unsigned NOT NULL default '0',
    PRIMARY KEY (serverId),
    UNIQUE KEY addressport (address, port)
) PACK_KEYS = 0;