-- name: insert-into-hlstats-Servers_Config_Default

INSERT INTO hlstats_Servers_Config_Default (parameter, value, description)
VALUES ('Admins', '', 'Steamids seperated by "," ("STEAM_0:1:XXX,STEAM_0:0:XXX,STEAM_0:1:XXX").'),
       ('AutoBanRetry', '0',
        'Auto-bans player for 5 minutes if the disconnect from the server. Prevent players from reconnecting until the have a good team and won''t loose many points. 1=on 0=off(default)'),
       ('AutoTeamBalance', '0',
        'If rcon is enabled hlstats automatically analyzed teams and balance players for fair teams. It will make teams numerical even and also swap players based on there skill to balance teams. 1=on, 0=off(default)'),
       ('BonusRoundIgnore', '0',
        'Ignore frags and actions after round has ended (for applicable games). 1=on, 0=off(default)'),
       ('BonusRoundTime', '0',
        'Length (in seconds) of mp_bonusroundtime (as failsafe in case round_start event is not detected).'),
       ('BroadCastEvents', '1',
        'Nearly all Events will be directly broadcasted through rcon on the server. You will directly see, how many points you got for a kill or bomb plating etc. 1=on 0=off(default)'),
       ('BroadCastEventsCommand', 'hlx_sm_psay', 'The command to broadcast the events. Default is the "say"-command'),
       ('BroadCastEventsCommandAnnounce', 'hlx_sm_csay',
        'Command to announce ingame summary stats and admin email etc. Default is "say".'),
       ('BroadCastPlayerActions', '1',
        'Toggle broadcasting PlayerActions ingame. (f.e Touched a hostage or dropped the Bomb). 1=on(default) 0=off'),
       ('ConnectAnnounce', '1',
        'Toggle display of message upon each player connect showing player points/kills, rank, and country of origin. 1=on(default) 0=off'),
       ('DefaultDisplayEvents', '1',
        'Toggle players default option to see kill/event messages on server. 1=on(default) 0=off'),
       ('DisplayResultsInBrowser', '1',
        'If enabled (1=on 0=off(default)) the player queries will displayed in the valve browser as small html files. (Not support in all game and admin mod combinations)'),
       ('EnablePublicCommands', '1',
        'If activated players can report their statistics to all players in the chat area.'),
       ('GameEngine', '3',
        'Game engine of game on this server:<UL>\r\n<LI>1 = HL1 (GoldSource).\r\n<LI>2 = HL2 (Source original).\r\n<LI>3 = HL2ep2 (Source OrangeBox)(default).</UL>'),
       ('GameType', '0',
        'Mode of the current gametype:<UL>\r\n<LI>0 = Normal mod standard (default).\r\n<LI>1 = Deathmatch (only need to set if team names are NOT "Unassigned" during deathmatch (ie. in CSS Deathmatch).</UL>'),
       ('HLStatsURL', 'http://yoursite.com/hlstats',
        'URL to your HLStats. This is broadcasted to master server and displays ingame.'),
       ('IgnoreBots', '1', 'If enabled, bots are not tracked 1=on(default) 0=off.'),
       ('MinimumPlayersRank', '0',
        'Required players position to be allowed playing on the server (e.g Top500-Server).'),
       ('MinPlayers', '4',
        'Specifies the minimum number of players required in the server for most player events (objectives, frags, etc.) to be recorded.\r\nThis prevents players from hopping on an empty server and boosting their skill rating by capturing the flag, etc., with no opposition.'),
       ('Mod', 'SOURCEMOD',
        'Valid values are SOURCEMOD, MINISTATS, BEETLE, MANI, and AMXX if one of such plugins are installed.'),
       ('PlayerEvents', '1', 'Determine if players can get player-specific display ingame (f.e. /skill)'),
       ('PlayerEventsAdminCommand', '',
        'Some messages (f.e. team-balancer) are only for admins. here you can specify a admin-command. Default is "".'),
       ('PlayerEventsCommand', 'hlx_sm_psay', 'The command to display player events. Default is the "say"-command.'),
       ('PlayerEventsCommandOSD', 'hlx_sm_msay',
        'The command to display amx style menu for "/rank", "/session", "/kpd" commands. Default is "".'),
       ('ShowStats', '1', 'If set to 1 (default) periodically stats are shown ingame with the broadcast-command.'),
       ('SkillMode', '2',
        'Mode of skill changes on frags with following options:\r\n<UL>\r\n<LI>0 = Normal (Victims lose all the points which the killer gains).\r\n<LI>1 = Victims lose 3/4 the points which the killer gains.\r\n<LI>2 = Victims lose 1/2 the points which the killer gains.\r\n<LI>3 = Victims lose 1/4 the points which the killer gains.\r\n<LI>4 = Victims lose no points.\r\n<LI>5 = ZPS-only. Survivor victims lose 1/2, Zombie victims lose 1/4\r\n</UL>'),
       ('SuicidePenalty', '5', 'Penalty for a suicide (Default: 5 points).'),
       ('SwitchAdmins', '0', 'Defines if admins are switched from auto-team balancer 1=on 0=off(default).'),
       ('TKPenalty', '50', 'Penalty for a team kill (Default: 50 points).'),
       ('TrackServerLoad', '1', 'Saves every 5 min how much players are playing on the server.'),
       ('UpdateHostname', '1', 'Toggles auto-update of server name from hostname cvar 1=on(default) 0=off'),
       ('PlayerEventsCommandHint', 'hlx_sm_hint',
        'The command to display "hint" style messages for ATB switches. Default is "".');
