-- name: insert-into-hlstats-Weapons

INSERT INTO hlstats_Weapons (game, code, name, modifier)
VALUES ('tf', 'tf_projectile_rocket', 'Rocket Launcher', 1.00),
       ('tf', 'sniperrifle', 'Sniper Rifle', 1.00),
       ('tf', 'minigun', 'Minigun (Sasha)', 1.00),
       ('tf', 'obj_sentrygun', 'Sentry Gun (Level 1)', 1),
       ('tf', 'knife', 'Knife', 2.00),
       ('tf', 'scattergun', 'Scatter Gun', 1.25),
       ('tf', 'tf_projectile_pipe', 'Grenade Launcher', 1.00),
       ('tf', 'flamethrower', 'Flamethrower', 1.00),
       ('tf', 'tf_projectile_pipe_remote', 'Stickybomb Launcher', 1.00),
       ('tf', 'shotgun_primary', 'Engy Shotgun', 1.00),
       ('tf', 'smg', 'Submachine Gun', 1.00),
       ('tf', 'shotgun_soldier', 'Soldier Shotgun', 1.00),
       ('tf', 'syringegun_medic', 'Syringe Gun', 1.00),
       ('tf', 'revolver', 'Revolver', 1.00),
       ('tf', 'samrevolver', 'Big Kill', 1.00),
       ('tf', 'shotgun_pyro', 'Pyro Shotgun', 1.00),
       ('tf', 'world', 'World', 1.00),
       ('tf', 'bat', 'Bat', 2.00),
       ('tf', 'wrench', 'Wrench', 2.00),
       ('tf', 'wrench_golden', 'Golden Wrench', 2.00),
       ('tf', 'bonesaw', 'Bone Saw', 2.00),
       ('tf', 'shotgun_hwg', 'Heavy Shotgun', 1.00),
       ('tf', 'club', 'Kukri', 2.00),
       ('tf', 'pistol_scout', 'Scout Pistol', 1.50),
       ('tf', 'maxgun', 'Lugermorph', 1.50),
       ('tf', 'pistol', 'Engy Pistol', 1.00),
       ('tf', 'bottle', 'Bottle', 2.00),
       ('tf', 'shovel', 'Shovel', 2.00),
       ('tf', 'fireaxe', 'Fire Axe', 2.00),
       ('tf', 'fists', 'Fists', 2.00),
       ('tf', 'axtinguisher', 'Axtinguisher', 2.00),
       ('tf', 'backburner', 'Backburner', 1.00),
       ('tf', 'blutsauger', 'Blutsauger', 1.50),
       ('tf', 'deflect_flare', 'Deflected Flare', 20.00),
       ('tf', 'deflect_promode', 'Deflected Grenade', 2.00),
       ('tf', 'deflect_rocket', 'Deflected Rocket', 2.00),
       ('tf', 'deflect_sticky', 'Deflected Sticky', 2.00),
       ('tf', 'deflect_arrow', 'Deflected Arrow', 2.00),
       ('tf', 'flaregun', 'Flaregun', 2.00),
       ('tf', 'natascha', 'Minigun (Natascha)', 1.00),
       ('tf', 'gloves', 'K.G.B.', 2.00),
       ('tf', 'taunt_heavy', 'Showdown', 5.00),
       ('tf', 'taunt_pyro', 'Hadouken', 5.00),
       ('tf', 'ubersaw', 'Ubersaw', 2.00),
       ('tf', 'taunt_scout', 'Home Run', 3.00),
       ('tf', 'sandman', 'The Sandman', 1.75),
       ('tf', 'obj_sentrygun2', 'Sentry Gun (Level 2)', 1),
       ('tf', 'obj_sentrygun3', 'Sentry Gun (Level 3)', 1),
       ('tf', 'taunt_sniper', 'Skewer', 3),
       ('tf', 'taunt_spy', 'Fencing', 3),
       ('tf', 'tf_projectile_arrow', 'Huntsman', 1),
       ('tf', 'ambassador', 'Ambassador', 1),
       ('tf', 'tf_pumpkin_bomb', 'Pumpkin Bomb', 2),
       ('tf', 'force_a_nature', 'Force-A-Nature', 1),
       ('tf', 'tf_projectile_arrow_fire', 'Huntsman (Fire arrow)', 1),
       ('tf', 'telefrag', 'Telefrag', 2),
       ('tf', 'rocketlauncher_directhit', 'Direct Hit', 1.0),
       ('tf', 'unique_pickaxe', 'Equalizer', 2.0),
       ('tf', 'sword', 'Eyelander', 2.0),
       ('tf', 'sticky_resistance', 'Scottish Resistance', 1.0),
       ('tf', 'taunt_demoman', 'Decapitation', 5.0),
       ('tf', 'taunt_soldier', 'Kamikaze', 5.0),
       ('tf', 'demoshield', 'Chargin'' Targe', 2.0),
       ('tf', 'ball', 'Baseball', 2.5),
       ('tf', 'taunt_medic', 'Spinal Tap', 5.0),
       ('tf', 'paintrain', 'The Pain Train', 2.00),
       ('tf', 'sledgehammer', 'The Homewrecker', 2.00),
       ('tf', 'tribalkukri', 'Tribalman''s Shiv', 2.00),
       ('tf', 'battleaxe', 'Scotsman''s Skullcutter', 2.00),
       ('tf', 'frontier_justice', 'Frontier Justice', 1.00),
       ('tf', 'obj_minisentry', 'Sentry Gun (Mini)', 1.00),
       ('tf', 'robot_arm', 'Gunslinger', 2.00),
       ('tf', 'robot_arm_combo_kill', 'Gunslinger Combo', 2.00),
       ('tf', 'bleed_kill', 'Bleed Kill', 1.80),
       ('tf', 'robot_arm_blender_kill', 'Organ Grinder', 5.00),
       ('tf', 'southern_hospitality', 'Southern Hospitality', 2.00),
       ('tf', 'taunt_guitar_kill', 'Dischord', 2.00),
       ('tf', 'wrangler_kill', 'Wrangler', 1.00),
       ('tf', 'battleneedle', 'The Vita-Saw', 2.00),
       ('tf', 'powerjack', 'The Powerjack', 2.00),
       ('tf', 'degreaser', 'The Degreaser', 1.00),
       ('tf', 'short_stop', 'The Shortstop', 1.00),
       ('tf', 'holy_mackerel', 'The Holy Mackerel', 2.00),
       ('tf', 'letranger', 'L''Etranger', 1.00),
       ('tf', 'eternal_reward', 'Your Eternal Reward', 2.00),
       ('tf', 'fryingpan', 'Frying Pan', 2.00),
       ('tf', 'bushwacka', 'The Bushwacka', 2.00),
       ('tf', 'gloves_running_urgently', 'Gloves of Running Urgently', 2.00),
       ('tf', 'blackbox', 'The Black Box', 1.00),
       ('tf', 'sydney_sleeper', 'The Sydney Sleeper', 1.00),
       ('tf', 'headtaker', 'Horseless Headless Horsemann''s Headtaker', 2.0),
       ('tf', 'claidheamohmor', 'The Claidheamohmor', 2.0),
       ('tf', 'back_scratcher', 'The Back Scratcher', 2.0),
       ('tf', 'boston_basher', 'The Boston Basher', 2.0),
       ('tf', 'steel_fists', 'The Fists of Steel', 2.0),
       ('tf', 'amputator', 'The Amputator', 1.0),
       ('tf', 'crusaders_crossbow', 'The Crusader''s Crossbow', 1.0),
       ('tf', 'ullapool_caber', 'The Ullapool Caber', 2.0),
       ('tf', 'ullapool_caber_explosion', 'The Ullapool Caber BOOM', 1.2),
       ('tf', 'loch_n_load', 'The Loch-n-Load', 1.0),
       ('tf', 'brass_beast', 'The Brass Beast', 1.0),
       ('tf', 'warrior_spirit', 'The Warrior''s Spirit', 2.0),
       ('tf', 'candy_cane', 'The Candy Cane', 2.0),
       ('tf', 'wrench_jag', 'The Jag', 2.0),
       ('tf', 'iron_curtain', 'The Iron Curtain', 1.0),
       ('tf', 'atomizer', 'Atomizer', 2.00),
       ('tf', 'bazaar_bargain', 'Bazaar Bargain', 1.00),
       ('tf', 'demokatana', 'Half-Zatoichi', 2.00),
       ('tf', 'detonator', 'Detonator', 2.00),
       ('tf', 'disciplinary_action', 'Disciplinary Action', 2.00),
       ('tf', 'enforcer', 'Enforcer', 2.00),
       ('tf', 'eviction_notice', 'Eviction Notice', 2.00),
       ('tf', 'family_business', 'Family Business', 1.00),
       ('tf', 'kunai', 'Conniver''s Kunai', 2.00),
       ('tf', 'liberty_launcher', 'Liberty Launcher', 1.00),
       ('tf', 'mantreads', 'Mantreads', 2.00),
       ('tf', 'market_gardener', 'Market Gardener', 2.00),
       ('tf', 'persian_persuader', 'Persian Persuader', 2.00),
       ('tf', 'proto_syringe', 'Overdose', 2.00),
       ('tf', 'reserve_shooter', 'Reserve Shooter', 2.00),
       ('tf', 'scout_sword', 'Three-Rune Blade', 2.00),
       ('tf', 'shahanshah', 'Shahanshah', 2.00),
       ('tf', 'soda_popper', 'Soda Popper', 1.25),
       ('tf', 'solemn_vow', 'Solemn Vow', 2.00),
       ('tf', 'the_maul', 'Maul', 2.00),
       ('tf', 'the_winger', 'Winger', 1.00),
       ('tf', 'tomislav', 'Tomislav', 1.00),
       ('tf', 'warfan', 'Fan O''War', 2.00),
       ('tf', 'big_earner', 'Big Earner', 2.00),
       ('tf', 'saxxy', 'Saxxy', 2.00),
       ('tf', 'splendid_screen', 'Splendid Screen', 2.00),
       ('tf', 'taunt_soldier_lumbricus', 'Kamikaze (Lumbricus Lid)', 5.00),
       ('tf', 'nessieclub', 'Nessie\'s Nine Iron', 2.00),
       ('tf', 'mailbox', 'Postal Pummeler', 2.00),
       ('tf', 'lava_axe', 'Sharpened Volcano Fragment', 2.00),
       ('tf', 'lava_bat', 'Sun-on-a-Stick', 2.00),
       ('tf', 'cow_mangler', 'Cow Mangler 5000', 1.00),
       ('tf', 'righteous_bison', 'Righteous Bison', 2.00),
       ('tf', 'tf_projectile_energy_ball', 'Deflected Cow Mangler Shot', 5.00),
       ('tf', 'machina', 'Machina', 2.00),
       ('tf', 'diamondback', 'The Diamondback', 2.00),
       ('tf', 'widowmaker', 'The Widowmaker', 2.00),
       ('tf', 'short_circuit', 'The Short Circuit', 2.00),
       ('tf', 'quake_rl', 'Original', 2.00),
       ('tf', 'scotland_shard', 'Scottish Handshake', 2.00),
       ('tf', 'nonnonviolent_protest', 'Conscientious Objector', 2.00),
       ('tf', 'deflect_flare_detonator', 'Deflected Flare (Detonator)', 2.00),
       ('tf', 'deflect_huntsman_flyingburn', 'Deflect Huntsman Burning Arrow', 2.00),
       ('tf', 'unarmed_combat', 'Unarmed Combat', 2.00),
       ('tf', 'eureka_effect', 'Eureka Effect', 2.00),
       ('tf', 'holiday_punch', 'Holiday Punch', 2.00),
       ('tf', 'manmelter', 'Manmelter', 2.00),
       ('tf', 'phlogistinator', 'Phlogistinator', 2.00),
       ('tf', 'pomson', 'Pomson 6000', 2.00),
       ('tf', 'spy_cicle', 'Spy-cicle', 2.00),
       ('tf', 'thirddegree', 'Third Degree', 2.00),
       ('tf', 'wrap_assassin', 'Wrap Assassin', 2.00),
       ('tf', 'pep_pistol', 'Pretty Boy\'s Pocket Pistol ', 1.50),
       ('tf', 'pep_brawlerblaster', 'Baby Face\'s Blaster', 1.00),
       ('tf', 'dumpster_device', 'Beggar\'s Bazooka', 1.00),
       ('tf', 'pro_smg', 'The Cleaner\'s Carbine', 1.00),
       ('tf', 'pro_rifle', 'The Hitman\'s Heatmaker', 1.00),
       ('tf', 'rainblower', 'The Rainblower', 1.00),
       ('tf', 'lollichop', 'The Lollichop', 2.00),
       ('tf', 'scorchshot', 'The Scorch Shot', 2.00),
       ('tf', 'unique_pickaxe_escape', 'The Escape Plan', 1.00),
       ('csp', 'knife', 'Bundeswehr Advanced Combat Knife', 2.00),
       ('csp', 'usp', 'H&K USP .45 Tactical', 1.40),
       ('csp', 'glock', 'Glock 18 Select Fire', 1.40),
       ('csp', 'deagle', 'Desert Eagle .50AE', 1.20),
       ('csp', 'mp5navy', 'H&K MP5-Navy', 1.20),
       ('csp', 'm4a1', 'Colt M4A1 Carbine', 1.00),
       ('csp', 'ak47', 'Kalashnikov AK-47', 1.00),
       ('csp', 'awp', 'Arctic Warfare Magnum (Police)', 1.00),
       ('csp', 'hegrenade', 'High Explosive Grenade', 1.80),
       ('csp', 'famas', 'Fusil Automatique', 1.00),
       ('csp', 'galil', 'Galil', 1.10),
       ('css', 'knife', 'Bundeswehr Advanced Combat Knife', 2.00),
       ('css', 'usp', 'H&K USP .45 Tactical', 1.40),
       ('css', 'glock', 'Glock 18 Select Fire', 1.40),
       ('css', 'deagle', 'Desert Eagle .50AE', 1.20),
       ('css', 'p228', 'Sig Sauer P-228', 1.50),
       ('css', 'm3', 'Benelli M3 Super 90 Combat', 1.20),
       ('css', 'xm1014', 'Benelli/H&K M4 Super 90 XM1014', 1.10),
       ('css', 'mp5navy', 'H&K MP5-Navy', 1.20),
       ('css', 'tmp', 'Steyr Tactical Machine Pistol', 1.50),
       ('css', 'p90', 'FN P90', 1.20),
       ('css', 'm4a1', 'Colt M4A1 Carbine', 1.00),
       ('css', 'ak47', 'Kalashnikov AK-47', 1.00),
       ('css', 'sg552', 'Sig Sauer SG-552 Commando', 1.00),
       ('css', 'scout', 'Steyr Scout', 1.10),
       ('css', 'awp', 'Arctic Warfare Magnum (Police)', 1.00),
       ('css', 'g3sg1', 'H&K G3/SG1 Sniper Rifle', 0.80),
       ('css', 'm249', 'M249 PARA Light Machine Gun', 1.20),
       ('css', 'hegrenade', 'High Explosive Grenade', 1.80),
       ('css', 'flashbang', 'Flashbang', 5.00),
       ('css', 'elite', 'Dual Beretta 96G Elite', 1.40),
       ('css', 'aug', 'Steyr Aug', 1.00),
       ('css', 'mac10', 'Ingram MAC-10', 1.50),
       ('css', 'fiveseven', 'FN Five-Seven', 1.50),
       ('css', 'ump45', 'H&K UMP45', 1.20),
       ('css', 'sg550', 'Sig SG-550 Sniper', 0.80),
       ('css', 'famas', 'Fusil Automatique', 1.00),
       ('css', 'galil', 'Galil', 1.10),
       ('css', 'smokegrenade_projectile', 'Smoke Grenade', 5.00),
       ('css', 'PROP_PHYSICS', 'Rare Physics kill', 10.00),
       ('hl2mp', 'env_explosion', 'Explosion', 2.70),
       ('hl2mp', 'player', 'pTelefrag', 10.00),
       ('hl2mp', 'physbox', 'bTelefrag', 7.20),
       ('hl2mp', 'physics', 'Physics', 7.00),
       ('hl2mp', 'crowbar', 'Crowbar', 15.00),
       ('hl2mp', 'stunstick', 'Stun Stick', 15.00),
       ('hl2mp', 'pistol', 'USP Match', 10.00),
       ('hl2mp', '357', '.357 Magnum', 4.30),
       ('hl2mp', 'smg1', 'Sub Machine Gun', 0.00),
       ('hl2mp', 'smg1_grenade', 'Impact Grenade', 2.50),
       ('hl2mp', 'ar2', 'Combine Assault Rifle', 1.00),
       ('hl2mp', 'combine_ball', 'Combine Ball', 2.40),
       ('hl2mp', 'shotgun', 'Shotgun', 3.80),
       ('hl2mp', 'crossbow_bolt', 'Crossbow', 7.30),
       ('hl2mp', 'rpg_missile', 'Rocket Propelled Grenade', 0.00),
       ('hl2mp', 'grenade_frag', 'Frag Grenade', 3.70),
       ('hl2mp', 'slam', 'Slam', 4.60),
       ('hl2mp', 'physcannon', 'Physics Cannon', 2.70),
       ('hl2ctf', 'stunstick', 'Stun Stick', 2.50),
       ('hl2ctf', 'Crowbar', 'Crowbar', 2.50),
       ('hl2ctf', 'crossbow_bolt', 'Crossbow', 1.75),
       ('hl2ctf', 'Slam', 'S.L.A.M', 1.80),
       ('hl2ctf', 'Pistol', 'USP Match', 1.75),
       ('hl2ctf', 'grenade_frag', 'Grenade', 1.75),
       ('hl2ctf', 'combine_ball', 'Combine Ball', 1.50),
       ('hl2ctf', 'physcannon', 'Gravity Gun', 1.15),
       ('hl2ctf', 'Shotgun', 'Shotgun', 1.10),
       ('hl2ctf', '357', '.357 Magnum', 1.10),
       ('hl2ctf', 'rpg_missile', 'Rocket Propelled Grenade', 1.00),
       ('hl2ctf', 'ar2', 'Combine Assault Rifle', 1.00),
       ('hl2ctf', 'smg1', 'Sub Machine Gun', 1.00),
       ('hl2ctf', 'env_explosion', 'Explosion', 1.00),
       ('hl2ctf', 'ctf_combine_turret', 'Combine Turret', 1.25),
       ('hl2ctf', 'ctf_rebel_turret', 'Rebel Turret', 1.25),
       ('hl2ctf', 'ctf_oicw', 'OICW Rifle', 1.00),
       ('hl2ctf', 'ctf_sniper', 'Sniper Rifle', 1.10),
       ('hl2ctf', 'grenade_ctf_oicw_airburst', 'OICW Grenade', 1.20),
       ('hl2ctf', 'ctf_alyxgun', 'Alyx Gun', 1.15),
       ('hl2ctf', 'smg1_grenade', 'SMG Grenade', 1.10),
       ('dods', 'k98', 'Mauser Kar 98k', 1.30),
       ('dods', 'mp40', 'MP40 Machine Pistol', 1.25),
       ('dods', 'k98_scoped', 'Mauser Karbiner k98 Sniper Rifle', 1.50),
       ('dods', 'mp44', 'MP44 Assault Rifle', 1.35),
       ('dods', 'colt', 'Colt .45 model 1911', 1.60),
       ('dods', 'riflegren_us', 'M1 Garand Rifle', 1.30),
       ('dods', 'thompson', 'Thompson Submachine Gun', 1.25),
       ('dods', 'spring', 'Springfield Rifle with Scope', 1.50),
       ('dods', 'bar', 'BAR Browning Automatic Rifle', 1.20),
       ('dods', 'frag_us', 'U.S. Grenade', 1.00),
       ('dods', 'm1carbine', 'M1 Carbine', 1.20),
       ('dods', '30cal', '.30 Caliber Machine Gun', 1.25),
       ('dods', 'frag_ger', 'German Grenade', 1.00),
       ('dods', 'spade', 'Spade Entrenchment Tool', 3.00),
       ('dods', 'amerknife', 'U.S. Issue Knife', 3.00),
       ('dods', 'bazooka', 'Bazooka', 2.25),
       ('dods', 'pschreck', 'Panzerschreck', 2.25),
       ('dods', 'riflegren_ger', 'German Rifle Grenade', 1.30),
       ('dods', 'garand', 'M1 Garand Rifle', 1.30),
       ('dods', 'p38', 'Pistol 38', 1.50),
       ('dods', 'c96', 'Pistol c96', 1.50),
       ('dods', 'punch', 'Butt Stock Hit', 3.00),
       ('dods', 'mg42', 'MG42 Machine Gun', 1.20),
       ('dods', 'smoke_ger', 'German Smoke Grenade', 5.00),
       ('dods', 'smoke_us', 'U.S. Smoke Grenade', 5.00),
       ('dods', 'dod_bomb_target', 'TNT Bomb', 1.00),
       ('insmod', 'weapon_makarov', 'Soviet Makarov Combat Pistol', 1.5),
       ('insmod', 'weapon_m9', '9mm Beretta Pistol', 1.5),
       ('insmod', 'world', 'RPG or Grenade', 1.4),
       ('insmod', 'weapon_sks', 'Simonov SKS carbine', 1.3),
       ('insmod', 'weapon_m1014', 'M1014 Service Combat Shotgun', 1.2),
       ('insmod', 'weapon_toz', 'TOZ Rifle', 1.1),
       ('insmod', 'weapon_svd', 'Dragunov Sniper Rifle', 1.1),
       ('insmod', 'weapon_rpk', 'RPK Ruchnoy Pulemyot Kalashnikova', 1.1),
       ('insmod', 'weapon_m249', 'M249 SAW (Squad Automatic Weapon)', 1.1),
       ('insmod', 'weapon_m16m203', 'M16 carbine M203 Grenade Launcher', 1.1),
       ('insmod', 'weapon_l42a1', 'Enfield L42A1 Military Sniper Rifle', 1.1),
       ('insmod', 'weapon_m4med', 'M4 Medium Range Rifle', 1),
       ('insmod', 'weapon_m4', 'M4 Carbine Rifle', 1),
       ('insmod', 'weapon_m16a4', 'M16A4 Infantry Rifle', 1),
       ('insmod', 'weapon_m14', 'Colt M14 Carbine', 1),
       ('insmod', 'weapon_fnfal', 'FN FAL Automatic Rifle', 1),
       ('insmod', 'weapon_aks74u', 'AKS-74U Awtomat Kalaschnikowa Ukorochennyj', 1),
       ('insmod', 'weapon_ak47', 'AK-47 Awtomat Kalaschnikowa', 1),
       ('ff', 'weapon_railgun', 'Railgun', 1.00),
       ('ff', 'weapon_tranq', 'Tranq Gun', 1.00),
       ('ff', 'weapon_medkit', 'Medkit', 1.00),
       ('ff', 'weapon_spanner', 'Spanner', 1.00),
       ('ff', 'weapon_crowbar', 'Crowbar', 1.00),
       ('ff', 'weapon_shotgun', 'Shotgun', 1.00),
       ('ff', 'grenade_napalm', 'Napalm Grenade', 1.00),
       ('ff', 'weapon_ic', 'IC', 1.00),
       ('ff', 'grenade_nail', 'Nail Grenade', 1.00),
       ('ff', 'weapon_supershotgun', 'Super Shotgun', 1.00),
       ('ff', 'weapon_supernailgun', 'Super Nailgun', 1.00),
       ('ff', 'weapon_sniperrifle', 'Sniper Rifle', 1.00),
       ('ff', 'weapon_rpg', 'Rocket Launcher', 1.00),
       ('ff', 'weapon_pipelauncher', 'Pipe Launcher', 1.00),
       ('ff', 'weapon_knife', 'Knife', 1.00),
       ('ff', 'weapon_grenadelauncher', 'Grenade Launcher', 1.00),
       ('ff', 'weapon_flamethrower', 'Flamethrower', 1.00),
       ('ff', 'Dispenser', 'Dispenser', 1.00),
       ('ff', 'weapon_autorifle', 'Auto Rifle', 1.00),
       ('ff', 'weapon_assaultcannon', 'Assault Cannon', 1.00),
       ('ff', 'SentryGun', 'Sentry Gun', 1.00),
       ('ff', 'grenade_normal', 'Frag Grenade', 1.00),
       ('ff', 'grenade_mirv', 'Mirv Grenade', 1.00),
       ('ff', 'grenade_emp', 'Emp Grenade', 1.00),
       ('ff', 'DETPACK', 'Detpack', 1.00),
       ('ff', 'weapon_umbrella', 'Umbrella', 10.00),
       ('ff', 'grenade_gas', 'Gas Grenade', 1.00),
       ('ff', 'weapon_tommygun', 'Tommygun', 1.00),
       ('ff', 'weapon_nailgun', 'Nailgun', 1.00),
       ('ff', 'backstab', 'Backstab', 1.00),
       ('hidden', 'fn2000', 'FN2000 Assault Rifle', 1.50),
       ('hidden', 'p90', 'FN P90 Sub Machine Gun', 2.00),
       ('hidden', 'shotgun', 'Remington 870 MCS Shotgun', 2.00),
       ('hidden', 'fn303', 'FN303 Less Lethal Launcher', 2.00),
       ('hidden', 'pistol', 'FN FiveSeven Pistol', 3.00),
       ('hidden', 'pistol2', 'FNP-9 Pistol', 3.00),
       ('hidden', 'knife', 'Kabar D2 Knife', 2.50),
       ('hidden', 'grenade_projectile', 'Pipe Bomb', 2.00),
       ('hidden', 'physics', 'Physics', 3.00),
       ('zps', 'arms', 'Zombie', 1),
       ('zps', 'carrierarms', 'Carrier', 1),
       ('zps', 'ak47', 'AK-47', 1),
       ('zps', 'mp5', 'MP5', 1),
       ('zps', 'revolver', 'Revolver', 1),
       ('zps', 'glock', 'Glock 17', 1),
       ('zps', 'glock18c', 'Glock 18c', 1),
       ('zps', 'ppk', 'Walther PPK', 1),
       ('zps', 'usp', 'Heckler & Kock USP', 1),
       ('zps', '870', 'Remington 870', 1),
       ('zps', 'supershorty', 'Mossberg Super Shorty', 1),
       ('zps', 'grenade_frag', 'Grenade', 1),
       ('zps', 'sledgehammer', 'Sledgehammer', 1.5),
       ('zps', 'crowbar', 'Crowbar', 1.5),
       ('zps', 'chair', 'Chair', 1.5),
       ('zps', 'keyboard', 'Keyboard', 1.5),
       ('zps', 'plank', 'Wooden Plank', 1.5),
       ('zps', 'shovel', 'Shovel', 1.5),
       ('zps', 'golf', 'Golf Club', 1.5),
       ('zps', 'machete', 'Machete', 1.5),
       ('zps', 'fryingpan', 'Frying Pan', 1.5),
       ('zps', 'spanner', 'Wrench', 1.5),
       ('zps', 'axe', 'Axe', 1.5),
       ('zps', 'tireiron', 'Tire Iron', 1.5),
       ('zps', 'hammer', 'Hammer', 1.5),
       ('zps', 'pot', 'Pot', 1.5),
       ('zps', 'world', 'World', 1.5),
       ('zps', 'physics', 'Physics', 1.5),
       ('zps', 'torque', 'Torque', 1.0),
       ('zps', 'winchester', 'Winchester Double Barreled Shotgun', 1),
       ('zps', 'bat_aluminum', 'Bat (Aluminum)', 1.5),
       ('zps', 'bat_wood', 'Bat (Wood)', 1.5),
       ('zps', 'm4', 'M4', 1),
       ('zps', 'pipe', 'Pipe', 1),
       ('zps', 'slam', 'IED', 1),
       ('aoc', 'Flamberge', 'Flamberge', 1),
       ('aoc', 'Longsword', 'Longsword', 1),
       ('aoc', 'Glaive', 'Glaive', 1),
       ('aoc', 'Dual Daggers', 'Dual Daggers', 1),
       ('aoc', 'Flamberge & Kite Shield', 'Flamberge & Kite Shield', 1),
       ('aoc', 'world', 'World', 1),
       ('aoc', 'chivalry', 'Chivalry', 1),
       ('aoc', 'Shortsword', 'Shortsword', 1),
       ('aoc', 'Warhammer', 'Warhammer', 1),
       ('aoc', 'Mace', 'Mace', 1),
       ('aoc', 'Mace & Buckler', 'Mace & Buckler', 1),
       ('aoc', 'Broadsword & Evil Shield', 'Mason Broadsword & Shield', 1),
       ('aoc', 'Crossbow', 'Crossbow', 1),
       ('aoc', 'Longbow', 'Longbow', 1),
       ('aoc', 'Longsword & Kite Shield', 'Longsword & Kite Shield', 1),
       ('aoc', 'Broadsword & Good Shield', 'Knights Broadsword & Shield', 1),
       ('aoc', 'Hatchet', 'Hatchet', 1),
       ('aoc', 'Double Axe', 'Battle Axe', 1),
       ('aoc', 'Flail & Evil Shield', 'Mason Flail & Shield', 1),
       ('aoc', 'Flail & Good Shield', 'Knights Flail & Shield', 1),
       ('aoc', 'Javelin', 'Javelin', 1),
       ('aoc', 'Spear & Buckler', 'Spear & Buckler', 1),
       ('aoc', 'Dagger', 'Dagger', 1),
       ('aoc', 'Broadsword', 'Broadsword', 1),
       ('aoc', 'Throwing Knife', 'Throwing Knife', 1),
       ('aoc', 'Spiked Mace', 'Spiked Mace', 1),
       ('aoc', 'Spiked Mace & Buckler', 'Spiked Mace & Buckler', 1),
       ('aoc', 'Halberd', 'Halberd', 1),
       ('aoc', 'Oil Pot', 'Oil Pot', 1),
       ('aoc', 'Fists', 'Fists', 2),
       ('aoc', 'Throwing Axe', 'Throwing Axe', 1),
       ('cstrike', 'knife', 'Bundeswehr Advanced Combat Knife', 1.80),
       ('cstrike', 'usp', 'H&K USP .45 Tactical', 1.50),
       ('cstrike', 'glock18', 'Glock 18 Select Fire', 1.50),
       ('cstrike', 'deagle', 'Desert Eagle .50AE', 1.50),
       ('cstrike', 'p228', 'Sig Sauer P-228', 1.50),
       ('cstrike', 'm3', 'Benelli M3 Super 90 Combat', 1.40),
       ('cstrike', 'xm1014', 'Benelli/H&K M4 Super 90 XM1014', 1.40),
       ('cstrike', 'mp5navy', 'H&K MP5-Navy', 1.25),
       ('cstrike', 'tmp', 'Steyr Tactical Machine Pistol', 1.25),
       ('cstrike', 'p90', 'FN P90', 1.25),
       ('cstrike', 'm4a1', 'Colt M4A1 Carbine', 1.00),
       ('cstrike', 'ak47', 'Kalashnikov AK-47', 1.00),
       ('cstrike', 'sg552', 'Sig Sauer SG-552 Commando', 1.00),
       ('cstrike', 'scout', 'Steyr Scout', 1.60),
       ('cstrike', 'awp', 'Arctic Warfare Magnum (Police)', 1.40),
       ('cstrike', 'g3sg1', 'H&K G3/SG1 Sniper Rifle', 1.40),
       ('cstrike', 'm249', 'M249 PARA Light Machine Gun', 0.80),
       ('cstrike', 'grenade', 'High Explosive Grenade', 1.80),
       ('cstrike', 'elite', 'Dual Beretta 96G Elite', 1.50),
       ('cstrike', 'aug', 'Steyr Aug', 1.00),
       ('cstrike', 'mac10', 'Ingram MAC-10', 1.25),
       ('cstrike', 'fiveseven', 'FN Five-Seven', 1.50),
       ('cstrike', 'ump45', 'H&K UMP45', 1.25),
       ('cstrike', 'sg550', 'Sig SG-550 Sniper', 1.70),
       ('cstrike', 'famas', 'Fusil Automatique', 1.00),
       ('cstrike', 'galil', 'Galil', 1.00),
       ('tfc', 'sniperrifle', 'Sniper Rifle', 1.00),
       ('tfc', 'normalgrenade', 'Normal Grenade', 1.10),
       ('tfc', 'ac', 'Autocannon', 1.00),
       ('tfc', 'rocket', 'Rocket Launcher', 1.00),
       ('tfc', 'sentrygun', 'Sentry Gun', 1.00),
       ('tfc', 'supershotgun', 'Super Shotgun', 1.15),
       ('tfc', 'autorifle', 'Sniper Rifle (Auto Mode)', 1.20),
       ('tfc', 'empgrenade', 'EMP Grenade', 1.25),
       ('tfc', 'mirvgrenade', 'MIRV Grenade', 1.25),
       ('tfc', 'gl_grenade', 'Grenade Launcher', 1.35),
       ('tfc', 'pipebomb', 'Pipebomb', 1.35),
       ('tfc', 'timer', 'Infection Timer', 0.00),
       ('tfc', 'infection', 'Infection', 1.50),
       ('tfc', 'flames', 'Flame Thrower', 1.60),
       ('tfc', 'shotgun', 'Shotgun', 1.60),
       ('tfc', 'nails', 'Nail Gun', 1.70),
       ('tfc', 'nailgrenade', 'Nail Grenade', 1.70),
       ('tfc', 'supernails', 'Super Nail Gun', 1.65),
       ('tfc', 'axe', 'Crowbar', 1.80),
       ('tfc', 'medikit', 'Medikit', 1.85),
       ('tfc', 'napalmgrenade', 'Napalm Grenade', 1.70),
       ('tfc', 'detpack', 'Detpack', 1.80),
       ('tfc', 'gasgrenade', 'Gas Grenade', 1.90),
       ('tfc', 'spanner', 'Spanner', 2.00),
       ('tfc', 'caltrop', 'Caltrops', 2.00),
       ('tfc', 'railgun', 'Rail Gun', 1.85),
       ('tfc', 'building_dispenser', 'Dispenser', 2.00),
       ('dod', 'k43', 'Karbiner 43', '1.50'),
       ('dod', 'luger', 'Luger 08 Pistol', '1.50'),
       ('dod', 'kar', 'Mauser Kar 98k', '1.30'),
       ('dod', 'mp40', 'MP40 Machine Pistol', '1.25'),
       ('dod', 'scopedkar', 'Mauser Karbiner 98k Sniper Rifle', '1.50'),
       ('dod', 'mp44', 'MP44 Assault Rifle', '1.35'),
       ('dod', 'colt', 'Colt .45 model 1911', '1.60'),
       ('dod', 'garand', 'M1 Garand Rifle', '1.30'),
       ('dod', 'thompson', 'Thompson Submachine Gun', '1.25'),
       ('dod', 'spring', 'Springfield Rifle with Scope', '1.50'),
       ('dod', 'bar', 'BAR Browning Automatic Rifle', '1.20'),
       ('dod', 'grenade', 'U.S. Grenade', '1.00'),
       ('dod', 'enf_bayonet', 'Enfield Bayonet', '2.50'),
       ('dod', 'bren', 'Bren Machine Gun', '1.25'),
       ('dod', 'm1carbine', 'M1 Carbine', '1.20'),
       ('dod', 'greasegun', 'Greasegun', '1.30'),
       ('dod', '30cal', '.30 Caliber Machine Gun', '1.25'),
       ('dod', 'mg42', 'MG42 Machine Gun', '1.20'),
       ('dod', 'grenade2', 'German Grenade', '1.00'),
       ('dod', 'spade', 'Spade Entrenchment Tool', '3.00'),
       ('dod', 'gerknife', 'German Knife', '3.00'),
       ('dod', 'fg42', 'FG42 Paratroop Rifle', '1.25'),
       ('dod', 'world', 'worldspawn', '0.00'),
       ('dod', 'amerknife', 'U.S. Issue Knife', '3.00'),
       ('dod', 'bayonet', 'Karbiner Bayonet', '2.40'),
       ('dod', 'mg34', 'MG34 Machine Gun', '1.20'),
       ('dod', 'brit_knife', 'British Knife', '3.00'),
       ('dod', 'mortar', 'Mortar', '1.00'),
       ('dod', 'fcarbine', 'F1 Carbine', '1.35'),
       ('dod', 'scoped_fg42', 'Scoped FG42', '1.30'),
       ('dod', 'bazooka', 'Bazooka', '2.25'),
       ('dod', 'enfield', 'Enfield Rifle', '1.35'),
       ('dod', 'garandbutt', 'Butt Stock Hit', '3.00'),
       ('dod', 'mills_bomb', 'British Grenade', '1.00'),
       ('dod', 'piat', 'Piat', '2.25'),
       ('dod', 'pschreck', 'Panzerschreck', '2.25'),
       ('dod', 'scoped_enfield', 'Scoped Enfield', '1.50'),
       ('dod', 'sten', 'Sten Submachine Gun', '1.25'),
       ('dod', 'webley', 'Webley Revolver', '1.60'),
       ('ns', 'welder', 'Marine Welder', '3.00'),
       ('ns', 'item_mine', 'Marine Mine', '1.00'),
       ('ns', 'handgrenade', 'Marine Hand Grenade', '1.00'),
       ('ns', 'grenade', 'Marine Grenade Launcher', '1.00'),
       ('ns', 'knife', 'Marine Knife', '4.00'),
       ('ns', 'pistol', 'Marine Pistol', '2.00'),
       ('ns', 'machinegun', 'Marine Light Machine Gun', '1.25'),
       ('ns', 'shotgun', 'Marine Shotgun', '1.00'),
       ('ns', 'heavymachinegun', 'Marine Heavy Machine Gun', '1.00'),
       ('ns', 'turret', 'Marine Turret', '.75'),
       ('ns', 'siegeturret', 'Marine Siege Turret', '1.00'),
       ('ns', 'resourcetower', 'Electrified Marine Resource Tower', '2.00'),
       ('ns', 'team_turretfactor', 'Electric Marine Turret Factory', '2.00'),
       ('ns', 'team_advturretfactor', 'Electrified Marine Advance Turret Factory', '2.00'),
       ('ns', 'acidrocket', 'Fade Acid Rocket', '1.00'),
       ('ns', 'bitegun', 'Skulk Bite', '1.25'),
       ('ns', 'charge', 'Onos Charge', '1.00'),
       ('ns', 'claws', 'Onos Gore', '1.00'),
       ('ns', 'divinewind', 'Skulk Xenocide', '1.00'),
       ('ns', 'leap', 'Skulk Leap', '2.00'),
       ('ns', 'bite2gun', 'Lerk Bite', '2.00'),
       ('ns', 'spitgunspit', 'Gorge Spit', '2.00'),
       ('ns', 'sporegunprojectile', 'Lerk Spores', '1.00'),
       ('ns', 'swipe', 'Fade Slash', '1.00'),
       ('ns', 'healingspray', 'Gorge Health Spray', '3.00'),
       ('ns', 'parasite', 'Skulk Parasite', '3.00'),
       ('ns', 'devour', 'Onos Devour', '2.00'),
       ('ns', 'offensechamber', 'Offense Chamber', '1.00'),
       ('l4d', 'rifle', 'M16 Assault Rifle', 1.00),
       ('l4d', 'autoshotgun', 'Auto Shotgun', 1.00),
       ('l4d', 'pumpshotgun', 'Pump Shotgun', 1.30),
       ('l4d', 'smg', 'Uzi', 1.20),
       ('l4d', 'dual_pistols', 'Dual Pistols', 1.60),
       ('l4d', 'pipe_bomb', 'Pipe Bomb', 1.00),
       ('l4d', 'hunting_rifle', 'Hunting Rifle', 1.00),
       ('l4d', 'pistol', 'Pistol', 2.00),
       ('l4d', 'prop_minigun', 'Mounted Machine Gun', 1.20),
       ('l4d', 'tank_claw', 'Tank''s Claws', 3.00),
       ('l4d', 'hunter_claw', 'Hunter''s Claws', 3.00),
       ('l4d', 'smoker_claw', 'Smoker''s Claws', 3.00),
       ('l4d', 'boomer_claw', 'Boomer''s Claws', 3.00),
       ('l4d', 'inferno', 'Molotov/Gas Can Fire', 1.20),
       ('l4d', 'infected', 'Infected Horde', 1.00),
       ('l4d', 'witch', 'Witch''s Claws', 1.00),
       ('l4d', 'entityflame', 'Blaze', 3),
       ('l4d', 'first_aid_kit', 'First Aid Kit Smash', 1.5),
       ('l4d', 'gascan', 'Gas Can Smash', 1.5),
       ('l4d', 'molotov', 'Molotov Smash', 1.5),
       ('l4d', 'pain_pills', 'Pain Pills Smash', 1.5),
       ('l4d', 'player', 'Player', 1),
       ('l4d', 'propanetank', 'Propane Tank Smash', 1.5),
       ('l4d', 'tank_rock', 'Tank''s Rock', 1.5),
       ('l4d', 'oxygentank', 'Oxygen Tank Smash', 1.5),
       ('l4d', 'world', 'World', 1),
       ('l4d', 'prop_physics', 'Prop Physics', 1),
       ('fof', 'deringer', 'Deringer', 1),
       ('fof', 'carbine', 'Carbine', 1),
       ('fof', 'coltnavy', 'Colt Navy', 1),
       ('fof', 'bow', 'Bow', 1),
       ('fof', 'arrow', 'Arrow', 1),
       ('fof', 'sharps', 'Sharps', 1),
       ('fof', 'coachgun', 'Coach Gun', 1),
       ('fof', 'peacemaker', 'Peacemaker', 1),
       ('fof', 'knife', 'Knife', 2),
       ('fof', 'physics', 'Exploding Barrel', 1),
       ('fof', 'thrown_axe', 'Thrown Axe', 3),
       ('fof', 'arrow_fiery', 'Fire Arrow', 2),
       ('fof', 'thrown_knife', 'Thrown Knife', 3),
       ('fof', 'dualnavy', 'Dual Colt Navys', 1),
       ('fof', 'dynamite', 'Dynamite', 3),
       ('fof', 'explosive_arrow', 'Explosive Arrow', 2),
       ('fof', 'fists', 'Fists', 2),
       ('fof', 'axe', 'Axe', 2),
       ('fof', 'dualpeacemaker', 'Dual Peacemakers', 1),
       ('fof', 'henryrifle', 'Henry Rifle', 1),
       ('fof', 'shotgun', 'Winchester Shotgun', 1),
       ('ges', '#GE_ProximityMine', 'Proximity Mines', 1),
       ('ges', '#GE_AutoShotgun', 'Automatic Shotgun', 1),
       ('ges', '#GE_Phantom', 'Phantom', 1),
       ('ges', '#GE_Knife', 'Hunting Knife', 1),
       ('ges', '#GE_D5K', 'D5K Deutsche', 1),
       ('ges', '#GE_SilverPP7', 'Silver PP7', 1),
       ('ges', '#GE_DD44', 'DD44', 1),
       ('ges', '#GE_Grenade', 'Grenade', 1),
       ('ges', '#GE_CougarMagnum', 'Cougar Magnum', 1),
       ('ges', '#GE_D5K_SILENCED', 'D5K (Silenced)', 1),
       ('ges', '#GE_Shotgun', 'Shotgun', 1),
       ('ges', '#GE_Klobb', 'Klobb', 1),
       ('ges', '#GE_RCP90', 'RC-P90', 1),
       ('ges', '#GE_RemoteMine', 'Remote Mines', 1),
       ('ges', '#GE_KF7Soviet', 'KF7 Soviet', 1),
       ('ges', '#GE_ZMG', 'ZMG', 1),
       ('ges', '#GE_SniperRifle', 'Sniper Rifle', 1),
       ('ges', '#GE_GoldPP7', 'Golden PP7', 1),
       ('ges', '#GE_AR33', 'US AR33 Assault', 1),
       ('ges', '#GE_GoldenGun', 'Golden Gun', 1),
       ('ges', '#GE_ThrowingKnife', 'Throwing Knives', 1),
       ('ges', '#GE_PP7', 'PP7', 1),
       ('ges', '#GE_PP7_SILENCED', 'PP7 (Silenced)', 1),
       ('ges', '#GE_TimedMine', 'Timed Mines', 1),
       ('ges', '#GE_MilitaryLaser', 'Military Laser', 1),
       ('ges', '#GE_GrenadeLauncher', 'Grenade Launcher', 1),
       ('ges', '#GE_Rocket', 'Rocket Launcher', 1),
       ('ges', '#GE_Taser', 'Taser', 1),
       ('ges', '#GE_SniperButt', 'Sniper Butt', 1),
       ('ges', '#GE_Slapper', 'Slappers', 1),
       ('ges', '#GE_RocketLauncher', 'Rocket Launcher', 1),
       ('bg2', 'brownbess', 'Brown Bess', 1),
       ('bg2', 'brownbess_bayonet', 'Brown Bess - Bayonet', 1),
       ('bg2', 'charleville', 'Charleville', 1),
       ('bg2', 'charleville_bayonet', 'Charleville - Bayonet', 1),
       ('bg2', 'hirschf', 'Hirschfaenger', 1),
       ('bg2', 'jaeger', 'Jaeger Rifle', 1),
       ('bg2', 'knife', 'Knife', 2),
       ('bg2', 'pennsylvania', 'Pennsylvania', 1),
       ('bg2', 'pistol_a', 'British Pistol', 1.5),
       ('bg2', 'pistol_b', 'American Pistol', 1.5),
       ('bg2', 'sabre_a', 'British Sabre', 1),
       ('bg2', 'sabre_b', 'American Sabre', 1),
       ('sgtls', 'p90', 'FN Herstal P-90 Red Dot / FN-H P-90RD', 1),
       ('sgtls', 'pistol', 'Beretta M92F-s', 1),
       ('sgtls', 'knife', 'Combat Knife', 1),
       ('sgtls', 'staff_blast', 'Staff Weapon', 1),
       ('sgtls', 'p90D', 'FN Herstal P-90 w/ Disruptor', 1),
       ('sgtls', 'hdevice', 'Hand Device / Ribbon Device', 1),
       ('sgtls', 'tac_pulse', 'Tac (turrent)', 1),
       ('sgtls', 'tac_projectile', 'Tac (bomb)', 1),
       ('sgtls', 'c4_charge', 'C4', 1),
       ('sgtls', 'grenade_projectile', 'M67 Frag Grenade', 1),
       ('sgtls', 'g36', 'H&K G-36', 1),
       ('sgtls', 'kull_blast', 'Kull Warrior Staff Device', 1),
       ('sgtls', 'suicide_bomb', 'Goa''uld Suicide Bomb', 1),
       ('sgtls', 'kullblaster', 'Kull Warrior Staff Device (blast)', 1),
       ('sgtls', 'staff', 'Staff Weapon Melee', 1),
       ('sgtls', 'zat_blast', 'Zat', 1),
       ('sgtls', 'awp', 'AWP Rifle', 1),
       ('sgtls', 'grenade', 'M67 Frag Grenade', 1),
       ('sgtls', 'zat', 'Zat (splash)', 1),
       ('sgtls', 'tac', 'Tac (splash)', 1),
       ('dystopia', 'Light Katana', 'Light Katana', 1),
       ('dystopia', 'Medium Katana', 'Medium Katana', 1),
       ('dystopia', 'Fatman Fist', 'Fatman Fist', 1),
       ('dystopia', 'Machine Pistol', 'Machine Pistol', 1),
       ('dystopia', 'Shotgun', 'Shotgun', 1),
       ('dystopia', 'Laser Rifle', 'Laser Rifle', 1),
       ('dystopia', 'BoltGun', 'Bolt Gun', 1),
       ('dystopia', 'SmartLock Pistols', 'Smartlock Pistols', 1),
       ('dystopia', 'Assault Rifle', 'Assault Rifle', 1),
       ('dystopia', 'Grenade Launcher', 'Grenade Launcher', 1),
       ('dystopia', 'MK-808 Rifle', 'MK-808 Rifle', 1),
       ('dystopia', 'Tesla Rifle', 'Tesla Rifle', 1),
       ('dystopia', 'Rocket Launcher', 'Rocket Launcher', 1),
       ('dystopia', 'Minigun', 'Minigun', 1),
       ('dystopia', 'Ion Cannon', 'Ion Cannon', 1),
       ('dystopia', 'Basilisk', 'Basilisk', 1),
       ('dystopia', 'Frag Grenade', 'Frag Grenade', 1),
       ('dystopia', 'EMP Grenade', 'EMP Grenade', 1),
       ('dystopia', 'Spider Grenade', 'Spider Grenade', 1),
       ('dystopia', 'Cortex Bomb', 'Cortex Bomb', 1),
       ('dystopia', 'Leg Boosters', 'Leg Boosters', 1),
       ('dystopia', 'Trap', 'Trap', 1),
       ('dystopia', 'Turret', 'Turret', 1),
       ('nts', 'aa13', 'AA13', 1.00),
       ('nts', 'grenade_projectile', 'Frag Grenade', 1.00),
       ('nts', 'jitte', 'Jitte', 1.00),
       ('nts', 'jittescoped', 'Jitte (Scoped)', 1.00),
       ('nts', 'knife', 'Knife', 1.50),
       ('nts', 'kyla', 'KYLA', 1.00),
       ('nts', 'm41', 'M41', 1.00),
       ('nts', 'm41s', 'M41S', 1.00),
       ('nts', 'milso', 'MilSO', 1.00),
       ('nts', 'mpn', 'MPN45', 1.00),
       ('nts', 'mx', 'MX', 1.00),
       ('nts', 'mx_silenced', 'MX Silenced', 1.00),
       ('nts', 'pz', 'PZ252', 1.00),
       ('nts', 'grenade_detapack', 'Detpack', 1.00),
       ('nts', 'srm', 'SRM', 1.00),
       ('nts', 'srm_s', 'SRM-S', 1.00),
       ('nts', 'srs', 'SRS', 1.00),
       ('nts', 'supa7', 'MURATA SUPA 7', 1.00),
       ('nts', 'tachi', 'TACHI', 1.00),
       ('nts', 'zr68c', 'ZR68C', 1.00),
       ('nts', 'zr68l', 'ZR68L', 1.00),
       ('nts', 'zr68s', 'ZR68S', 1.00),
       ('l4d2', 'rifle', 'M16 Assault Rifle', 1.00),
       ('l4d2', 'autoshotgun', 'Auto Shotgun', 1.00),
       ('l4d2', 'pumpshotgun', 'Pump Shotgun', 1.30),
       ('l4d2', 'smg', 'Uzi', 1.20),
       ('l4d2', 'dual_pistols', 'Dual Pistols', 1.60),
       ('l4d2', 'pipe_bomb', 'Pipe Bomb', 1.00),
       ('l4d2', 'hunting_rifle', 'Hunting Rifle', 1.00),
       ('l4d2', 'pistol', 'Pistol', 2.00),
       ('l4d2', 'prop_minigun', 'Mounted Machine Gun', 1.20),
       ('l4d2', 'tank_claw', 'Tank''s Claws', 2.00),
       ('l4d2', 'hunter_claw', 'Hunter''s Claws', 3.00),
       ('l4d2', 'smoker_claw', 'Smoker''s Claws', 3.00),
       ('l4d2', 'boomer_claw', 'Boomer''s Claws', 3.00),
       ('l4d2', 'jockey_claw', 'Jockey''s Claws', 3.00),
       ('l4d2', 'spitter_claw', 'Spitter''s Claws', 3.00),
       ('l4d2', 'charger_claw', 'Charger''s Claws', 3.00),
       ('l4d2', 'inferno', 'Molotov/Gas Can Fire', 1.20),
       ('l4d2', 'infected', 'Infected Horde', 1.00),
       ('l4d2', 'witch', 'Witch''s Claws', 1.00),
       ('l4d2', 'entityflame', 'Blaze', 3),
       ('l4d2', 'first_aid_kit', 'First Aid Kit Smash', 1.5),
       ('l4d2', 'gascan', 'Gas Can Smash', 1.5),
       ('l4d2', 'molotov', 'Molotov Smash', 1.5),
       ('l4d2', 'pain_pills', 'Pain Pills Smash', 1.5),
       ('l4d2', 'player', 'Player', 1),
       ('l4d2', 'propanetank', 'Propane Tank Smash', 1.5),
       ('l4d2', 'tank_rock', 'Tank''s Rock', 1.5),
       ('l4d2', 'oxygentank', 'Oxygen Tank Smash', 1.5),
       ('l4d2', 'prop_physics', 'Prop Physics', 1),
       ('l4d2', 'defibrillator', 'Defibrillator', 1.5),
       ('l4d2', 'chainsaw', 'Chainsaw', 1),
       ('l4d2', 'grenade_launcher', 'Grenade Launcher Smash', 1.5),
       ('l4d2', 'fire_cracker_blast', 'Fire Cracker', 1),
       ('l4d2', 'grenade_launcher_projectile', 'Grenade Launcher', 0.75),
       ('l4d2', 'pistol_magnum', 'Magnum', 1),
       ('l4d2', 'rifle_ak47', 'AK-47', 1),
       ('l4d2', 'rifle_desert', 'Combat Rifle', 1),
       ('l4d2', 'shotgun_chrome', 'Chrome Shotgun', 1),
       ('l4d2', 'shotgun_spas', 'Combat Shotgun', 1),
       ('l4d2', 'smg_silenced', 'Uzi (silenced)', 1),
       ('l4d2', 'sniper_military', 'Sniper Rifle', 1),
       ('l4d2', 'vomitjar', 'Vomit Jar Smash', 1.5),
       ('l4d2', 'baseball_bat', 'Baseball Bat', 1.5),
       ('l4d2', 'cricket_bat', 'Cricket Bat', 1.5),
       ('l4d2', 'crowbar', 'Crowbar', 1.5),
       ('l4d2', 'electric_guitar', 'Electric Guitar', 1.5),
       ('l4d2', 'fireaxe', 'Fireaxe', 1.5),
       ('l4d2', 'upgradepack_incendiary', 'Incendiary Pack Smash', 1.5),
       ('l4d2', 'frying_pan', 'Frying Pan', 1.5),
       ('l4d2', 'katana', 'Katana', 1.5),
       ('l4d2', 'knife', 'Knife', 1.5),
       ('l4d2', 'machete', 'Machete', 1.5),
       ('l4d2', 'tonfa', 'Tonfa', 1.5),
       ('l4d2', 'insect_swarm', 'Insect Swarm', 1.5),
       ('l4d2', 'melee', 'Melee', 1.5),
       ('l4d2', 'adrenaline', 'Adrenaline Smash', 1.5),
       ('l4d2', 'cola_bottles', 'Cola Bottles Smash', 1.5),
       ('l4d2', 'env_explosion', 'Explosion', 1.5),
       ('l4d2', 'env_fire', 'Fire', 1.5),
       ('l4d2', 'fireworkcrate', 'Fireworks Crate Smash', 1.5),
       ('l4d2', 'gnome', 'Gnome Smash', 1.5),
       ('l4d2', 'rifle_sg552', 'Sig Sauer SG-552 Commando', 1),
       ('l4d2', 'smg_mp5', 'H&K MP5-Navy', 1),
       ('l4d2', 'sniper_awp', 'Arctic Warfare Magnum (Police)', 1),
       ('l4d2', 'sniper_scout', 'Steyr Scout', 1),
       ('l4d2', 'upgradepack_explosive', 'Explosive Pack', 1.5),
       ('l4d2', 'world', 'World', 1),
       ('l4d2', 'golfclub', 'Golf Club', 1.50),
       ('l4d2', 'rifle_m60', 'M60', 1.00),
       ('pvkii', 'zerking', 'Zerking', 1.00),
       ('pvkii', 'slidingdoor', 'Sliding Door', 1.00),
       ('pvkii', 'seaxshield', 'Langseax & Shield', 1.00),
       ('pvkii', 'longbow', 'Long Bow', 1.00),
       ('pvkii', 'chest', 'Chest', 1.00),
       ('pvkii', 'parrot', 'Parrot', 1.00),
       ('pvkii', 'rocks', 'Rocks', 1.00),
       ('pvkii', 'bigaxe', 'Berserker Axe', 1.00),
       ('pvkii', 'gatecrush', 'Gate Crush', 1.00),
       ('pvkii', 'cutlass', 'Cutlass', 1.00),
       ('pvkii', 'twoaxe', 'Huscarl Axe', 1.00),
       ('pvkii', 'spear', 'Spear', 1.00),
       ('pvkii', 'freeze', 'Freeze', 1.00),
       ('pvkii', 'plfall', 'Falling', 1.00),
       ('pvkii', 'steam', 'Steam', 1.00),
       ('pvkii', 'vulture', 'Vultures', 1.00),
       ('pvkii', 'shuriken', 'shuriken', 1.00),
       ('pvkii', 'huscshieldbash', 'Huscarl Shield Bash', 1.00),
       ('pvkii', 'spike', 'Spike', 1.00),
       ('pvkii', 'blunderbuss', 'Blunderbuss', 1.00),
       ('pvkii', 'punch_cpt', 'Punch', 1.00),
       ('pvkii', 'crossbow', 'Crossbow', 1.00),
       ('pvkii', 'env_explosion', 'Explosion', 1.00),
       ('pvkii', 'flintlock', 'Flintlock Pistols', 1.00),
       ('pvkii', 'throwaxe', 'Throwing Axes', 1.00),
       ('pvkii', 'powderkeg', 'Powderkeg', 1.00),
       ('pvkii', 'physics', 'Physics', 1.00),
       ('pvkii', 'boulder', 'Boulder', 1.00),
       ('pvkii', 'drowned', 'Drowned', 1.00),
       ('pvkii', 'barrel', 'Barrel', 1.00),
       ('pvkii', 'axesword', 'Sword & Axe', 1.00),
       ('pvkii', 'cutlass2', 'Captain''s Cutlass', 1.00),
       ('pvkii', 'flames', 'Flames', 1.00),
       ('pvkii', 'vikingshield', 'Huscarl Sword & Shield', 1.00),
       ('pvkii', 'thrownkeg', 'Thrown Powderkeg', 1.00),
       ('pvkii', 'archersword', 'Short Sword', 1.00),
       ('pvkii', 'player', 'Player', 1.00),
       ('pvkii', 'worldspawn', 'World', 1.00),
       ('pvkii', 'twosword', '2 Handed Sword', 1.00),
       ('pvkii', 'hook', 'Hook', 1.00),
       ('pvkii', 'hkshieldbash', 'Heavy Knight Bash', 1.00),
       ('pvkii', 'javelin', 'Javelins', 1.00),
       ('pvkii', 'swordshield', 'Heavy Knight Sword/Shield', 1.00),
       ('pvkii', 'crusher', 'Crusher', 1.00),
       ('valve', '357', '357 Revolver', '1.60'),
       ('valve', '9mmAR', '9mm Automatic Rifle', 1.00),
       ('valve', '9mmhandgun', '9mm Handgun', 1.50),
       ('valve', 'bolt', 'Crossbow Bolt', 1.70),
       ('valve', 'crossbow', 'Crossbow', 1.40),
       ('valve', 'crowbar', 'Crowbar', 1.90),
       ('valve', 'tau_cannon', 'Egon Tau Cannon / Rail Gun', 1.00),
       ('valve', 'gluon gun', 'Gluon / Gauss Gun', 1.00),
       ('valve', 'grenade', 'Grenade', 1.00),
       ('valve', 'hornet', 'Hornet', 1.30),
       ('valve', 'rpg_rocket', 'Rocket Propelled Grenade', 1.00),
       ('valve', 'satchel', 'Satchel Charge', 1.50),
       ('valve', 'shotgun', 'Shotgun', 1.20),
       ('valve', 'snark', 'Snark', 1.80),
       ('valve', 'tripmine', 'Trip Mine', 1.60),
       ('nd', 'armblade', 'BLADES', 1.00),
       ('nd', 'armknives', 'KNIVES', 1.00),
       ('nd', 'artillery', 'Artillery', 0.70),
       ('nd', 'avenger', 'C1 AVENGER', 1.00),
       ('nd', 'bag90', 'BAG-90', 2.00),
       ('nd', 'chaingun', 'GAU-20P', 1.00),
       ('nd', 'commander damage', 'Commander Damage Ability', 0.60),
       ('nd', 'commander poison', 'Commander Poison Ability', 1.00),
       ('nd', 'daisy cutter', 'DAISYCUTTER', 2.00),
       ('nd', 'f2000', 'FN-H F2100 TR', 1.00),
       ('nd', 'env_explosion', 'Environment Explosion', 1.50),
       ('nd', 'flamethrower turret', 'Flamethrower Turret', 0.40),
       ('nd', 'frag grenade', 'M-87 FRAG', 1.50),
       ('nd', 'grenade launcher', 'M52 HYDRA', 1.50),
       ('nd', 'm95', 'M-95 L.A.W.S.', 1.00),
       ('nd', 'mg turret', 'Machine-gun Turret', 0.40),
       ('nd', 'mp500', 'MP-500', 1.20),
       ('nd', 'mp7', 'MP-7', 1.20),
       ('nd', 'nx300', 'NX-300', 1.50),
       ('nd', 'p12 grenade', 'P12 POISON', 2.00),
       ('nd', 'p900', 'P-900', 2.00),
       ('nd', 'paladin', 'PALADIN PLR-5', 1.00),
       ('nd', 'pp22', 'PP-22', 1.20),
       ('nd', 'psg', 'PSG-L', 1.00),
       ('nd', 'R.E.D.', 'R.E.D', 1.50),
       ('nd', 'repair tool', 'BLOWTORCH', 5.00),
       ('nd', 'rocket turret', 'Rocket Turret', 0.40),
       ('nd', 'shotgun', 'SPETZ-9', 1.40),
       ('nd', 'sonic turret', 'Sonic Turret', 0.40),
       ('nd', 'sp5', 'SP-5 K1', 1.30),
       ('nd', 'u23 grenade', 'U23 POISON', 2.00),
       ('nd', 'world', 'World', 1.00),
       ('nd', 'x01', 'X-01', 1.00),
       ('csgo', 'ak47', 'Kalashnikov AK-47', 1.00),
       ('csgo', 'm4a1', 'M4A4', 1.00),
       ('csgo', 'awp', 'AWP', 1.00),
       ('csgo', 'deagle', 'Desert Eagle', 1.20),
       ('csgo', 'hkp2000', 'P2000', 1.40),
       ('csgo', 'galilar', 'Galil', 1.10),
       ('csgo', 'glock', 'Glock-18', 1.40),
       ('csgo', 'bizon', 'PP-Bizon', 1.30),
       ('csgo', 'galil', 'Galil', 1.10),
       ('csgo', 'p90', 'FN P90', 1.20),
       ('csgo', 'aug', 'Steyr Aug', 1.00),
       ('csgo', 'mp7', 'MP7', 1.30),
       ('csgo', 'elite', 'Dual Berretta Elites', 1.40),
       ('csgo', 'ssg08', 'SSG 08', 1.10),
       ('csgo', 'sg553', 'SG 553', 1.00),
       ('csgo', 'nova', 'Nova', 1.30),
       ('csgo', 'p250', 'P250', 1.50),
       ('csgo', 'knife', 'Knife', 2.00),
       ('csgo', 'ump45', 'H&K UMP45', 1.20),
       ('csgo', 'sawedoff', 'Sawed-Off', 1.30),
       ('csgo', 'mag7', 'MAG-7', 1.30),
       ('csgo', 'hegrenade', 'High Explosive Grenade', 1.80),
       ('csgo', 'mp9', 'MP9', 1.40),
       ('csgo', 'tec9', 'Tec-9', 1.20),
       ('csgo', 'scar20', 'Scar-20', 0.80),
       ('csgo', 'xm1014', 'XM1014', 1.10),
       ('csgo', 'fiveseven', 'FN Five-Seven', 1.50),
       ('csgo', 'negev', 'Negev', 1.00),
       ('csgo', 'mac10', 'MAC-10', 1.50),
       ('csgo', 'g3sg1', 'H&K G3/SG1 Sniper Rifle', 0.80),
       ('csgo', 'm249', 'M249 PARA Light Machine Gun', 1.00),
       ('csgo', 'inferno', 'Incendiary Grenade', 1.80),
       ('csgo', 'taser', 'Zeus x27', 1.00),
       ('dinodday', 'fists', 'Berserk Punch', 1.30),
       ('dinodday', 'flechette', 'Flechette Gun', 1.40),
       ('dinodday', 'jackrabbit', 'Jackrabbit', 1.40),
       ('dinodday', 'flak30', 'Desmatosuchus Flak 30', 1.30),
       ('dinodday', 'k98sniper', 'Karabiner 98 Sniper', 1.50),
       ('dinodday', 'mg42', 'Maschinengewehr 42', 1.20),
       ('dinodday', 'pterosaur', 'Pterosaur Strike', 1.30),
       ('dinodday', 'claws', 'Claw Attack', 1.70),
       ('dinodday', 'k98', 'Karabiner 98', 1.70),
       ('dinodday', 'mosin', 'Mosin Nagant', 1.50),
       ('dinodday', 'artillery', 'Artillery Strike', 1.20),
       ('dinodday', 'piat', 'PIAT Mk I', 1.20),
       ('dinodday', 'stickgrenade', 'Stielhandgranate 43', 1.40),
       ('dinodday', 'luger', 'P08 Luger', 1.60),
       ('dinodday', 'bar', 'Browning Automatic Rifle M1918', 1.20),
       ('dinodday', 'garand', 'M1 Garand', 1.30),
       ('dinodday', 'trenchknife', 'Kampfmesser', 1.70),
       ('dinodday', 'kabar', 'KA-BAR Combat Knife', 1.70),
       ('dinodday', 'pistol', 'Colt M1911', 1.60),
       ('dinodday', 'grenade', 'Hand Grenade MKII', 1.40),
       ('dinodday', 'shotgun', 'Trench Gun M1897', 1.40),
       ('dinodday', 'thompson', 'M1 Thompson', 1.20),
       ('dinodday', 'mp40', 'Maschinenpistole 40', 1.20),
       ('dinodday', 'sticky', 'Sticky Bomb', 1.40),
       ('dinodday', 'mp44', 'Sturmgewehr 44', 1.20),
       ('dinodday', 'dilophosaurus', 'Dilophosaurus Claws', 1.70),
       ('dinodday', 'satchel', 'Satchel Charge', 1.30),
       ('dinodday', 'sten', 'Sten Mk II', 1.20),
       ('dinodday', 'p38', 'Pistole 38', 1.60),
       ('dinodday', 'nagant', 'Nagant M1894', 1.60),
       ('dinodday', 'fistsregular', 'Fists', 1.70),
       ('dinodday', 'styracosaur', 'Styracosaur', 1.30),
       ('dinodday', 'trex', 'T-Rex Dual-MG42', 1.20),
       ('dinodday', 'trexbomb', 'T-Rex Bomb Throw', 1.50),
       ('dinodday', 'tankmine', 'Tankmine', 1.30),
       ('dinodday', 'trigger', 'Trigger .30cal', 1.20),
       ('dinodday', 'stygimoloch', 'Stygimoloch MG34', 1.20),
       ('dinodday', 'compy', 'Compsognathus', 1.70),
       ('dinodday', 'flamethrower', 'Flamethrower', 1.40),
       ('dinodday', 'microraptor', 'Microraptor Claws', 1.70),
       ('dinodday', 'carbine', 'M1 Carbine', 1.25),
       ('dinodday', 'greasegun', 'M3 Grease Gun', 1.20),
       ('dinodday', 'pounce', 'Velociraptor Pounce', 1.70),
       ('dinodday', 'desmamelee', 'Desmatosuchus Melee', 1.70),
       ('dinodday', 'body', 'Dilophosaurus Body Throw', 1.30),
       ('dinodday', 'stygihead', 'Stygimoloch Headbutt', 1.70),
       ('dinodday', 'suicide', 'Compsognathus Suicidebomb', 1.70),
       ('dinodday', 'spit', 'Microraptor Acidspit', 1.70),
       ('dinodday', 'triggerhead', 'Trigger Headbutt', 1.70),
       ('dinodday', 'dinner', 'T-Rex Dinner', 1.70),
       ('dinodday', 'stomp', 'T-Rex Stomp', 1.70),
       ('dinodday', 'goat', 'Dilophosaurus Goat Throw', 1.90);